### ISSUE TITLE
`.modal()` is not a function, and needs to be moved

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#1008]
## Problem

`maps/slug` previously rendered an editable map, with an intro modal explaining how to edit it:
![image](https://user-images.githubusercontent.com/41092741/64666128-2454ec80-d423-11e9-9f81-e76ca1bc8155.png)

We updated our paths so that the map view at `maps/slug` is just a preview of the map, and to get to the previous edit view you have to click `Edit this map` (bottom right directly under map)
![image](https://user-images.githubusercontent.com/41092741/64666043-e2c44180-d422-11e9-9420-0837f988579e.png)

The editable map's updated path is `maps/slug/edit`.

In making these updates, we did not update the logic for the `modal`, which should display the first time a user opens their map for editing. The left behind code is:

https://github.com/publiclab/mapknitter/blob/88c6cb427401754130f68cb6e0871ca443e0ef75/app/views/maps/show.html.erb#L96-L98

It throws an error `TypeError: $(...).modal is not a function` is not a function. Currently no modal shows ever.

## Solution

- [ ] We need to delete the conditional block above. It no longer belongs in the show view.

- [ ] You will also find this conditional in `app/views/layouts/knitter2.html.erb`
https://github.com/publiclab/mapknitter/blob/88c6cb427401754130f68cb6e0871ca443e0ef75/app/views/layouts/knitter2.html.erb#L196-L198

it should now be `params[:action] == "edit"`

3. The hard part (this part was never implemented): we only want the modal to open once for a map. The conditional check `@map.warpables.empty?` does this by checking if there are any warpables (images) on the map. This works fine, unless you delete all the images on the map and refresh the page. By this logic, its your first time viewing the map and the modal pops up.

- [ ] We need to write a conditional that takes this case into account. Or refactor completely for a new solution.

### Notes

- a new map instance is created on every page refresh, so need to consider if it is possible to store this additional logic in JS and how
- a function that only executes once also wouldn't work, because then the modal won't show for any future maps.
- resolve this however you'd like - server-side, front-end, etc. Can refactor completely if you'd like.

**Comment by sashadev-sky** [comment]
@cesswairimu @divyabaid16 @jywarren

**Comment by sashadev-sky** [comment]
@SidharthBansal is this how I create GCI tasks for now? just the label? 
Also would love your input on the issue, and if you have any opinions on the solution you can edit it to guide the developer in that direction. 

Also is this appropriate difficulty? I have not made GCI tasks before

**Comment by SidharthBansal** [comment]
Awesome!
Just put a line in the issue body stating this issue is reserved for GCI only.
Please see last yr GCI solved issues so that you can copy paste from it.
Thanks

**Comment by divyabaid16** [comment]
This is very well written @sashadev-sky 
According to me, it is a good task for GCI.
Thanks!

**Comment by jywarren** [comment]
Oh, actually i wonder if this is too high priority for GCI. This would be a
blocking issue for publishing to production, don't you think?

But, thanks for documenting and for organizing for GCI!!!

**Comment by sashadev-sky** [comment]
@jywarren its not a showstopper but I see what you mean. I can fix it, but really I was not sure how to handle point 3 myself
