### ISSUE TITLE
logging in does not work in development or production

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#1010]
### What happened just before the problem occurred

Clicking on any of the `login`s available throughout the site results in something like this:

```Ruby
Started GET "/sessions/create?authenticity_token=z7ojHOQtzkyk1fcyrUpixkJ5vb4GTyVJSLhljBqinofmF%2BXfkbzcH86fAkjUZj8Ktg%2BLfZT%2B5igldIog4MeofQ%3D%3D&back_to=%2F&subaction=github" for ::1 at 2019-09-11 05:55:28 -0400
Processing by SessionsController#create as HTML
  Parameters: {"authenticity_token"=>"z7ojHOQtzkyk1fcyrUpixkJ5vb4GTyVJSLhljBqinofmF+XfkbzcH86fAkjUZj8Ktg+LfZT+5igldIog4MeofQ==", "back_to"=>"/", "subaction"=>"github"}
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)


WARNING: making https request to https://publiclab.org/people/identity/github without verifying server certificate; no CA path was specified.
Processing by SessionsController#create as HTML
  Parameters: {"authenticity_token"=>"z7ojHOQtzkyk1fcyrUpixkJ5vb4GTyVJSLhljBqinofmF+XfkbzcH86fAkjUZj8Ktg+LfZT+5igldIog4MeofQ==", "back_to"=>"/", "subaction"=>"github"}
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)


  
NoMethodError (undefined method `split' for nil:NilClass):
  
app/controllers/sessions_controller.rb:71:in `block in openid_authentication'
app/controllers/sessions_controller.rb:69:in `openid_authentication'
app/controllers/sessions_controller.rb:45:in `create'
```

this isn't exact because I messed around with inputs a little bit to try to debug but the errorr stays the same regardless.

Complaint seems to be that `identity_url`is always nil -- in browser:
![image](https://user-images.githubusercontent.com/41092741/64688484-6c433600-d45a-11e9-8ac6-b84043b02226.png)

seems to be broken for most recent previous commits in MK as well

**Comment by sashadev-sky** [comment]
@jywarren

**Comment by sashadev-sky** [comment]
@divyabaid16 tried fetching your pr and running locally
https://github.com/publiclab/mapknitter/pull/969
and even that wouldn't work. any idea why?

**Comment by jywarren** [comment]
Hi, on the live site at MapKnitter.org (which is usually what I think of as "production" but there's definitely an ambiguity there, so i'll start being more specific) the Sign Up menu item in far upper right works:

![image](https://user-images.githubusercontent.com/24359/64703521-9a387280-d47a-11e9-90b8-9f8838899c01.png)

(2 tabs successfully opened from the different options here)

However I see that when I click the Google, Twitter or Facebook buttons after clicking `Make a map`, nothing happens:

![image](https://user-images.githubusercontent.com/24359/64703659-e7b4df80-d47a-11e9-89e9-8673595d037b.png)

`sign up for a Public Lab account` does work. But I'm not sure it preserves a path back. 

Ideally all of these in the `Make a Map` popup would re-use code from the navbar. 

Sasha, where exactly are you seeing the Login prompts that don't work, have I reproduced your issue in the `Make a Map` popup? Thank you!

**Comment by jywarren** [comment]
I see you've copied the navbar login partial in #1011 and I believe that solves all issues I have found. But i'll keep looking for instances of `Login` not working, i may have missed something.

**Comment by sashadev-sky** [comment]
Confirming production is fine. Let me double check locally, I think I was having issues on both for some reason. Also yes production for me means the live site

**Comment by sashadev-sky** [comment]
ah yay fixed. Closing!
