### ISSUE TITLE
Research and document anonymous editing and the purpose of MapKnitter

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#1021]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

# Problem

There has been much discussion on why we allow anonymous users to create maps, as it creates complications. See #445, for example. 

We have decided to move forward with anonymous users and continue improving our implementation of it. 

We would like to explain why we do this and document how it works in a new [wiki file](https://github.com/publiclab/mapknitter/wiki). This is a research issue and we would like it to align with MK's purpose overall.

# Solution:

[Focusing around this quote](https://github.com/publiclab/mapknitter/issues/445#issuecomment-521315865):

> "We have had input from community partners that people who may be vulnerable or are concerned about being connected to data produced on MapKnitter.org may be more comfortable producing maps anonymously, despite the drawbacks. So we have continued to allow this although we are getting better at explaining why it presents difficulties like this one, and trying to help people make a good decision about whether to use an anonymous map or not."

**Please cover:**

- **Conceptual**: what type of impact might MK make environmentally, and why might people want to be anonymous in their contributions to this? You can reference [MK's roots in the BP oil crisis](https://publiclab.org/wiki/stories). 

- **User experience**: what privileges do anonymous authors lose? what privileges do they have? (ie. map/image deletion, editing)

- **Code architecture**: what is the current architecture we use for anonymous users (authentication, etc.)? What are the possible downfalls (ie. moderation, spam, etc.) and what will we do in the future to make it more sophisticated?

**some research ideas**: 
- Talk to people - feel free to discuss this prompt with any mentors or @jywarren and @ebarry!
- Run MapKnitter locally and try creating an anonymous map. Then try creating one logged in using credentials we provide for our testing environment (https://github.com/publiclab/mapknitter#logging-in-when-running-locally)
- Look at the source code
- [Our issues page filtered by the word "anonymous"](https://github.com/publiclab/mapknitter/issues?page=2&q=is%3Aissue+anonymous&utf8=%E2%9C%93)
- [Our PRs page filtered by the word "anonymous"](https://github.com/publiclab/mapknitter/pulls?utf8=%E2%9C%93&q=is%3Apr+anonymous)
- https://publiclab.org
- http://mapknitter.org

##  💬   Get help
If you need any help - here are some options: 
- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

Labeled `hard` because questions cover broad scope and require a deeper understanding of both PL's mission and grassroots mapping.

**Comment by jywarren** [comment]
This is so awesome. Thank you! Rad! And - the output of this could be posted at PublicLab.org as well. ❤️

**Comment by sashadev-sky** [comment]
@jywarren thank you!! I have come to learn that "rad" is the highest form compliment there is 🚀

**Comment by jywarren** [comment]
lol!!! I'm just catching up on all the work you've been doing so forgive me! ❤️ 

Rad! 🚀 🎸

**Comment by sashadev-sky** [comment]
**Uploaded on GCI dashboard**

**Comment by ebarry** [comment]
Yay! What timezone are you in Sasha that you posted this at 2am?

**Comment by SidharthBansal** [comment]
Oh, you all check the times too! It is great.
One interesting thing: Person mails to github. Then the timezone can be found by clicking on `...` button. :-)
Sasha can you please tell me if this issue can be broken into two separate issues:
1)Anonymous Editing Doc
2) Purpose MK doc
GCI students don't know the rules of documentation. Last year, I helped them by telling them each point which is taught in CSE branch. So, I will really like if this can be divided into 2 separate `hard` labelled issues.
Also, please hide unwanted comments before uploading to GCI dashboard to prevent confusion for students! They are new to tech and obviously GH

**Comment by SidharthBansal** [comment]
Love your issue :heart:

**Comment by SidharthBansal** [comment]
Published

**Comment by SidharthBansal** [comment]
Let's write documentation of Anonymous editing first :-)
Once you have completed it then please ping me to create second task for the remaining of the issue.

**Comment by Uzay-G** [comment]
Hey @sashadev-sky @cesswairimu I am so excited to be working on this issue! It's really interesting to learn more about the roots of this amazing project :smile:. I also really like writing so I couldn't be happier.

**Comment by Uzay-G** [comment]
Hey @jywarren could I ask you about this quote:
>We have had input from community partners that people who may be vulnerable or are concerned about being connected to data produced on MapKnitter.org may be more comfortable producing maps anonymously, despite the drawbacks. So we have continued to allow this although we are getting better at explaining why it presents difficulties like this one, and trying to help people make a good decision about whether to use an anonymous map or not. Thanks!

I understand the problem of privacy but I can't really think of a situation where this might become a problem related to the data on Mapknitter. 
Could you maybe give me a vague example?
Thanks

**Comment by Uzay-G** [comment]
Hey @jywarren @sashadev-sky @cesswairimu I've been working on a rough draft for the documentation [here](https://github.com/Uzay-G/mapknitter/blob/style/anonymity.md). It is still in its early stages but I would love to hear what you think I should focus on or correct.
Thanks again!

**Comment by cesswairimu** [comment]
Great I will take a look

**Comment by Uzay-G** [comment]
Thanks @cesswairimu! It's just a start but I would really appreciate to hear your feedback

**Comment by jywarren** [comment]
Hi, sure -- privacy concerns can go many different directions. At the most basic level, people may be worried that sensitive information about them may be revealed - like, their location, if they are in danger for some reason - or for example political activity, if they are in a place where their activity is not permitted or it puts them at risk. There are many different scenarios where posting information on MapKnitter could present a risk -- even a small risk -- which they don't want to take. Making an anonymous map could help them to not reveal their identity, or to make it harder to identify them. 

It's very hard to imagine either being vulnerable the way someone else is, or to understand the many ways different people could be at risk. So we take it as enough that this has been expressed as a concern and as it's not very burdensome to allow anonymous maps, we are happy to provide them to those who want to make maps that way. 

Our approach is that where we want to add features that are helpful but don't work (or don't work easily) with anonymously authored maps, we explain why, and let people make an informed decision. 

Thanks!

**Comment by Uzay-G** [comment]
Ok thanks a bunch for your detailed response!

**Comment by Uzay-G** [comment]
Hey @sashadev-sky do you think for the technical section do you think I shouldn't link to the issues and instead explain more in depth what they talk about?
