### ISSUE TITLE
should give warning about "return to editor" being permanent save for anon maps

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#1025]
We have an ability to create a map without login-in, these maps are marked as created by "anonymous".  During creation of such a map, when you click on "return to editor" means permanent save, since a not logged in user cannot edit/delete maps. 

### To do
We need to add a warning about clicking on "create map" button being permanent save for anonymous maps. This is the  button https://github.com/publiclab/mapknitter/blob/main/app/views/maps/new.html.erb#L76

### Relevant URLs
https://mapknitter.org/maps/new

--------------------------------------------
We are participating in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more

**Comment by jywarren** [comment]
We could use a `data-confirm="Are you sure? This ....."` attribute on the link, so a popup appears?

**Comment by SidharthBansal** [comment]
@cesswairimu @sashadev-sky @jywarren can anyone explain me the issue?
I can't understand it. Sorry!

**Comment by cesswairimu** [comment]
@SidharthBansal, I just added some context on the description. thanks

**Comment by cesswairimu** [comment]
We are participating in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more

**Comment by SidharthBansal** [comment]
This should be in the issue body @Cess. :-)

**Comment by cesswairimu** [comment]
Oh, my bad adding that...Thanks @SidharthBansal

**Comment by SidharthBansal** [comment]
Published on GCI dashboard

**Comment by Uzay-G** [comment]
Hey, I am just waiting for another task and then I will submit the pull request for this.
Thanks :+1:!

**Comment by SidharthBansal** [comment]
you can submit the pr for it. don't wait for codecov pr
Thanks
