### ISSUE TITLE
500 error: Render and/or redirect were called multiple times on stable

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#1027]
Got this upon submitting the form at http://mapknitter-stable.laboratoriopublico.org/maps/new -- 

```
Completed 500 Internal Server Error in 78ms (Views: 10.9ms | ActiveRecord: 54.7ms) 
D, [2019-09-14T16:12:38.762116 #289] DEBUG -- : [1c2b0fe1-aab7-4931-8f80-5ef013990301] Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return". excluded from capture: DSN not set 
```

I think it's because of these two `render 'new'`:

https://github.com/publiclab/mapknitter/blob/8f04db55955fd698e3795fe353b5773a9663e88c/app/controllers/maps_controller.rb#L45-L52

**Comment by jywarren** [comment]
Looks like we just remove the one on line 45. Surprised that tests didn't catch this!

**Comment by jywarren** [comment]
Filed a fix at #1026 ttps://github.com/publiclab/mapknitter/pull/1028

**Comment by sashadev-sky** [comment]
@jywarren sorry! I had through that when a rails controller hits a `render` or a `redirect`, its like hitting a `return` statement. Is this not the case?

**Comment by jywarren** [comment]
There is some odd reason why you can't render twice... i think it's not the
same as a redirect!
