### ISSUE TITLE
Add "use current location" button to new map page

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#1036]
We currently show a lat/lon and location search here:

https://mapknitter.org/maps/new

However, it could be useful to add a button to geolocate yourself, as we do on the front page, and to use that location 

We could use a button in the same input group, attached to the right side of the input field for location, with the icon `crosshairs` - https://fontawesome.com/v4.7.0/icon/crosshairs

![image](https://user-images.githubusercontent.com/24359/65156369-fa8c5e80-d9fc-11e9-9f5b-5f3041ff705c.png)

This would take the following code: (see the final "div" for the new button)

```html
<div class="input-group">
      <div class="input-group-prepend"><button class="btn btn-outline-secondary" type="button"><i class="fa fa-search"></i></button></div>
      <input class="form-control ui-autocomplete-input" tabindex="2" type="text" value="" name="map[location]" id="map_location" autocomplete="off">
    <div class="input-group-append"><button class="btn btn-outline-secondary btn-geocode-map" type="button"><i class="fa fa-crosshairs"></i></button></div>
</div>
```

It'd go here:

https://github.com/publiclab/mapknitter/blob/684338a3f8a2fcd26107438e11224d20fbb37a5a/app/views/maps/new.html.erb#L34-L38

The next step is a little harder. We'll have to attach a `$('.btn-geocode-map').click()` handler and in `.click(function() { ... })` we'll have to handle the returned location and splice them into the latitude/longitude fields on the form. 

We can use the `map.locate()` method in Leaflet, like we do on the front page:

https://github.com/publiclab/mapknitter/blob/fc4a042b7c53c2eac94aa37225eca364cdcc4bf7/app/views/front_ui/index.html.erb#L234-L267

We'd love help with this!

**Comment by jattoabdul** [comment]
Hi @jywarren
I am having some issues setting the project up on `https://codenvy.io`. I am getting an error `Mysql2::Error::ConnectionError (Access denied for user 'user'@'localhost' (using password: NO))` when I run and load the app.

I am also getting this error(`Your Ruby version is 2.4.4, but your Gemfile specified 2.4.6`) too even though the app runs and tries to load.

PS: I followed the setup instructions on the Repo Readme.

**Comment by jywarren** [comment]
Hi! Sorry you had trouble! Did you run the whole `install_cloud.sh` file and did it run without errors? You may also find other people going through the same steps at #307 which may be helpful. 

If you read through this file, it shows each step in order -- it's possible we need to update some for the latest Codenvy setup, but the errors you're seeing above maybe suggest the whole file didn't run completely? https://github.com/publiclab/mapknitter/blob/main/install_cloud.sh

**Comment by blurry-x-face** [comment]
Hi, Can I work on this issue?
