### ISSUE TITLE
"File size limit exceeded" should return more useful error

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#105]
<pre>
App 14781 stdout: convert -contrast-stretch 0 public/warps/goteborg2-working/229270-amin.png -crop 476612x476612+0+0! -flatten -distort Perspective '0,
0 0,0  1245,0 476612,0  1245,834 476612,319330  0,834 0,319330' -flatten -crop 476612x476612+0+0! +repage public/warps/goteborg2/229270.png
App 14781 stdout:
App 14746 stderr: File size limit exceeded
App 14781 stdout: convert +antialias -size 476612x476612  xc:none -draw "fill black stroke red stroke-width 30 polyline 0,0 476612,0 476612,319330 0,31
9330 0,0"  -alpha set -channel A -transparent red -blur 0x8 -channel R -evaluate set 0 +channel public/warps/goteborg2/229270-mask.png
App 14746 stderr: File size limit exceeded
</pre>

**Comment by gauravano** [comment]
Hey @jywarren,  this issue somewhat relates to the file size upload issue - https://github.com/publiclab/mapknitter/issues/203 . I think, this can also be closed and we can track File-upload in a single issue. What do you think?

**Comment by jywarren** [comment]
yep!

**Comment by gauravano** [comment]
Awesome! Closing this and let's track the file limit at #328 only. Thanks!
