### ISSUE TITLE
Move anonymous styling to app/assets/stylesheets

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/mapknitter#1066]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### Description
Rails convention dictates that styling should not be done on the view level but rather on the assets
### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** these files https://github.com/publiclab/mapknitter/blob/main/app/views/front_ui/anonymous.html.erb and https://github.com/publiclab/mapknitter/blob/main/app/assets/stylesheets/style.scss (press the little pen Icon) and edit the line as shown below. 

1. Change this line https://github.com/publiclab/mapknitter/blob/main/app/views/front_ui/anonymous.html.erb#L3  to 
`   <div class= "text-block text-anonymous">`

2. Delete these block of code https://github.com/publiclab/mapknitter/blob/main/app/views/front_ui/anonymous.html.erb#L15-L44

3. At the end of this file https://github.com/publiclab/mapknitter/blob/main/app/assets/stylesheets/style.scss add this piece of code
```
.text-anonymous {
    text-align: left;
    margin: 20px;
    padding: 50px;
    width: 60%;
    margin-left: 17%;
  }
  
  
  @media (max-width: 750px) {
    .text-anonymous {
      width: 100%;
      margin: 10px;
      padding: 10px;
    }
  }


```
[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

### Relevant URLs

 http://mapknitter-stable.laboratoriopublico.org/maps/test

The page to be changed is https://github.com/publiclab/mapknitter/blob/main/app/views/maps/show.html.erb

**Comment by cesswairimu** [comment]
@Akashutreja here is an issue for you

**Comment by kiyominox** [comment]
I would like this please.

**Comment by cesswairimu** [comment]
Hi @kiyominox, sorry, this is reversed for @Akashutreja...If you looking for a first-timer issue please leave a comment here https://github.com/publiclab/plots2/issues/6206 and we will get an issue for you. Or if you  can browse and look for an unassigned issue. Thanks

**Comment by Akashutreja** [comment]
Hi @cesswairimu, I have raised pr. please review this and thanks for assigning the issue.

**Comment by briannadeg** [comment]
I would like this please

**Comment by b18050** [comment]
i will work on this

**Comment by gr455** [comment]
If no one is currently working on this issue, can I work on it?

**Comment by cesswairimu** [comment]
@gr455, the opened PRs did not complete the whole tasks and no communication has been done for a while. You can do ahead and work on this. Thanks

**Comment by Kajol-Kumari** [comment]
I would like to work on this if no one currently is working on it.
