### ISSUE TITLE
no sensible error when config/initializers/recaptcha.rb is not present

### ISSUE THREAD

**Issue by icarito** [publiclab/mapknitter#1112]
This file is needed for starting the app but the error that appears when launching without it is confusing. It took me a while to figure it out so I suggest we should improve this.

**Comment by icarito** [comment]
This is actually documented in the installation steps... :-/

**Comment by SidharthBansal** [comment]
PUBLISHED ON GCI DASHBOARD

**Comment by CodeSarthak** [comment]
Hey @icarito can you please help me out a bit by pointing me to the code links? I am not able to figure them out exactly.

**Comment by Uzay-G** [comment]
@icarito should I work on this or are the instructions in the documentation enough? Thanks!

**Comment by tsparksh** [comment]
I dont see any errors while starting without recaptcha config, how can I reproduce this issue?

**Comment by sashadev-sky** [comment]
@icarito please follow up with us here!

**Comment by icarito** [comment]
@sashadev-sky and all, sorry I missed all this activity! I think the PR by @VladimirMikulic should solve this particular issue! Thanks a ton for working on it!

**Comment by VladimirMikulic** [comment]
@icarito you are most welcome :tada:

**Comment by VladimirMikulic** [comment]
@icarito could you please approve the PR so they can merge it. Thanks a lot.
