### ISSUE TITLE
Remove sudo from yarn installation command in README [First Timers Only]

### ISSUE THREAD

**Issue by pythongiant** [publiclab/mapknitter#1146]
### What happened just before the problem occurred
The yarn installation command in the README is stated as `sudo npm -g install yarn`. this is not recommended.

### Relevant URLs

https://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo

**Comment by CodeSarthak** [comment]
Relevant reasoning : https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92

**Comment by cesswairimu** [comment]
Mmmh I think we wonna keep sudo there @publiclab/mapknitter-reviewers what do you think?
