### ISSUE TITLE
Weekly community Check-In #41 -Everybody Struggles

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/mapknitter#1150]
Hi everyone 👋

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## Everybody Struggles

This is one of the themes for the weeks on Outreachy and I always love it because with coding sometimes it can be frustrating. It helps to know that everyone goes through and its part of the process getting amazing work out in the world :smile:. 
This week share of something that you have been struggling with or have struggled with. We won't judge just want to show that coding sometimes we struggle. 

## This week's focus Issues

These are issues that are of high priority and requests from our 
large community that use the software. We will very much appreciate any help on these issues. Any contributor who is looking for issues to work on please consider taking a look at these. Or you can add more context to the ones labeled `gci-candidate` so that they can be taken up by the gci folks.  We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance :smile: 

https://github.com/publiclab/Leaflet.DistortableImage/labels/high-priority

## Note to GCI participants 💻 

So glad to have all the gci participants in our community :tada: :tada:  we are happy to have you and you are all doing amazing work :rocket: 
Really love the collaboration you are doing, commenting on others PR and issues, leaving reviews and helping each other out :tada: :tada: 
Please don't hesitate to ask for help if you are stuck for a while. 

 ## Note to Outreachy interns  👨‍💻 👩‍💻

@nstjean and @crisner we are happy to to have you :smile: we normally have the interns leave a comment here on what they are working on that week and leave any links to blogs that you might have. Keep up the great work, collaboration and planning :rocket: 

## Next Check-in

If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time :smile: 

**Thanks everyone for making Public Lab awesome** :balloon: 
Have a great week ahead all :heart:

**Comment by cesswairimu** [comment]
@Rishabh570 @sashadev-sky @IshaGupta18 @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo

**Comment by cesswairimu** [comment]
@shashwataggarwal, @yeo-yeo, @Uzay-G, @dependabot-preview[bot], @chen-robert, @VladimirMikulic, @gabrielrumiranda, @mikepetridisz, @GarvinH, @Ugtan, @sap143, @arjunshekhawat5, @nstjean, @sagarpreet-chadha, @ami-friedman, @gautamig54, @shubhankarsharma00, @rebecarancan, @swathi-0901, @rojasTob, @rosensteinsamuel1, @jairus-crabb, @kamal-kaur04, @Ruchika06, @1405043-kd, @stefanosu, @ChamuMutezva, @Thunder80, @nicoleiocana, @gptshubham595, @Tanish0019, @dare892, @yamiacat, @crtlf, @mathyoudawson, @CleverFool77, @seabl, @nishantwrp, @marcin-wicha, @vaibhavmathur13, @klaffert, @WulfPlasma, @crisner

**Comment by chen-robert** [comment]
It's been super fun working here! I've currently been learning a lot about Ruby model validations (maybe a bit too much even :smile:) in trying to fix the validation errors on the PL signup. Hopefully I'll be able to finish up my PR sometime this week!

How's everyone been doing? :tada:

**Comment by Uzay-G** [comment]
Yeah it's really amazing. I learned how to setup travis ci for the simple data grapher repo and it's so cool to see the automatic testing. What have you guys been working on?

**Comment by SidharthBansal** [comment]
I am working on my nlp project. :-)

**Comment by Uzay-G** [comment]
That's cool @SidharthBansal. I was trying to do some stuff with nlp last year. Are you using the [spacy](https://spacy.io) library? If you aren't, I'd really recommend you check it out because it's well documented and super efficient.

**Comment by VladimirMikulic** [comment]
I am fascinated by a Leaflet.DistortableImage project, making maps out of pictures is so cool.
Currently working and exploring it :smile:

**Comment by shubhankarsharma00** [comment]
Recently I have been helping high schoolers learn rails as part of my work
as a GCI mentor also I am trying to build a gesture recognition system.

**Comment by nstjean** [comment]
I love seeing the people from GCI learning and playing with the different repos!

This week I am working on getting the map at /post/ to set a default location [#6946](https://github.com/publiclab/plots2/issues/6946) and when that's working I'm going to clean up the styling a little.

I also have two bugs I'm trying to fix: [#6904](https://github.com/publiclab/plots2/issues/6904) [#214](https://github.com/publiclab/leaflet-blurred-location/issues/214)

I have definitely had some struggles! I'm still learning about how testing works, and some of these tasks start in plots2 but depend on leaflet-blurred-location and PublicLab.Editor so I've had to become familiar with how those work and tracing javascript calls. Some days I write very little code, it's a lot of trying and failing and testing.

**Comment by crisner** [comment]
This week I am working on an embed feature for the LEL demo page [#252](https://github.com/publiclab/leaflet-environmental-layers/issues/252). I am also planning on getting started on testing.

I've been struggling with URL hashes on my tasks. 😅 You think you got them but then you try it another way you are back to struggling again, with other issues that crop up from it. The thing is each time I struggle and I manage to overcome it I learn something. I am glad I am learning things, I just need to remind myself to take it easy(because I tend to obsess and then stress out). I know for sure the next session of my struggles will begin when I start UI testing which I am not familiar with. 😅 Here's to overcoming struggles and learning! 🥂

**Comment by jywarren** [comment]
Love this theme!

> This is one of the themes for the weeks on Outreachy and I always love it because with coding sometimes it can be frustrating. It helps to know that everyone goes through and its part of the process getting amazing work out in the world 😄.

I've long put off learning about Promises in JavaScript and still don't quite grasp how it works - it just bends my mind a bit! And my mind was already bent from learning about asynchronous JavaScript in the first place 😆 So that's my struggle! I was able to use it with the `fetch()` method in JS this past week to solve a problem and write this README example: 

https://github.com/publiclab/image-sequencer-app#usage

Thanks all for doing a great job this past week. It's an exciting time for our community and let's help each other out any way we can! 🙌 🎉

**Comment by jywarren** [comment]
@crisner hang in there with the hashes! You'll get it! Here's an example of a set of utility functions we've used to manage hashes in `image-sequencer`, which uses them in a pretty advanced way: https://github.com/publiclab/image-sequencer/blob/main/examples/lib/urlHash.js

They're weird! But powerful!

@nstjean thanks for working through those complex bugs and tracking them down! You've already done some great system testing. This'll help @crisner too when we try writing tests for... URL hashes, for example! 

One approach is to try to thoroughly understand just one step in the process, and then write a test for it to "protect" it. Then build on that. This lets you kind of take one variable off the table as you narrow in on a bug, and makes sure you are empirically demonstrating what your assumptions are, through tests. Tests can be tough, but they're really your friends 😄 when they can help you work iteratively and step-by-step!

**Comment by nstjean** [comment]
@jywarren That makes sense! I do like the idea behind tests... the practice of them is a little hard. :laughing:

**Comment by SidharthBansal** [comment]
I spent many months learning tests. When you write them for first time they
are your enemies. But eventually after some time, they will help you a lot.
They will be your friends after you are used to them.
Happy learning
:-)

**Comment by jywarren** [comment]
@VladimirMikulic if you're really interested in Leaflet.DistortableImage, you may like this issue in Leaflet Environmental Layers, which is designed to better feature LDI images from MapKnitter! https://github.com/publiclab/leaflet-environmental-layers/issues/153

We could craft a GCI task around it, maybe...?

**Comment by VladimirMikulic** [comment]
@jywarren It would be my pleasure to do it. You could create a GCI task, so I can start working on it.

**Comment by cesswairimu** [comment]
Nice to read all the stories...Thanks everyone for sharing...I am doing some work on the PL Editor and it involves some javascript and I always struggle with javascript but it is also making me learn so that s good :).
Anyone interested in opening next week's check-in?

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/leaflet-blurred-location/issues/227. Thanks all
