### ISSUE TITLE
Bug prevents from creating map on mapknitter website 

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/mapknitter#1159]
### What happened just before the problem occurred
I tried to create a map anonymously and got the mapknitter error page.
I tried replicating the process on my local server with a logged in account and got the following error:
![bug-mapknitter](https://user-images.githubusercontent.com/52892257/70943213-a0795480-2050-11ea-9424-84f88d1e873b.png)

### Relevant URLs
https://mapknitter.org/maps/new

### Browser, version, and operating system
I was using Firefox on a Ubuntu browser.

Does anyone know why this might be happening @jywarren?
I hope we can figure out why this is happening :smile:

**Comment by cesswairimu** [comment]
Hey @Uzay-G, where did u get this error locally or mapknitter.org?

**Comment by Uzay-G** [comment]
The screenshot I took was a local error, but when I tried on the website I also got the website's error page.

**Comment by cesswairimu** [comment]
thanks, looking into this

**Comment by cesswairimu** [comment]
@Uzay-G , I just trying creating a map anonymous locally and when logged in...I can't see the error. I also tried on the website it is taking forever to load..., maybe it has been fixed could you try to pull the changes and let me know if the error still persists locally? Thanks

**Comment by Uzay-G** [comment]
Yeah for me too the website is taking a long time to load. I will see locally when I finish my homework

**Comment by Uzay-G** [comment]
Uh I tried by pulling the repo and got this error:

![bug-map](https://user-images.githubusercontent.com/52892257/71123737-99cf1680-21e3-11ea-9283-7d4a525cd298.png)

**Comment by cesswairimu** [comment]
There is a new migration... Try running "rake db:migrate" then retry
