### ISSUE TITLE
upload error on clean local install

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#117]
Hmm

    Completed 500 Internal Server Error in 517.8ms
    TypeError (no implicit conversion of nil into String):
      app/controllers/images_controller.rb:68:in `+'
      app/controllers/images_controller.rb:68:in `url_upload_not_found'

**Comment by btbonval** [comment]
https://github.com/publiclab/mapknitter/blob/master/app/controllers/images_controller.rb#L68
`redirect_to "/map/edit/"+params[:id]`

Looks like `params[:id]` is `nil`. If `:id` was `nil`, you'd probably have a different error.

That's about all I can do with this.

**Comment by jywarren** [comment]
Indeed; on my netbook (where I develop) i'm not seeing this, but on a clean VM install, I am. Odd. Could have to do with a missing dependency.

**Comment by jywarren** [comment]
OK - it's not clearly switching between s3 and local file storage. I'm going to try adjusting the reference to `config/config.yml`

**Comment by jywarren** [comment]
http://stackoverflow.com/questions/2562249/how-can-i-set-paperclips-storage-mechanism-based-on-the-current-rails-environme
