### ISSUE TITLE
Homepage modal buttons not scaled

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/mapknitter#1174]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### :fire: Problem

![Screenshot_20191225_171442](https://user-images.githubusercontent.com/35997844/71448295-73a4fb80-273a-11ea-84be-331ed93d3924.png)

![Screenshot_20191225_171519](https://user-images.githubusercontent.com/35997844/71448296-77388280-273a-11ea-972b-1732a7e3cfa0.png)

On mobile phone and tablets, buttons are not of the same height.
It results in bad UI/UX and it should be fixed.

### 🚩 Solution

![Screenshot_20191225_171912](https://user-images.githubusercontent.com/35997844/71448308-b961c400-273a-11ea-9283-da0d1018c97d.png)

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Open** the file ./mapknitter/app/views/front_ui/index.erb

- Line 55 -> add inline styles to paragraph
```html
<p style="display:flex;justify-content:space-around;"><i style="color:#aaa;">A Community Atlas hosted by <a href="https://publiclab.org">PublicLab</a></i></p>
```

- Line 64 -> add an inline style to the anchor tag
```html
<a class="btn btn-primary btn-lg" style="display:flex;align-items:center;justify-content:center;" href="" data-toggle="collapse" data-target="#anonymous-map">
```

- Line 66 -> add margin-left to inline styles
```html
<i class="fa fa-plus fa-fw" style="font-size:12px;color:white;margin-left:2%;"></i>
```

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by Johongirrr** [comment]
Hey @IshaGupta18 can I get this done?

**Comment by VladimirMikulic** [comment]
@Johongirrr of course, we would really appreciate your help with this issue.

**Comment by Johongirr** [comment]
@VladimirMikulic  Thank u I am on

**Comment by Johongirr** [comment]
@VladimirMikulic  problem was with height media queries need to be set up for this problem.

@media(min-width: 576px) and (max-width: 1359px){
   p  a.btn {
        height: 80px;
    }
}

**Comment by VladimirMikulic** [comment]
@Johongirr I would like you to follow the solution step by step. Your solution with media queries has it's flaws.

`p a.btn` would apply this style to all paragraphs that have anchors with btn class. 

That's why I've done inline stylings, it is unique on the whole site, but it doesn't make sense to assign it an ID.

If there is anything that you didn't understand, feel free to ask :)

**Comment by Johongirr** [comment]
Hi @VladimirMikulic  sorry, I did not look at the code you provided. i looked at picture and figured that problem is with height either coz modal buttons were not given same height or elements nested inside them had

**Comment by VladimirMikulic** [comment]
@Johongirr it's alright, no need to apologise!
It's the important thing for newcomers to understand why we do something instead of what we do.

I would love a PR from you that resolves this :rocket:

**Comment by Johongirr** [comment]
@VladimirMikulic  I made my PR and now wating for review and approval of it.

**Comment by VladimirMikulic** [comment]
@Johongirr great work, I've approved the task, but please specify this issue number `#1174` in your PR  description. Thanks.

**Comment by shubhangikori** [comment]
Can I work on it if this first-timers-only issue is still open?

**Comment by VladimirMikulic** [comment]
@shubhangikori the issue is still present, feel free to take over. Let me know if you need any help. Thanks.

**Comment by IC1101Virgo** [comment]
May I work on this? 😃

**Comment by pydevsg** [comment]
Go ahead @IC1101Virgo :)

**Comment by IC1101Virgo** [comment]
Thanks ! :)

**Comment by yuktea** [comment]
Hello @VladimirMikulic, I'm starting my OSS Journey and am a first timer. Can I please take this issue up?

**Comment by VladimirMikulic** [comment]
Hi @yuktea. Think this was resolved in #1176, but if not feel free to submit a new PR.

**Comment by sakshi-2412** [comment]
Hey @VladimirMikulic Can I work on this issue?
I tried to follow the steps provided but this is what the buttons looked like -

![Screenshot from 2022-03-05 20-21-57](https://user-images.githubusercontent.com/85152262/156888796-518529d3-112c-4cab-8f27-dced190d290d.png)

Also noting that the codes are not at the specified lines (as this is a very old issue, maybe other code has been added/deleted)
:thinking: 

I would love to work on this issue :smile:

**Comment by VladimirMikulic** [comment]
@sakshi-2412 feel free to take over :)

**Comment by sakshi-2412** [comment]
@VladimirMikulic I have opened a PR, can you please check it once? Thanks ✨

**Comment by chepyego** [comment]
is this issue still on? am outreachy applicant 2022 and I would like to work on it

**Comment by PeculiarE** [comment]
I believe this has been resolved @chepyego

**Comment by chepyego** [comment]
> I believe this has been resolved @chepyego

yeah I think so
