### ISSUE TITLE
Searching with less than 3 characters results in error

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/mapknitter#1177]
### What happened just before the problem occurred
Type any string where the number characters is less than 3 on the [mapknitter website] (https://mapknitter.org) and you will get the production error page. There is more detail if you test in a development environment:

![map-search-error](https://user-images.githubusercontent.com/52892257/71528023-2a8dac80-28de-11ea-9a43-ea5cce3e5edd.png)

The route responsible for this is in "maps#search". It returns the relevant search results if the query is more than 2 strings long, otherwise it returns featured maps. The latter is the problem. The code for this route look like this:
https://github.com/publiclab/mapknitter/blob/f0e8dbd896e2b13318ec8656fc1d49c407832cce/app/controllers/maps_controller.rb#L177-L198

The bug is because the `@maps` contains zero maps when the query is too small because there is a problem with the way the maps are collected through `Map.featured` (line 185). There is then a bug when the `@maps` variable is called inside the views although it contains nothing.
 
I don't know why the `@maps` variable doesn't gather any maps but have been trying to debug through tests and noticed that simply and maybe naively commenting out this line fixed the problem:
https://github.com/publiclab/mapknitter/blob/f0e8dbd896e2b13318ec8656fc1d49c407832cce/app/controllers/maps_controller.rb#L187.
The featured maps then render like this:
![success-search-maps](https://user-images.githubusercontent.com/52892257/71528272-5fe6ca00-28df-11ea-8e79-edad72d79a1e.png)

Now I obviously understand that this is not an ideal solution because I don't understand why change works although I will look at the codebase to figure it out. I'd love your help in deciphering this problem!

**Comment by cesswairimu** [comment]
NIce catch @Uzay-G, looking into this.

**Comment by cesswairimu** [comment]
@Uzay-G, locally I get this  page 
![Screenshot from 2020-01-03 00-39-29](https://user-images.githubusercontent.com/17081074/71694941-c0837480-2dc1-11ea-9850-4f25cd908ba2.png)
which is fine

**Comment by cesswairimu** [comment]
Also on stable I get the same http://mapknitter-stable.laboratoriopublico.org/search?q=as which is the latest code on main right now...Maybe we haven't deployed in a while..but it would be nice to checkout what error sentry is giving

**Comment by cesswairimu** [comment]
Which query gave you this? https://user-images.githubusercontent.com/52892257/71528023-2a8dac80-28de-11ea-9a43-ea5cce3e5edd.png

**Comment by Uzay-G** [comment]
Any query under 3 characters does that for me. Should I close the issue?

**Comment by cesswairimu** [comment]
nope don't close it yet, lets investigate further

**Comment by Uzay-G** [comment]
Yeah for me it only works if I remove the line `.except(:styles, :email)`

**Comment by sashadev-sky** [comment]
Just looked into this. Confirming mapknitter.org production site gives error page on queries less than 3. Thanks @Uzay-G for all the debugging! 

For now I will label this accordingly and come back when I have time to help investigate :)

**Comment by jywarren** [comment]
I'm not caught up on this issue, but just noting that sometimes queries <3
are skipped because they are hard on the database (lots of matches)... so
that could be related?

**Comment by Uzay-G** [comment]
No because when the query is less than 3 characters, instead of running the search, it is supposed to return to the featured maps but for some reason they are nil on Mapknitter production. It might be fine as it apparently works on Mapknitter stable. It does not work for me locally though.

**Comment by sashadev-sky** [comment]
@jywarren labeled this priority and help wanted to give it some attention because its so old. Shouldn't be tough to fix

**Comment by sashadev-sky** [comment]
@jywarren labeled this priority and help wanted to give it some attention because its so old. Shouldn't be tough to fix

**Comment by Uzay-G** [comment]
@jywarren there is already a built-in explanation that is supposed to display when the query is too small. But an error in the code is preventing it from working correctly.

The bug is because the `@maps` class variable contains zero maps when the query is too small because there is a problem with the way the maps are collected when the query is too small:
https://github.com/publiclab/mapknitter/blob/f0e8dbd896e2b13318ec8656fc1d49c407832cce/app/controllers/maps_controller.rb#L185-L187
For some reason this variable is empty and so when it is called inside the view there is an error.

I think this is the problem.

**Comment by cesswairimu** [comment]
Currently on prod, the search button is not clickable if the chars are less than 3. Which I believe is okay. Closing this. Thanks everyone
