### ISSUE TITLE
Consistent styling across PL projects

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/mapknitter#1178]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### :fire: Problem
PublicLab's naviagtion search bar

![pl](https://user-images.githubusercontent.com/35997844/71587468-11733e80-2b1e-11ea-9cc1-571e0cd8ca3a.png)

Mapknitter's navigation search bar

![Screenshot_20191230_155931](https://user-images.githubusercontent.com/35997844/71587477-1e902d80-2b1e-11ea-8474-0f12ac864a25.png)

Since PublicLab uses the same colour palette and stylings across pages, it would make sense to have the same search bar in the navigation.

### 🚩 Solution

![mapkn](https://user-images.githubusercontent.com/35997844/71587545-67e07d00-2b1e-11ea-8ecd-0cb138b49e22.png)

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Open** the file mapknitter/app/views/layouts/_header.html.erb

- Line 13, remove inline styling from the button
```html
 <button class="btn btn-light" type="submit" style="margin-left: 2px;"><i class="fa fa-search"></i></button> 
```

- Line 11, remove `bg-light` class from the input element
```html
<input class="form-control bg-light" id="search-input" type="text" name='q' placeholder="Search maps" value='<%= params[:id] if params[:action] == "search" %>'>
```

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by greyGroot** [comment]
i claim

**Comment by VladimirMikulic** [comment]
@greyGroot it's all yours :)

**Comment by greyGroot** [comment]
just have created pr #1179 review please

**Comment by arghac14** [comment]
Is it still open to work on? @VladimirMikulic

**Comment by VladimirMikulic** [comment]
@arghac14 it has already been done :)
You can check out other FTOs.
