### ISSUE TITLE
Add message if there are no results for search query

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/mapknitter#1182]
Currently, when a user searches a query without results the following page is displayed:
![no-results-mapknitter](https://user-images.githubusercontent.com/52892257/71646154-8c398680-2ce3-11ea-8e6b-1fa2d9d82c86.png)

I think it would be nice to add a message with maybe an illustration when there are no results for a specific query. If you think it's a good idea, I'd love to work on it!
What do you think @publiclab/mapknitter-reviewers?

**Comment by cesswairimu** [comment]
Hi @Uzay-G, I think its a great idea...maybe we could also  tweak the text when are no results to read  "*No results found for ---*   maybe also add links to "featured mappers" and  "featured maps" something like "See our featured mappers and  featured maps". I would like to hear your thoughts on this and other ideas you have to improve this. You are really doing an amazing job, glad to have you here :heart: . Thanks

**Comment by Uzay-G** [comment]
Thanks! I will edit the code and see that it looks like. I will send a screenshot :smile:

**Comment by Uzay-G** [comment]
Hey, could you also check out #1177. I think it's a pretty important error. Thanks :+1:

**Comment by Uzay-G** [comment]
Something like this:
![search-logic](https://user-images.githubusercontent.com/52892257/71664637-ebd27900-2d59-11ea-9475-46dd7295cc23.png)

**Comment by cesswairimu** [comment]
Oh sorry...I meant a text that links to that page...mmmh actually that looks interesting :thinking: but I am thinking someone might be frustrated by getting results he didn't ask for

**Comment by cesswairimu** [comment]
LIke the way plots2 gives the "all content" and "authors" link if no results https://publiclab.org/search?q=tygdyus but ni our case we could start with a mere text that is a link..What do you think?

**Comment by Uzay-G** [comment]
Yeah alright... could you check out #1177. Thanks

**Comment by Uzay-G** [comment]
I did it that way because that's how it's handled when the query is less than 3 characters. So you think it's better to just link the buttons and tell the user that there were no results?

**Comment by sakshi-2412** [comment]
hello @Uzay-G @cesswairimu  can I work on this issue?
Also, do we have a dedicated page for featured maps/mappers?.. I could see them in https://mapknitter.org/gallery which is linked in the home page as "All Maps"
Maybe here too we can provide a link to the gallery page with the error text if there are no results?

**Comment by Uzay-G** [comment]
Definitely! Go ahead :)

**Comment by sakshi-2412** [comment]
Okay thanks!
I tried some changes...How does this look?

![Screenshot from 2022-03-10 00-25-23](https://user-images.githubusercontent.com/85152262/157649972-d62b3472-04d1-4263-9add-bdaf6eb443fa.png)

**Comment by cesswairimu** [comment]
Hi all,
this is looking good @sakshi-2412 :100:  yeah I agree lets provide the link to the gallery. Thanks for working on this

**Comment by sakshi-2412** [comment]
okay thanks.. I'll make a PR soon :sparkles:
