### ISSUE TITLE
Login Page Unresponsive

### ISSUE THREAD

**Issue by pythongiant** [publiclab/mapknitter#1183]
### What happened just before the problem occurred
Here's The Login Page:

![image](https://user-images.githubusercontent.com/13624560/71654151-2508ea00-2d56-11ea-924b-885f0abea0bd.png)

As you can see its pretty unresponsive, It would be better if it was center aligned with some padding

**Comment by gr455** [comment]
Hey, I would like to work on this issue

**Comment by gr455** [comment]
However, I can't find a way to reach that page apart from adding a '/login' onto the url
