### ISSUE TITLE
Remove horizontal scrollbar

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/mapknitter#1187]
The scrollbar at the bottom looks ugly and we don't need it. Lets remove it

![Screenshot from 2020-01-06 10-22-19](https://user-images.githubusercontent.com/17081074/71802403-a3270280-306e-11ea-9c97-1245ea186153.png)

**Comment by cesswairimu** [comment]
@SidharthBansal do we need more issues for gci? I could reformat this to a gci issue if we need it. Thanks

**Comment by SidharthBansal** [comment]
Go ahead!

**Comment by keshavsethi** [comment]
Can i try this issue??

**Comment by SidharthBansal** [comment]
Sure.

**Comment by keshavsethi** [comment]
Is it ok if i just make overflow-x hidden

**Comment by cesswairimu** [comment]
@keshavsethi are you participating in gci? If so let me know so that I can add this. Thanks

**Comment by keshavsethi** [comment]
nope 
so,should i continue on this?

**Comment by cesswairimu** [comment]
Yeah sure...please do. Thanks

**Comment by keshavsethi** [comment]
@cesswairimu @SidharthBansal PR is made, please review this.

**Comment by SidharthBansal** [comment]
Awesome thanks
