### ISSUE TITLE
"Cancel export" button squished with progress bar

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/mapknitter#1193]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### :fire: Problem 

![Screenshot_20200111_015342](https://user-images.githubusercontent.com/35997844/72195976-8cd5c980-3415-11ea-859a-3cfb346b060b.png)

When the progress bar is displayed on the page it is always squished with the button.
We should fix it.

### 🚩 Goal

![Screenshot_20200111_015319](https://user-images.githubusercontent.com/35997844/72195981-919a7d80-3415-11ea-9ebc-c8996586bb02.png)

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Open** the file app/views/maps/_sidebar_exports.html.erb
- Line 31, add `mb-3` to the div that has class `progress`
```html
<div class="progress mb-3"<% unless @map.exporting? %> style="display:none;"<% end %>>
```

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by developer22-university** [comment]
I am working on this @VladimirMikulic

**Comment by developer22-university** [comment]
@VladimirMikulic  please check

**Comment by developer22-university** [comment]
also , @VladimirMikulic  i would like to work on publiclab.editor  could you please suggest some issues for improvement.

**Comment by VladimirMikulic** [comment]
Hi @developer22-university. It does work! Could you submit a PR for it so I can remove it?
Thanks.

**Comment by VladimirMikulic** [comment]
I am glad that you want to work with PublicLab editor. It won't be easy, it has quite a few issues.
As a starting point, you could try https://github.com/publiclab/PublicLab.Editor/issues/339.
You will solve an important issue and also familiarize yourself with the codebase.

**Comment by developer22-university** [comment]
@VladimirMikulic  do you think there should be option for underline the important text, or highlighting the text written in public lab editor. for  which we should update the toolbar.

**Comment by developer22-university** [comment]
i made the PR.

**Comment by VladimirMikulic** [comment]
@developer22-university it's markdown, I think it's already possible to underline text.
Woofmark is the engine that drives this editor so if you would like to add a toolbar button, that's how you would do it.

> I made the PR

Could you reference this issue in it so I can review it?

**Comment by developer22-university** [comment]
@VladimirMikulic  actually i was familiarising my self with the code base of the editor and found there is lot of things for improvement. as i am not able to upload photos. also the kind of photos required is not opening also. @VladimirMikulic  happy to know you worked with it

**Comment by VladimirMikulic** [comment]
Every time you fix an issue, you should reference it in your PR so reviewers can easily find it.

**Comment by VladimirMikulic** [comment]
@developer22-university actually you can't upload any images. Upload does work but on publiclab.org/post. It sends a post request to their server.

**Comment by VladimirMikulic** [comment]
You would need to set up something similar to get it running locally.

**Comment by developer22-university** [comment]
Hi , I did in the description please check

**Comment by developer22-university** [comment]
@VladimirMikulic  check please

**Comment by VladimirMikulic** [comment]
Hi @developer22-university. Did you see my comments in your PR?
If not please read them.

**Comment by developer22-university** [comment]
you asked to refrence the issue could you please guide if i m not doing correctly, @VladimirMikulic

**Comment by VladimirMikulic** [comment]
@developer22-university no worries, let me guide you.
As I can see you've pushed the branch `developer22-university-patch-1`.
You've probably done something like [this](https://github.com/msu-anthropology/daea-fs16/wiki/Create-and-Complete-a-Pull-Request-on-Your-Own-Repo).


1. What you need to do is to select `base fork` to be this mapknitter repo and set as `base` the master branch.

2. Set as `head-fork` your repository and set `compare` to be your branch where you've implemented the changes. In your case, it's `developer22-university-patch-1`.

In the PR description, you reference this issue like `Resolves #1193` or `Fixes 1193`...

In the end, you click "Create pull request".

I hope it helps and thank you very much for your interest and eagerness to learn. :rocket:

**Comment by developer22-university** [comment]
THANKS @VladimirMikulic

**Comment by developer22-university** [comment]
@VladimirMikulic  i did what you said


![Screenshot (61)](https://user-images.githubusercontent.com/51835554/72280019-5ee2c600-365d-11ea-9852-3e34fe8c9b75.png)

**Comment by developer22-university** [comment]
what should i do now

**Comment by VladimirMikulic** [comment]
Awesome @developer22-university. Now create that PR :rocket:

**Comment by VladimirMikulic** [comment]
Provide a title and the description.

**Comment by VladimirMikulic** [comment]
The title can be "FIX: Squished cancel export button with a progress bar"
In the description, you can just mention Fixes (number of this issue -> #1193)

**Comment by developer22-university** [comment]
thanks  for being patient and  helpful @VladimirMikulic .more issues for me till i set up some repo in my system

**Comment by VladimirMikulic** [comment]
That's it!!!!! I am proud of you @developer22-university. Very nice job :rocket: :rocket: :rocket:
