### ISSUE TITLE
CTA buttons squished on multiple lines

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/mapknitter#1194]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### :fire: Problem

![Screenshot_20200111_022700](https://user-images.githubusercontent.com/35997844/72196703-66fef380-341a-11ea-8d16-718e879f5244.png)

As you can see from the image above, when we have multiple CTA button they are squished with the row above.

### 🚩 Goal

![Screenshot_20200111_022912](https://user-images.githubusercontent.com/35997844/72196704-6b2b1100-341a-11ea-89a4-da861b4c7ca9.png)

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Open** the file app/views/layouts/knitter2.html.erb
- Line 137, add `cta-buttons` class to the `p` tag
```html 
<p class="cta-buttons">
```

- Line 146, after the before `.footer` rule in the app/assets/stylesheets/style.scss file, add this code:
```css
.cta-buttons {
  .btn {
    margin-top: 0.25rem;
  }
}
```

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by keshavsethi** [comment]
I want to claim this.

**Comment by VladimirMikulic** [comment]
@keshav234156 go for it :rocket:

**Comment by VladimirMikulic** [comment]
That was fast :)
