### ISSUE TITLE
Weekly community check in #44 - Learning with Public Lab

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/mapknitter#1199]
Hi everybody! :clap: 

We all at Public Lab :balloon: - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas :bulb , your learning goals :ballot_box_with_check:.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100:

New contributors, please comment down below and introduce yourself! We welcome you all to Publiclab and are here to help if you encounter any issues! :+1:
 
# Learning with Publiclab
This week share something you learned or a new experience you gained through contributing to Publiclab. It could be a new tool or topic you heard about that interested you. Or for example if someone introduced you to a new way to view an idea or a concept. Publiclab is a community built to share knowledge and help others learn about a variety of environmental topics and we would love to hear about what **you** are learning as you make this platform even better!

# Next check-in
If you'd like to open the next check-in, please comment down below :+1:! We'd love to help you :smile:

**Thanks to all of you for making Publiclab amazing!!** :+1: :balloon:

**Comment by Uzay-G** [comment]
@dmahajan980, @bryceparkman, @nicoleiocana, @0dim, @nstjean, @AnshitaVishwa, @tsparksh, @sharmamansi, @polygonart6777, @anthony-zhou, @cesswairimu, @chen-robert, @leesgrey, @smarty1palak, @VladimirMikulic, @nfarve, @jywarren, @chanchalsaini, @johnaceto, @gireeshcse, @lisaschumann, @shashwataggarwal, @yeo-yeo, @gabrielrumiranda, @mikepetridisz, @GarvinH, @Ugtan, @sap143, @arjunshekhawat5, @sagarpreet-chadha, @ami-friedman, @gautamig54, @shubhankarsharma00, @rebecarancan, @swathi-0901, @Rishabh570 @sashadev-sky @IshaGupta18 @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo @shipcy

**Comment by Uzay-G** [comment]
@Rishabh570 @sashadev-sky @IshaGupta18 @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo @shipcy @developer22-university @keshavsethi @emilyashley @smarty1palak @daemon1024

**Comment by SidharthBansal** [comment]
https://github.com/publiclab/plots2/issues/6808#issuecomment-573388883

**Comment by SidharthBansal** [comment]
Kindly read https://github.com/publiclab/plots2/issues/6808#issuecomment-573388883

**Comment by SidharthBansal** [comment]
@Uzay-G you forget to tell about your learnings

**Comment by cesswairimu** [comment]
Great topic @Uzay-G and thanks for opening this :tada: :tada: 
I am working on a project that needs integration with a couple of js libraries and js is not my strongest language..I am learning a lot of js and whenever something works I get so excited. 
Great week ahead everyone

**Comment by Uzay-G** [comment]
> @Uzay-G you forget to tell about your learnings

 Thanks! I will :+1: 
I am honestly learning so much through GCI and Publiclab. 
I am currently researching and exploring how I could build a natural language processing program that would help detect spam in Publiclab with the help of @skilfullycurled. I am also learning a lot about all the cool, not so obvious things you can do with Rails (system testing) andsetting up complex login systems across websites with @SidharthBansal.

Are you learning about any new things @SidharthBansal?

**Comment by emilyashley** [comment]
Oh yes good topic. I've never built or worked on anything with Ruby/Rails before so it looks like I'll be learning that very soon with Public Lab. I've worked with Elixir/Pheonix, Python/Django, and JavaScript/Angular in the past so fingers crossed that I'll pick it up quickly. 

I'm trusting that I can come to you all with any questions and putting my learning cap on! :)

**Comment by jywarren** [comment]
Hi all! Thanks for opening this, @Uzay-G !!

My learning is that you can make carbon quantum dots by microwaving polyethelene glycol (used in vaping liquid) and saccharide (sugar?), and that these, when filtered or treated with coatings, can be used to detect different chemicals... i'm really out of my depth here, but just love it when some really wildly experimental technique just ends up using a microwave and some sugar:

https://en.wikipedia.org/wiki/Carbon_quantum_dots

![image](https://user-images.githubusercontent.com/24359/72557527-ef442500-386e-11ea-9fd7-dd5cd586a61d.png)

On the coding side, I learned from @emilyashley that I should try to switch to using the GitHub notifications page (https://github.com/notifications) instead of my inbox, to respond to issues. 😭 😂 

Thanks, all!!!!

**Comment by nstjean** [comment]
Ahh I forgot to respond! This week we've been learning a lot about testing in Jasmine and how it works... I have a feeling I'm going to learn a lot more about the subject before I'm done!

I've also been learning more about how the maps systems interact with each other, from LEL to LBL and plots2. It's interesting to see things done a few different ways!

**Comment by jywarren** [comment]
Hi all, i also wanted to point folks to this great convo about testing, it really made me feel good! ❤️ 🎉 😄 

https://github.com/publiclab/plots2/pull/7181#issuecomment-573276544

cc @Uzay-G @shipcy @skilfullycurled

**Comment by Uzay-G** [comment]
> Hi all, i also wanted to point folks to this great convo about testing, it really made me feel good! heart tada smile
> 
> [publiclab/plots2#7181 (comment)](https://github.com/publiclab/plots2/pull/7181#issuecomment-573276544)
> 
> cc @Uzay-G @shipcy @skilfullycurled

I'm happy it did :+1:! That was a really interesting conversation

**Comment by cesswairimu** [comment]
Thanks everyone for sharing...interesting things are happening :rocket: . Moved to https://github.com/publiclab/image-sequencer/issues/1540 . Thank you all
