### ISSUE TITLE
better error when adding tags while not logged in

### ISSUE THREAD

**Issue by eustatic** [publiclab/mapknitter#121]
http://mapknitter.org/maps/bayou-plaquemines

I suppose this is how it's supposed to be, that, when i'm not logged in, I can't add tags to a map. 

but instead of sending me to an error page, perhaps not having the tag field unless one is logged in?

a pop up reminding you to log in if you try to otherwise add a tag?

**Comment by jywarren** [comment]
Great - can you change the title to "better error when adding tags while
not logged in"? Thanks!
