### ISSUE TITLE
Move styling from front_ui to stylesheets

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/mapknitter#1221]
In the spirit of following rails way lets move the styling on the front_ui/index to stylesheets

To do
--------
Create a file named `front_ui.scss` under `app/assets/stylesheets`
Move this block of code to the file
https://github.com/publiclab/mapknitter/blob/main/app/views/front_ui/index.html.erb#L7-L48

Make sure you send a screenshot to make sure we did not break anything

**Comment by cesswairimu** [comment]
@katungi here you go

**Comment by katungi** [comment]
@cesswairimu i will work on it asap.
