### ISSUE TITLE
corner handles not moving with image in Chrome/Windows 7

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#125]
The circles that track the outside of each image were not tracking with the image as it moved. I was working on windows 7 with google chrome.

**Comment by jywarren** [comment]
I wasn't able to reproduce this in chromium or chrome in Ubuntu; is this always the case, or only sometimes? An on all maps or just some?

**Comment by steviepubliclab** [comment]
It was on two maps, two separate computers.

**Comment by jywarren** [comment]
so, consistently for all maps seems likely.

We may have to open an issue in
https://github.com/publiclab/Leaflet.DistortableImage/issues since that's
where we track bugs for that feature.

**Comment by jywarren** [comment]
Hi, Stevie - can you list what version of Chrome you were using on the two computers? Do you think it's possible that it was an older version?

**Comment by eustatic** [comment]
confirm this bug 
![mapknitter bug](https://cloud.githubusercontent.com/assets/3277298/6380628/a5194030-bd00-11e4-9825-ba518efa8bea.png)

**Comment by jywarren** [comment]
Thanks excellent. Scott also mentioned it was windows 7 and chrome Version
40.0.2214.115 m

**Comment by jywarren** [comment]
Great -- filed over here: https://github.com/publiclab/Leaflet.DistortableImage/issues/86 thanks!!
