### ISSUE TITLE
Maps should initialize showing all images in bounds

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#1280]
We used to have this behavior, where we just collect bounds from all images and then use Leaflet's fitBounds, i think? 

https://leafletjs.com/reference-1.3.4.html#map-fitbounds

https://leafletjs.com/reference-1.3.4.html#polygon

**Comment by jywarren** [comment]
Indeed:

```js
map.fitBounds(map._imgGroup.getBounds());
```

Let's just start by adding this as a button! https://github.com/publiclab/mapknitter/commit/0c842d624e5c9464e5b9eed2d5ef581fdc2b437b done!

If it works, we should test adding it to the startup sequence here:

https://github.com/publiclab/mapknitter/blob/0c842d624e5c9464e5b9eed2d5ef581fdc2b437b/app/assets/javascripts/mapknitter/Map.js#L121-L137

**Comment by jywarren** [comment]
and on the view page?

**Comment by jywarren** [comment]
This is now live via the button. We could extent to the view page if we like it!

**Comment by jywarren** [comment]
Context - this page is affected so if we set it to the default this should be solved: https://mapknitter.org/maps/stavanger2013/edit

**Comment by emilyashley** [comment]
Coooool, looking at this now. Getting my mapknitter environment setup and running into issues on finding the libxml headers on mojave.
