### ISSUE TITLE
Pagination on per-author gallery listings 

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#1296]
@joyofsoy reports:

> MK: Can’t click to next page when viewing Maps Gallery by Author

> From main page, clicking All Maps then the tab for Authors shows the first page of 20 results. When you click Next or another page number at the bottom, it returns with an error message.

> Clicking next from the first page of results tries to send you to https://mapknitter.org/gallery?mappers=2, which isn’t functioning

I think this is just cross-wired with the main gallery pagination at https://mapknitter.org/gallery !

**Comment by jywarren** [comment]
This is related to https://github.com/publiclab/mapknitter/pull/1268

**Comment by akp2603** [comment]
@cesswairimu Hi is this up for grabs? Would love to look this up.

**Comment by cesswairimu** [comment]
HI @akp2603 just checked, looks like its solved. Closing this. Thanks
