### ISSUE TITLE
TMS URLs returning 404 Not Found

### ISSUE THREAD

**Issue by mstenta** [publiclab/mapknitter#1343]
I work on a project called farmOS (https://farmOS.org), which is for farm management. It has a mapping component, and we have a module that allows users to pull in an aerial imagery map layer from MapKnitter using the TMS URL.

This has worked for a long time, but recently we have been seeing 404s returned from the TMS URLs. Reported here: https://farmos.discourse.group/t/farmos-mapknitter-integration/390/3

Has anything changed on the MapKnitter server side with regard to TMS URLs?

**Comment by deadcalf** [comment]
this is the screenshot of the 404 error and the files is looking for
![image](https://user-images.githubusercontent.com/17411516/85024677-b3dbb880-b176-11ea-91c3-70278b7c325d.png)

**Comment by jywarren** [comment]
Hi, all, i'm so sorry for the slow response. I'm wondering if the TMS route got modified possibly during one of our upgrades? Perhaps @cesswairimu @alaxalves @kaustubh-nair or others may have an idea? 

I'm seeing that the export links for TMS are mostly `.zip` files now, and there may be an error even there: 

* https://mapknitter.org/maps/placa-salvador-segui-barcelona
* https://mapknitter.org/maps/jack-and-annie
* https://mapknitter.org/maps/frogtown-irene2
* Older maps with old-style TMS exports: https://mapknitter.org/gallery?page=25

However, that may be its own error. 

Going just to https://mapknitter.org/tms/frogtown-irene2 for example shows the notes for the TMS endpoint. 

For FarmOS integration, I'm not sure if we are producing TMS in the same way in our Cloud Exporter. 

https://github.com/publiclab/mapknitter-exporter-sinatra#statusjson-format shows the new export product listing. I think it may still be possible to point at a TMS for a new cloud export in Google Cloud storage, but for the example map in the README, for example, the export is at https://mapknitter-exports-warps.storage.googleapis.com/1557156175/1557156175.jpg -- and there is no matching TMS folder. 

And digging deeper, it looks like TMS is no longer a format we are saving upon running an export:

https://github.com/publiclab/mapknitter-exporter-sinatra/blob/a218fa4a70c0ccb2be7655f7d1b8fce0f1bd8154/lib/export.rb#L54-L68

Although, we could revive the TMS export service, with input from @ebarry. It would take some additional Google Storage to do this, however. 

Unfortunately, FarmOS uses OpenLayers, while MapKnitter is primarily based on Leaflet, so directly including the dynamic layers as in https://github.com/publiclab/Leaflet.DistortableImage/ doesn't seem like an easy route forward. 

It looks like the map you're looking at (http://mapknitter.org/maps/rafa) has no exports -- did it before?

**Comment by jywarren** [comment]
Hi - coming back here after a long while, we are about to have TMS working due to https://github.com/publiclab/mapknitter/pull/1548, but are troubleshooting the coordinate systems before it's 100%. But this should re-establish TMS as an export option. Thanks for your patience on this.

**Comment by jywarren** [comment]
Hi, just writing to say that the export system is back up with some refinements, including that hosted TMS is back. 

You'll be able to see TMS export products in this format:

https://mapknitter-exports-warps.storage.googleapis.com/1637088561//tms/

They look like this:

![Screen Shot 2021-11-16 at 1 55 24 PM](https://user-images.githubusercontent.com/24359/142048494-bab72e43-0518-4e96-b8a0-1c83ab35b5f1.png)

The TMS you can use in, for example, QGIS, is:

https://mapknitter-exports-warps.storage.googleapis.com/1637088561/tms/{z}/{x}/{y}.png

Or it might be https://mapknitter-exports-warps.storage.googleapis.com/1637088561/tms/{z}/{x}/{-y}.png

(notice some systems use an inverted y coordinate, so you can show that with `{-y}`)

More on this is now at:

https://publiclab.org/wiki/mapknitter-cloud-exporter#TMS

I think there's a double `//` being added in MapKnitter right now so watch out for that, but I'll fix it today in any case. 

Thanks for bringing this to our attention and glad we could finally resolve it!

**Comment by ebarry** [comment]
This is so awesome! When you get a chance, please also share this in the internal Slack #web so staff can see!

**Comment by jywarren** [comment]
Yep, will do - doing finishing touches and coordinating a Twitter announcement too. Thanks!
