### ISSUE TITLE
"drag and drop" example screenshot may confuse

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#135]
One user seems to have actually dragged the image itself into the uploader: http://mapknitter.org/maps/ucv

![drag-drop-mistake](https://cloud.githubusercontent.com/assets/24359/6494879/fe11f884-c292-11e4-92ef-5d40b28e691f.png)

**Comment by sashadev-sky** [comment]
@jywarren can you explain this issue please? Not sure if its outdated, but the only way to get the example into the uploader is to take a screenshot of it and then upload it after it's already gone. Also based on the current UI I don't find it confusing!

**Comment by jywarren** [comment]
OK, agreed!
