### ISSUE TITLE
image distortion/manipulation breaks when map corner points too close together

### ISSUE THREAD

**Issue by eustatic** [publiclab/mapknitter#136]
windows 7 chrome

![mapknitter bug](https://cloud.githubusercontent.com/assets/3277298/6511825/df60bd6a-c334-11e4-86fb-139d89e653bd.png)

I think this is the same thing Stevie was running into, the corners were showing up way off from anything, the corners weren't in the footprint of the original photo, the stitched photo, or even themselves.  in fact, i only saw two corners showing up

**Comment by jywarren** [comment]
Ah, you mean this map? http://mapknitter.org/maps/golf-course-cut-down-city-park-trees

Pls put in links to pages you see bugs on -- it's tough to track and solve otherwise :-)

Taking a look...

**Comment by jywarren** [comment]
OK, this is likely related to https://github.com/publiclab/Leaflet.DistortableImage/issues/33 as it relates to points being very close to one another. Possibly below the level of precision of JavaScript. 

I fixed this map by tabbing around until i had map focus, then clicking and using arrow keys to find the image control points, then pressing `d` to get to distort mode, then dragging the points away from one another. 

Another question is how it got this way... i haven't tried to reproduce it by dragging points on top of one another.

**Comment by jywarren** [comment]
Indeed one can reproduce by dragging points on top of one another (which already starts to break the distortion) then hitting refresh. I wonder if we could simply not allow points to be placed near one another in the dragging listener? That sounds dumb but also clever ;-)

**Comment by eustatic** [comment]
will do, jeff.  thanks for bearing with my persistent github illiteracy,
and thanks for your swift work

s

On Thu, Mar 5, 2015 at 5:16 PM, Jeffrey Warren <notifications@github.com>
wrote:

> Ah, you mean this map?
> http://mapknitter.org/maps/golf-course-cut-down-city-park-trees
>
> Pls put in links to pages you see bugs on -- it's tough to track and solve
> otherwise :-)
>
> Taking a look...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/publiclab/mapknitter/issues/136#issuecomment-77473581>
> .
>



-- 
Scott Eustis, M.S.
Coastal Wetland Specialist
Gulf Restoration Network

504 237 0323
504-525-1528 x212
scott@healthygulf.org
www.healthygulf.org

541 Julia St, Suite 300
New Orleans, LA, 70130

**Comment by jywarren** [comment]
not a problem! I mention because it can help solve issues a bit faster.

**Comment by jywarren** [comment]
Merging into publiclab/Leaflet.DistortableImage#33
