### ISSUE TITLE
can't download exported map

### ISSUE THREAD

**Issue by eustatic** [publiclab/mapknitter#137]
windows 7 firefox, then chrome

http://mapknitter.org/export/geotiff/city-park-tree-removal-map.tif

re-made map
exported
downloaded GEO Tiff -->  error!
hit "abck" button --> map is borked!
opened in chrome -->  map looks fine
download --> GEO Tiff --> error!

not exported in firefox or chrome

same bug maybe?

sorry to repeat, on deadline, past deadline, trees are falling

**Comment by jywarren** [comment]
Hmm, this happened just before you posted? I just downloaded them fine and will send them to you; can you try one more time?

**Comment by steviepubliclab** [comment]
On this one, the download tab is not pulling up the previous download options. where can I get the JPG?

**Comment by jywarren** [comment]
Hmm, I see it: 

![image](https://cloud.githubusercontent.com/assets/24359/7205017/534144f8-e4f4-11e4-9471-0992b53482f0.png)

**Comment by steviepubliclab** [comment]
again on Chrome Version 41.0.2272.118 (64-bit)
[image: Inline image 2]

I know @patcoyle was having this problem as well

**Comment by jywarren** [comment]
Can you upload an image of what you see? If you just did, it didn't upload (you can't post images to GH by email, it seems).

I'm still seeing, in Chrome and Chromium: 
![image](https://cloud.githubusercontent.com/assets/24359/7208315/e8e33db8-e50d-11e4-8935-b835a10637d8.png)

On http://mapknitter.org/maps/city-park-tree-removal-map

@patcoyle if you're having the same issue, can you please confirm with a screenshot?

**Comment by steviepubliclab** [comment]
Sure: 
![download](https://cloud.githubusercontent.com/assets/7490478/7210781/6da7aff0-e51a-11e4-9e2b-0f74d18cc50c.png)

**Comment by jywarren** [comment]
Oh Stevie, that's a different map, not the one referred to above -- its really helpful if you say exactly where you're seeing something or I end up spending time on the wrong problem. 

It looks like the export did not complete properly; this is the same as in issue #164.

**Comment by steviepubliclab** [comment]
There I get what you get.
