### ISSUE TITLE
Link to the forums/mailing list

### ISSUE THREAD

**Issue by Nataliegurl** [publiclab/mapknitter#139]
Is there one anywhere on mapknitter? I wasn't able to find easily.

**Comment by jywarren** [comment]
Mapknitter users are automatically subscribed, so we didn't make as big a
deal about it.  But I guess we could prompt folks to ask questions or seek
help on the list. Where do you think we should put it?

**Comment by Nataliegurl** [comment]
Left sidebar or bottom of the page by the developers link maybe

-- 
Natalie Mayorga





*Kits Initiative ManagerPublic Lab412 NW Couch, Ste. 307Portland, OR 97209*

*T: 010.722.2291*

*F: 504.324.0401*

*Natalie@publiclab.org <Natalie@publiclab.org>*

*www.publiclab.org <http://www.publiclab.org>*


*FB: www.facebook.com/PublicLab <http://www.facebook.com/PublicLab>*

*Twitter: @PublicLab, @natcat5050*
*Instagram: public_lab*

**Comment by ebarry** [comment]
this is a great issue!

--

txt only: +1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by btbonval** [comment]
Since a lot of this is managed at publiclab.org, instead of duplicating the effort on mapknitter, maybe we could forward mapknitter users back to publiclab.org for this purpose?

**Comment by btbonval** [comment]
woops nevermind. Misread this as having a page devoted to forums/list, not just a link.
