### ISSUE TITLE
Double pagination for maps on the author profile

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/mapknitter#1437]
We have two pagination bars displayed here  https://mapknitter.org/profile/warren

 Lets display just one

![Screenshot from 2020-09-21 17-45-00](https://user-images.githubusercontent.com/17081074/93781758-628a0c00-fc32-11ea-9b29-c9692f292077.png)

**Comment by chethanagopinath** [comment]
@cesswairimu Hi, I would love to pick this up.

**Comment by cesswairimu** [comment]
Hi @chethanagopinath, go ahead. Thanks

**Comment by chethanagopinath** [comment]
@cesswairimu Hi, I am unable to assign myself as I am not the owner of the issue, so it would be great if you could assign the issue to me.

**Comment by cesswairimu** [comment]
cool, done

**Comment by chethanagopinath** [comment]
@cesswairimu  Hi, so as per the new rules of Hacktoberfest, contributing to a repo which has topic, '**Hacktoberfest**' or a label as '**hacktoberfest-accepted**' are valid it seems. Since I really want to work on this issue and participate in Hacktoberfest, would you be willing to do either of these? Sorry about the trouble. Thanks!

**Comment by cesswairimu** [comment]
Hey @chethanagopinath, sure thing added the topic. Go ahead

**Comment by chethanagopinath** [comment]
@cesswairimu Thank you! :)

**Comment by chethanagopinath** [comment]
@cesswairimu Could I have more details as to how I can reproduce this issue? I'm sorry if my question is a bit vague, I'm new to this project and open source in general, so any details would be great. Would I need to login as Warren? And how would I get this particular page? If I log in and try to create a map to check for this error, I get another error while saving the map.
![Screen Shot 2020-10-08 at 11 03 41 PM](https://user-images.githubusercontent.com/10332729/95537018-84b5b500-09ba-11eb-8574-f38ed6bcd0b4.png)
Not sure how to continue with it. Thanks again!

**Comment by cesswairimu** [comment]
Hello yeah sure, glad to.
First run `rake db:seed` to get some users. Then you can get logged in locally using this url `/local/harry` then maybe see if you can  get any map data... the url for this should be `/profile/harry` locally

**Comment by cesswairimu** [comment]
if you have some maps on harry's profile, you could edit this line https://github.com/publiclab/mapknitter/blob/main/app/controllers/users_controller.rb#L8 and use `per_page: 1` to see the double pagination. Please feel free to reach out if you have further questions or if this doesn't make sense. Thanks

**Comment by chethanagopinath** [comment]
@cesswairimu Really sorry for the delay, but when I run `rake db:seed` I get, 
`ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '16' for key 'warpables.PRIMARY': INSERT INTO `warpables` (`id`, `image_content_type`, `image_file_name`, `width`, `created_at`, `updated_at`, `map_id`, `history`) VALUES (16, 'image/png', 'demo.png', 500, '2020-10-21 23:37:50', '2020-10-21 23:37:50', 92, 'sit')`

I was wondering if I was missing something here :/

**Comment by cesswairimu** [comment]
that is strange, could you try dropping the db and immediately after running setup you try to seed again

**Comment by chethanagopinath** [comment]
Sure, I will do that now @cesswairimu. Thank you!

**Comment by chethanagopinath** [comment]
@cesswairimu If there are no maps on Harry's profile, is there any other user I could try? (Who isn't the admin)
