### ISSUE TITLE
remove image from sidebar if deleted from image popup toolbar

### ISSUE THREAD

**Issue by cspencer905** [publiclab/mapknitter#146]
on right side panel when trying to delete an image i was redirected to a new page that doesn't exist
when i delete it from the floating editing panel when the image is selected it no longer appears on the map but it is still there

**Comment by jywarren** [comment]
I noticed this; I think it wouldn't be a tough fix but we have a bit of a long list at the moment :-( 

I'm hoping we can recruit more contributors soon; please pass on the word if you know any developers looking to help out on an open source project!

**Comment by mathewlippincott** [comment]
Another case of this is I delete it from the map but it stays in the "images" menu but without the ability to re-place it on the map. 
![screen shot 2015-03-27 at 4 28 13 pm](https://cloud.githubusercontent.com/assets/1203280/6878631/b522d65c-d49e-11e4-9ac6-1754838fb0c0.png)

**Comment by mathewlippincott** [comment]
images no longer appear on the map but all reappear when the map is reloaded
![screen shot 2015-03-27 at 5 22 59 pm](https://cloud.githubusercontent.com/assets/1203280/6878986/fa97eb94-d4a5-11e4-89df-18afbcb0378e.png)

**Comment by jywarren** [comment]
2 issues; we should show an error when you're not logged in and want to delete, and should remove image from sidebar if deleted from image popup toolbar.

**Comment by jywarren** [comment]
This is actually a bit more complex; the 'delete' listener we're using is fired *after* the image is deleted from the client-side Leaflet environment. I just wrote code that "confirms" with a popup, sends a "delete" command to the server, and then removes the image from the sidebar, but by the time that fires, it's already been removed from the local instance -- though it'll show up again if the page is reloaded. We have to override the native "delete" behavior of [Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage/) to not actually delete, but to defer to the handler we've provided for the "delete" event.

**Comment by jywarren** [comment]
OK, this is partially complete in my local branch; now we need to ensure that the uploader adds a "warpable-#" id to newly uploaded images' sidebar elements, so this works for newly uploaded images too.

**Comment by numeroteca** [comment]
More on this behaviour: 
When an image is deleted it disappears from the sidebar. The top status check mark changes to red.
When the page is reloaded the image re-appears placed in the map. The top status check mark changes to green.
Map: http://mapknitter.org/maps/placa-salvador-segui-barcelona#
