### ISSUE TITLE
 Weekly Community Check-In #86 

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/mapknitter#1474]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Check-in 86

This week share what you are working on, feel free to leave a comment if you are blocked on anything and folks will get back with some help. :woman_technologist:   Happy coding :man_technologist: 

### To Outreachy  and mentors

Great to see the interns get working and it was really great to link up with you both last week :tada: . The new edited planning issues look superb :1st_place_medal: :1st_place_medal: 
Just a reminder: the first Zulip chat  is today at 13:00 UTC, do consider participating to get your questions answered by the organizers, learn from other interns and mentors and also contribute.
If there are any blogs feel free to leave the links below so we can check them out.

### Thank you note to focus issues contributors

 🥇 🥇 Thanks so much @jywarren   for working  on the migration from travis to git actions :rocket:   🥇 🥇

### Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by RuthNjeri** [comment]
Thanks @cesswairimu! I'll be sure to post the link to my blog here once done. 

I'm currently working on the All posts page, I've been able to make progress on what is needed. I'll be breaking it down into smaller tasks and begin working on them.

**Comment by RuthNjeri** [comment]
Hi everyone,

I was finally able to post my first Outreachy blog... [enjoy](https://publiclab.org/notes/ruthnwaiganjo/12-11-2020/hello?_=1607695851) 😄

**Comment by cesswairimu** [comment]
Hi all, I will keep this open for this week too...lets check-in here  this week too. Thanks

**Comment by jywarren** [comment]
Thanks Cess. I'm so relieved to be mostly done with the GitHub actions work! Some follow-ups now and then repeating (but simpler i hope) for some other PL repositories! 😅😁

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/8877 . Thanks everyone.
