### ISSUE TITLE
when rotated at a small size, images develop distortions

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/mapknitter#153]
images become trapezoids if they are rotated at a very small size.  the distortions are preserved when images are enlarged again.  Firefox on OS X
![screen shot 2015-03-27 at 4 34 00 pm](https://cloud.githubusercontent.com/assets/1203280/6878666/5079becc-d49f-11e4-9ac2-0dd9aa9cd481.png)

**Comment by mathewlippincott** [comment]
Using this bug I made a map that will break in every web browser
http://mapknitter.org/maps/portland-park-blocks-pole-test

**Comment by jywarren** [comment]
Haha wow! The ultimate MapKnitter breaker.

I have this theory that we hit the precision limit of floats in some very
zoomed in images... But unsubstantiated. Maybe not in this case. Thanks for
reporting.

**Comment by mathewlippincott** [comment]
Yeah I figured this was a mathematical precision problem-- I think the way quick way around is to enable closer zoom levels-- of course, I don't know what it'll take to get closer zoom levels ;-)

**Comment by ebarry** [comment]
I have also experienced this issue. The only way i have found to deal with it, is to delete the photo and re-add it.

**Comment by jywarren** [comment]
That works!!??!! Then the problem may be quite different than we imagined.

It could be enough then to have a "return to original dimensions" or "start
over" button.

**Comment by mathewlippincott** [comment]
these other bugs seem instances of the same:
#174
#204
#195

**Comment by jywarren** [comment]
Opened an issue over here to try to get help with this: https://github.com/publiclab/Leaflet.DistortableImage/issues/85 -- thanks!

**Comment by gauravano** [comment]
Hi @jywarren can we close this one as this issue is alraedy opened at #85? Thanks!
