### ISSUE TITLE
place with GPS button doesn't appear in sidebar without refresh

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/mapknitter#154]
In chrome, under images tab, I can't find auto-placement

![screen shot 2015-03-27 at 4 38 03 pm](https://cloud.githubusercontent.com/assets/1203280/6878685/b335c916-d49f-11e4-9932-57ef7c03aac7.png)

**Comment by jywarren** [comment]
I believe that means it did not find exif data for those images; can you
link to the map or images so I can run tests? Thanks!

**Comment by mathewlippincott** [comment]
http://mapknitter.org/maps/portland-park-blocks-pole-test

**Comment by mathewlippincott** [comment]
no, it finds the data-- the auto-placement button is in the uploads menu

**Comment by mathewlippincott** [comment]
I reloaded in chrome and I can see it now.

**Comment by jywarren** [comment]
Hmm, so it needs a refresh in chrome after uploading to appear in the sidebar, but not in the modal dialog?

**Comment by cesswairimu** [comment]
This was also solved in https://github.com/publiclab/mapknitter/pull/562 forgot to reference it

**Comment by cesswairimu** [comment]
![Peek 2019-05-02 04-09](https://user-images.githubusercontent.com/17081074/57052503-56458d80-6c90-11e9-9db3-3ea076357b20.gif)
