### ISSUE TITLE
selecting multiple images to upload from system dialog

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/mapknitter#155]
the upload screen currently requires me to select each image to upload individually.  It would be really nice to select a whole image folder or multiple images and have them upload in the background. 
![screen shot 2015-03-27 at 4 22 42 pm](https://cloud.githubusercontent.com/assets/1203280/6878822/0233e56e-d4a2-11e4-96ab-334d882d8be9.png)

**Comment by jywarren** [comment]
Huh, I'm not sure why that would be... But as a work around you can drag
multiple directly onto the map.
