### ISSUE TITLE
enable non-existent zoom levels with tile overscaling

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/mapknitter#156]
I'm trying to work with pole photos and they are about 1cm square on my screen at the lowest zoom level possible.  Is there any way to work smaller? I don't need better resolution.  my experience is suggesting that auto-placement will make pole mapping easier but I can't prove it because of #153

**Comment by jywarren** [comment]
This works in native Leaflet layers: https://github.com/Leaflet/Leaflet/issues/1798 and https://github.com/Leaflet/Leaflet/pull/1802

However, it doesn't in the [Google map tile plugin](https://github.com/shramov/leaflet-plugins). It seems that we should be able to get L.Google to inherit from L.TileLayer (as in [this abandoned pull request](https://github.com/shramov/leaflet-plugins/pull/89/files)) to allow it to inherit this ability, but that doesn't seem to be working in my tests. 

I think L.Google overrides some other L.TileLayer methods, which we have to port back in; key sections here: https://github.com/Leaflet/Leaflet/commit/b03f3221938448274b9f6c27c5ed707dd05b018d#diff-41e07cc2f66148151bde6b9e17c7f183R461

**Comment by jywarren** [comment]
How urgent is this? Should I work on #153 instead?

**Comment by jywarren** [comment]
It looks like the Google tile plugin was refactored for v1.0 of Leaflet: https://github.com/shramov/leaflet-plugins/pull/112

That means this may be easier to implement now, as the above error may not break it. We'd need to update the dependency in bower.json (https://github.com/publiclab/mapknitter/blob/master/bower.json#L17) to:

        "leaflet-plugins": "~1.5.3",

and run `bower install`, then manually test. 

I think we may need to change line 13 of this file, but it's already set to 24, which I believe is high enough, so it might be a simple upgrade and it'll start working.

https://github.com/publiclab/mapknitter/tree/master/app/assets/javascripts/mapknitter/Map.js#L13

**Comment by jywarren** [comment]
This was solved with our upgrade to Leaflet 1.x!
