### ISSUE TITLE
list all authors for a MapKnitter map

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#158]
based on all who've moved warpables

**Comment by jywarren** [comment]
Could this be part of the frontpage/placepage UI project @stefannibrasil ? Like, a list down the page of everyone whose images currently appear on the map?

**Comment by stefannibrasil** [comment]
hum, I can't visualize it now. Depending on how the info will be displayed, it may work. My only concern is putting too much information there, but that's something to try, for sure.

**Comment by cesswairimu** [comment]
@jywarren am torn between having this on the `view map` page or the `show` page which one do you feel is best? Thanks

**Comment by jywarren** [comment]
I think the view page would be great! Thanks, Cess!

**Comment by cesswairimu** [comment]
After https://github.com/publiclab/mapknitter/pull/862 is ready this be so easy to implement. Thanks to @divyabaid16
