### ISSUE TITLE
Coordinates not set on drag when making new map

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#1580]
https://mapknitter.org/maps/new

![image](https://user-images.githubusercontent.com/24359/148466477-813d2dc9-eec1-450e-a7bf-76f1b465ce07.png)

**Comment by reeshi-18** [comment]
@jywarren I want to take up this issue as a part of my contributions for Outreachy '22. 
I am interested to work on the project "MapKnitter.org Spam Management system"
Please assign me this issue

**Comment by reeshi-18** [comment]
@jywarren @TildaDares please guide me what is to be done in this issue so that I can start working on it

**Comment by jywarren** [comment]
Hi @reeshi-18 thank you!! have you taken on a first-timers-only issue already? If you have, then I can add some more detail here. 

Are you able to go to the address above and reproduce the issue?

1. visit https://mapknitter.org/maps/new (after logging in)
2. drag the map around and look for the coordinates to be auto-filled

I'm actually seeing it working -- see screenshot:
![mk](https://user-images.githubusercontent.com/24359/160667727-cdbae053-66f9-4456-b8cf-e9ad4f109570.gif)

If you can confirm this is working, we can close this!

**Comment by roli25** [comment]
@jywarren @TildaDares If this issue is still available, I would like to work on it.

**Comment by reeshi-18** [comment]
@jywarren the coordinates are set on dragging the map! I went through the entire map and coordinates were set at all places. According to me this issue is resolved and can be closed.

**Comment by jywarren** [comment]
Hi Thank you @reeshi-18 much appreciated!

@roli25 if you would like a first-timers-only issue, please check out https://github.com/publiclab/plots2/issues/10153, and if not perhaps you'd like to dig back into the issues to find another? Thank you!

**Comment by roli25** [comment]
Hello @jywarren, I have done a First timers issue. I would like to work on #1320. I have commented on that issue but got no reply yet. If you could assign me that issue, it would be really helpful.
