### ISSUE TITLE
Altitude considerations for autoplacement

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/mapknitter#159]
It would be great if the EXIF data for altitude were compared with existing terrain data to take a shot at scaling the image appropriately. This would help autoplacement.  A simpler version might just be a "set altitude" box where I can manually enter a value.  for pole/drone expeditions with consistent altitudes this would be very useful and speed autoplacement.

**Comment by jywarren** [comment]
+1+1+1 this would be great. Code is stubbed out here: https://github.com/publiclab/mapknitter/blob/master/app/assets/javascripts/mapknitter/Map.js#L207-L246

**Comment by jywarren** [comment]
Done! Closed in #176
