### ISSUE TITLE
Requiring a lat/lon

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#161]
Mapknitter is requiring I know my Lat/long to find my map. Previously the address used to work.

**Comment by jywarren** [comment]
Hi, Stevie - typically it will auto-lookup your lat/lon from the address.
Is that not happening? What address are you entering? Maybe it can't find
the address you're entering.

**Comment by steviepubliclab** [comment]
sure this was the address I was using: 141 Pine Street Bourg la 70343
<https://www.openstreetmap.org/#map=12.0/29.5518167/-90.537798>

**Comment by jywarren** [comment]
Hmm, mine gets it fine: 
![image](https://cloud.githubusercontent.com/assets/24359/7205247/f5534c18-e4f5-11e4-95b3-956feb03db45.png)

I wonder if your browser is having issues or something; the other bug you filed was also JavaScript Ajax related. If these problems persist, could you try these things in an Incognito tab, or in another browser? What browser/OS are you using?

**Comment by steviepubliclab** [comment]
I'm using Chrome Version 41.0.2272.118 (64-bit)

**Comment by jywarren** [comment]
I'm going to close this unless it recurs. Thanks for reporting!

**Comment by steviepubliclab** [comment]
I got it to work this time. Thanks
