### ISSUE TITLE
Navbar overlapping site content

### ISSUE THREAD

**Issue by sakshi-2412** [publiclab/mapknitter#1611]
### What happened just before the problem occurred
Bootstrap fixed-top navbar is overlapping the site content, thus notifications are not completely visible.

https://user-images.githubusercontent.com/85152262/157945224-a73748a3-1eca-4806-8dc4-76cb58dac068.mp4

Specifically, for a particular screen size the content hides behind the navbar.

![navbar-overlapping](https://user-images.githubusercontent.com/85152262/157944147-ee590a46-64a1-4bd7-9bfb-ab40c297a032.png)

### Relevant URLs

https://mapknitter.org/
https://mapknitter.org/gallery

Browser - Google Chrome
Version - 99.0.4844.51
OS -Ubuntu 20.04

**Comment by sakshi-2412** [comment]
Noting that this overlapping problem is much more visible in Ubuntu than Windows (almost nil). Both have the same google chrome version (checked in it my dual boot system)

**Comment by sakshi-2412** [comment]
Replacing `navbar fixed-top` with `navbar static-top` will solve this problem
@jywarren @cesswairimu can I open a PR for the same?

**Comment by cesswairimu** [comment]
Hey @sakshi-2412,  sure we would love your help, go ahead. Please test locally if possible and share some screenshots on the PR. Thanks

**Comment by sakshi-2412** [comment]
yes sure!

**Comment by chepyego** [comment]
is this ticket available?, am little bit confused there are so many projects here  at Public.am outreachy 2022 applicant, is this project in outreachy?

**Comment by imranburki** [comment]
I am Outreachy 2022 applicant. Can i work on this issue, If it is still open?

**Comment by sakshi-2412** [comment]
Hey @chepyego @imranburki , sorry but I have already opened a PR for this issue. You can work on other issues if you want :sparkles:
