### ISSUE TITLE
Weekly Community Check-In #134 - Outreachy  Contribution starts this week!

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/mapknitter#1615]
Hi everybody! 👏

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become a leader of tomorrow. 💯

## Outreachy Contribution starts this week!  

The Outreachy contribution period  officially  starts on Friday,  the 25th. We will therefore see an increase in aspirants coming to our various coding spaces. Lets try to help where we can and thanks all : because everyone is  already doing that,  with the ones that have reached out already :heart: :heart: :heart: :heart: 
If you are an Outreachy or a GSoC applicant:  First of all,  welcome to PublicLab :balloon: . Please make sure you checkout our [code of conduct](https://publiclab.org/conduct) before you continue(_if you haven't yet_). Our coding landing page is [here](https://code.publiclab.org/) and our communication channels can be found [here](https://publiclab.org/chat). [Here](https://github.com/publiclab/plots2/issues/10840) is the welcome issue for discussion for the Outreachy progam.  I will open a welcome issue for GSoC in the coming days and mention it here. Feel free to say hi below in the :slightly_smiling_face:  Thanks.

**Other helpful links for both programs:**
[Projects discussion Issue](https://github.com/publiclab/plots2/issues/10754) 
[First timer issue request](https://github.com/publiclab/plots2/issues/10153)
[Developers guides](https://publiclab.org/wiki/developers)

### Mentors
Thanks again everyone who have volunteered  to mentor this summer :100: :100: .
Here are the next important dates for each program:
Outreachy:
-  March 25, 2022 - Contribution period begins
- April 22, 2022 - Contribution period ends
- April 22, 2022 at 4pm UTC - Final application deadline

GSoC:
- March 7 - April 3 Potential GSoC contributors discuss application ideas with mentoring organizations
-  April 4 - 18:00 UTC GSoC contributor application period begins
- April 19 - 18:00 UTC GSoC contributor application deadline

### Applicants
Once the contribution period officially begins for each program.  We will try to prioritize getting you first-timer issues to work on. So please mention you are Summer of applicant(_and specifically which program because there are different timelines for each_) when requesting for a first-timer issue. Please be patient if sometimes getting you an issue to work on, takes a while. Thanks.
 
## This week's focus Issues
This week's focus is creating first-timer-issues and adding more info to fto-candidates for new contributors. The contribution period for Outreachy starts officially on March 25, 2022(_Friday this week_) .  And we will see an increase in demand for these issues. So creating some and you can label them `outreachy` too to preserve them for Outreachy applicants.

We will very much appreciate any help on these issues. We will add a thank you message here in next week's check-in if you contribute to any of these. Thanks in advance 😄

### Thank you note to focus issues contributors

Many thanks to all the folks who have been helping summer of code aspirants  across all our channels

:star: :star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star::star::star:
Many thanks to   @jywarren , @TildaDares,  @Sakshamgupta90 ,   @RaviAnand111 , 
and all the others I might have missed. Thanks all 
:star: :star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star: ::star::star::star:

## Next Check-in
If you would like to open the next check-in..Leave a comment below. We are happy to help if its your first time

**Thanks everyone for making Public Lab awesome** :heart:  
Have a great week ahead all :balloon:

**Comment by RaviAnand111** [comment]
Hey @cesswairimu, I would like to open the next week's check in.

**Comment by cesswairimu** [comment]
Thanks @RaviAnand111 :tada: 
Please feel free to ping me or Tilda if you need any help. Thanks

**Comment by jywarren** [comment]
I'm making some first-timers-only candidates which are also good issues for folks who've recently made a first-timers-only contribution! Please check out https://github.com/publiclab/plots2/labels/fto-candidate and I'm happy to answer questions too!

**Comment by cesswairimu** [comment]
Outreachy welome issue is here https://github.com/publiclab/plots2/issues/10840

**Comment by chepyego** [comment]
do we have two project here plot2 and mapkinter right?

**Comment by cesswairimu** [comment]
Hi @RaviAnand111 feel free to open the check-in anytime today. 
Hi @chepyego we have a number of projects in publiclab, you can find them all [here](https://github.com/orgs/publiclab/repositories). Thanks all

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/10871. Thanks
