### ISSUE TITLE
Map show page buttons not scaled

### ISSUE THREAD

**Issue by sakshi-2412** [publiclab/mapknitter#1625]
### Problem

Buttons on map show page have no padding and are not of the same width.

![buttonsBefore](https://user-images.githubusercontent.com/85152262/161514758-4ebf0db3-dbdf-43ed-bddb-7af8a441085d.png)

Solution ->

![buttonsAfter](https://user-images.githubusercontent.com/85152262/161514985-d573d6d0-4ea2-4056-bbfa-ab797d7ce94c.png)

### Relevant URLs

https://mapknitter.org/maps/la-fe-dam-the-weir   and related pages

If it looks fine, I will open a PR soon

**Comment by cesswairimu** [comment]
Hi @sakshi-2412 and thanks for raising this. Could you please add the details of the device OS and browser you are using smth different on my end. This  is what I see on the same url. I have tried with chrome and firefox on Ubuntu 20 
![Screenshot from 2022-04-14 08-25-41](https://user-images.githubusercontent.com/17081074/163319770-b1f40000-30a9-424e-bc5c-f83317d798f5.png). I have checked your PR out it is looking good the buttons are the same width, I believe however, we would like to maintain the design of having the buttons side by side, as shown above...what do you think? Thanks

**Comment by sakshi-2412** [comment]
hey @cesswairimu :sparkles:  .. i am using the following versions ->
Browser - Google Chrome
Version - 99.0.4844.51
OS -Ubuntu 20.04

For the current design of side-by-side buttons, is it getting disturbed for smaller screens on your browser? I am not sure how to solve it ( media queries? )... since it is displaying differently on our browsers.

**Comment by cesswairimu** [comment]
Hi @sakshi-2412 I was able to reproduce the error using a tablet. Seems the display changes based on screen/resolution and I agree this is the safest style for all the screens. Thanks for raising and working on this :100: . Merging the PR in a few. Thanks
