### ISSUE TITLE
Update Onboarding/Installation Documentation in README.md

### ISSUE THREAD

**Issue by PeculiarE** [publiclab/mapknitter#1626]
### What happened just before the problem occurred
I tried setting up the project on my local machine and faced some challenges while doing so because the README.md for the project had some issues and didn't cater to some specific problems faced by macOS Big Sur users like me. These include:

- [ ] Table of contents misdirection especially in the installation section - #1628
- [ ] Missing forking step in installation
- [ ] Sentence structure issues and typos
- [ ] RVM installation errors for macOs Big Sur users

Most of these task items can be properly broken down into very simple FTO issues for newbie contributors and once resolved would help in reducing issues faced and time taken for new contributors trying to successfully install the project on their local machines.

### Relevant URLs
https://github.com/publiclab/mapknitter/blob/main/README.md

### Browser, version, and operating system
Google Chrome Version 100.0.4896.60 (Official Build) (arm64), MacOS Big Sur version 11.4

**Comment by PeculiarE** [comment]
Hello @jywarren @cesswairimu @TildaDares....please review and let me know if I can go ahead with this. Thank you 😄 .

Also do you need me to provide video or screenshot evidence? Or are the explanations okay?

**Comment by TildaDares** [comment]
Hi @PeculiarE, this sounds like an amazing idea. Can you specify which part of the documentation caused issues for you?

**Comment by PeculiarE** [comment]
Thank you 😄  @TildaDares. Okay, so here goes:

**1. Table of contents misdirection especially in the installation section**:

Clicking on the headers (specified with arrows in the image below) doesn't take me anywhere. Plus the arrangement of the subheadings in the table of contents don't match exactly what's in the body of the installation section. And it got me a bit confused at first before I was able to successfully navigate my way.

<img width="1262" alt="Screenshot 2022-04-04 at 11 37 33" src="https://user-images.githubusercontent.com/75625011/161528424-c045de4d-e077-4266-ac07-81f682ad1104.png">


**2. Missing forking step in installation**
The forking of the repo is a crucial step not stated in the installation steps (see screenshot below) and I had already gone far in my installation process before realising I cloned the original repo instead of a forked copy.

<img width="1026" alt="Screenshot 2022-04-04 at 11 40 25" src="https://user-images.githubusercontent.com/75625011/161528937-d4af32ee-1b69-4163-a49b-c569766ac7e1.png">

Something similar like what we have on the community-toolbox repo would go a long way in helping contributors new to open source: https://github.com/publiclab/community-toolbox/blob/main/docs/getting_started.md

**3. Sentence structure issues and typos**
For example, the sentence in the screenshot below can be better structured and punctuated for easier understanding.

<img width="1017" alt="Screenshot 2022-04-04 at 11 42 27" src="https://user-images.githubusercontent.com/75625011/161529313-bebf7ca2-670f-4c36-aa64-7e18eb6f2d27.png">

**4. RVM installation errors for macOs Big Sur users**
As a macOS Big Sur user, the `rvm install 2.4.6 ` command highlighted with the arrow below failed to run and kept on throwing a compilation error. On browsing stackoverflow and some other github threads, I was able to find out this was specific to MacOS Big Sur users and luckily, also got a solution to fix it. I believe adding that to our documentation would help future users with a Big Sur Macbook.

<img width="1074" alt="Screenshot 2022-04-04 at 11 39 41" src="https://user-images.githubusercontent.com/75625011/161528770-9e329f47-1b62-4b17-ab90-29cab6251474.png">

**Comment by TildaDares** [comment]
These are really great observations @PeculiarE. Well done!!

I think it's better if you work on it since you know the problems and how to fix them.
