### ISSUE TITLE
[BUG] Empty search string on page

### ISSUE THREAD

**Issue by kunmi02** [publiclab/mapknitter#1635]
### What happened just before the problem occurred

Clicking on the search icon on the home page returns an error. The appropriate way there should be a validation for empty strings before the query is been ran

### Relevant URLs
http://127.0.0.1:3000/search?q= on local

https://mapknitter.org/search?q=
### PublicLab.org username
akinkunmi02
(to help reproduce the issue)

### Browser, version, and operating system
Google chrome, MacOs

For bug reports, fill out the above template; for feature requests, you can delete the template.
<img width="1440" alt="Screenshot 2022-04-08 at 14 33 22" src="https://user-images.githubusercontent.com/27483062/162446197-8415c579-9bc5-47f2-b5ba-80d93eaaf94e.png">

**Comment by kunmi02** [comment]
@jywarren and @TildaDares I saw this issue on the project and I would like to work on the fix.

**Comment by jywarren** [comment]
Hi @kunmi02 we'd welcome a PR for this - should it be a simple conditional to check that it's not nil or zero? Thank you!
