### ISSUE TITLE
Export map taking long

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#164]
This one has been stuck on 4 of 7 for a long time now : http://mapknitter.org/maps/grand-bois--2#

**Comment by jywarren** [comment]
Hi, Stevie - on http://mapknitter.org/exports it says the resolution was 0cm/px -- that's odd. 

Did you try the tips linked to below the Export button? 

![image](https://cloud.githubusercontent.com/assets/24359/7208248/68e00196-e50d-11e4-9f43-6f699aa160bd.png)

**Comment by steviepubliclab** [comment]
Ah, ok that showed up when I refreshed the page. Let me try a lower
resolution
