### ISSUE TITLE
Weird exported jpeg image: too much of the image cropped

### ISSUE THREAD

**Issue by numeroteca** [publiclab/mapknitter#166]
Is it normal that the border of the images are cropped?

Besides: I would expect not to see images "transparent" when there is no image behind.

Working on this map: http://mapknitter.org/maps/2015-04-14-barcelona-macba#

Map in mapknitter:
![macaba-mapkintter](https://cloud.githubusercontent.com/assets/1223722/7234893/cdf8a9d2-e78a-11e4-9fa9-20ce9e7788af.png)

Exported image:
![2015-04-14-barcelona-macba-2](https://cloud.githubusercontent.com/assets/1223722/7234856/81d6a004-e78a-11e4-87c6-7286aab1e0e8.jpg)

cc @ebarry

**Comment by jywarren** [comment]
No, this is another instance of this bug: https://github.com/publiclab/mapknitter/issues/88 which remains unresolved (although we've solved past instances of it) -- can you copy links to your raw photos into there and hopefully we'll have an opportunity to figure that bug out soon.
