### ISSUE TITLE
Outline mode makes images not entirely transparent

### ISSUE THREAD

**Issue by numeroteca** [publiclab/mapknitter#168]
When shifting to Outline mode the image has "opacity: 0.35".
Is it possible to make it entirely transparent and just have the border (opacity: 0;) while keeping the border?

When one or more images are set to outline mode it is impossible to see the "ground" photo.

operating system: Ubuntu Linux 14

**Comment by ebarry** [comment]
+1

**Comment by jywarren** [comment]
This is possible on this line of code in Leaflet.DistortableImage: https://github.com/publiclab/Leaflet.DistortableImage/blob/master/src/edit/DistortableImage.Edit.js#L196

Can you move your issue request to that repo please? Thanks!

https://github.com/publiclab/Leaflet.DistortableImage/issues

**Comment by jywarren** [comment]
I attempted this but it makes for no borders at all, as outlined in the referenced issue publiclab/Leaflet.DistortableImage#6 :-( 

That doesn't seem viable!
