### ISSUE TITLE
FTO: Correct console messages and errors in rake tasks

### ISSUE THREAD

**Issue by PeculiarE** [publiclab/mapknitter#1680]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all) and this means we have worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Claim the issue by commenting. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
<details>
  <summary>💡 <i>Learn how to claim</i> 🙋</summary>
  <h3>Claiming an issue</h3>
  <p>Unless the issue is marked as reserved for someone, you can just say "I'd like to try this!" and then you've claimed it - no need to wait for someone to assign it to you. Just be sure you link your pull request (PR) to this issue so we can see where your solution is.</p>
  <p>And open one early if possible - even before you've completed it with additional commits - and others can help you figure out any issues you may face.</p>
</details>

- [ ] 📝 **Update** the files specified below in the `mapknitter` repository (press the little pen Icon) and edit the line as shown below.

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

**1st file to be changed:** [attachment_tasks.rake](https://github.com/publiclab/mapknitter/blob/5b1d19c8018867921a6209150f746438507f8207/lib/tasks/attachment_tasks.rake#L39)

```diff
@@ -36,7 +36,7 @@ namespace :utils do
     task :empty_s3_bucket => :initialize_s3 do
       from_bucket = @s3.bucket(ENV['BUCKET'])
 
-      puts "Emtptying #{from_bucket.name}"
+      puts "Emptying #{from_bucket.name}"
       bucket.keys({'max-keys' => 100}).each do |key|
         (1..10).each do |try|
           begin
```

**2nd file to be changed:** [db.rake](https://github.com/publiclab/mapknitter/blob/5b1d19c8018867921a6209150f746438507f8207/lib/tasks/db.rake#L13)
```diff
@@ -10,7 +10,7 @@ namespace :db do
     ActiveRecord::Base.connection
     puts "There is a database"
     rescue StandardError
-      puts "There is NOT a database"
+      puts "There is no database"
       exit 1
     else
       exit 0
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below, and [reach out in our chatroom](https://publiclab.org/chat)!

**Comment by TildaDares** [comment]
Looks good @PeculiarE. Thank you!!

**Comment by BenoitDeo** [comment]
Hiya, I would like to take over this issue.

**Comment by akanbifatimah** [comment]
I would love to be assigned this issue @TildaDares

**Comment by TildaDares** [comment]
Hi @akanbifatimah, we usually leave FTOs for first timers only. Thank you for offering to help ❤️

**Comment by akanbifatimah** [comment]
😊😊❤

**Comment by jongwon254** [comment]
Hey, can I try this one? :)

**Comment by TildaDares** [comment]
Hi @jongwon254, it looks like you haven't opened a PR in `publiclab/mapknitter`.

**Comment by jongwon254** [comment]
Hi @TildaDares, I think I opened a PR right now.
Could you please check?
