### ISSUE TITLE
Allow multiple images selection for upload

### ISSUE THREAD

**Issue by PeculiarE** [publiclab/mapknitter#1690]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Currently on MapKnitter, when a user tries to upload images onto their created maps, they can drag and drop multiple images at once. But on using the 'Select Images' button, they can only pick one file from their computer at a time.

https://user-images.githubusercontent.com/75625011/167290277-d468c4d1-93c0-4e5a-b051-fd7e3661b344.mp4

> What did you expect to see that you didn't?

I expect that users should be able to select several images from their computer at once the same way they are able to drag and drop multiple images onto the image modal at once.

### Please show us where to look

https://mapknitter.org/maps/(map-name)/edit ...where (map-name) is the name of the map being edited.

### What's your PublicLab.org username?

perhisohwode

### Browser, version, and operating system

Google Chrome Version 100.0.4896.60 (Official Build) (arm64), MacOS Big Sur version 11.4

**Comment by PeculiarE** [comment]
Hi @TildaDares, @cesswairimu, @jywarren....can I please work on this?

**Comment by cesswairimu** [comment]
Hi @PeculiarE please go ahead and really good catch :tada: . Thanks!

**Comment by PeculiarE** [comment]
Alright. Thank you @cesswairimu 😄
