### ISSUE TITLE
Auto place picture with skycam app crash the map

### ISSUE THREAD

**Issue by lotelx** [publiclab/mapknitter#170]
Hi,
I tried to autoplace a picture taked with skycam app but the map stop working (see picture atached).

This is the picture taked with skycam that I try to auto place
![picture_152012122020](https://cloud.githubusercontent.com/assets/1766484/7288959/b2c4ae3e-e93f-11e4-96f4-da71bfb20759.jpg)

This is what I have:
![captura de pantalla 2015-04-22 a la s 22 33 15](https://cloud.githubusercontent.com/assets/1766484/7289128/1ec1a1d0-e942-11e4-9aca-3dec806a968c.png)

**Comment by lotelx** [comment]
I used firefox 36.0.4 on mac.

I realized now that firefox is not working at all anyway :(

**Comment by btbonval** [comment]
I can't read that language but I think the error on the map is saying that no images were found at that zoom level.

Lo sentimos / Sorry?
no disponemos de imagenes / no images?
para esta vista / at this zoom level?

The lack of images is a problem with the map project we use but the project is not ours, I don't know if we can fix that.

@jywarren What can be done about no images at the current zoom level? Is there a way participants can contribute?

**Comment by lotelx** [comment]
Yes, This means that there is no images at that zoom level.
The problem is when I upload a picture automaticly crash and I can't change the zoom neither modify the image or do anything in the map.
The only solution is delete the image and refresh the page.

But anyway the problem is general with firefox+mac. Is not working properlly :(

**Comment by jywarren** [comment]
Hi, Lot - gracias por la ayuda. Debemos pedir ayuda en el error de Firefox (aqui: https://github.com/publiclab/mapknitter/issues/143) porque yo no he podido resolverlo :-(

Tambien hay un issue abierto sobre niveles de zoom muy altas: https://github.com/publiclab/mapknitter/issues/156

Gracias por apuntar estes errores; ojala que los resolveremos pronto.  Como que ya hay issues abiertos, voy a cerrar la esta. Siga por favor los otros si quieres saber como va! :-)
