### ISSUE TITLE
deletion inconsistencies

### ISSUE THREAD

**Issue by ebarry** [publiclab/mapknitter#172]
I was able to delete in that i wasn't denied permission, 
BUT 
the photos reappear on refresh and in the export. 

See "parking lot" images in these two maps: 
http://mapknitter.org/maps/city-park-nir#
http://mapknitter.org/maps/haaas-mapster#

**Comment by jywarren** [comment]
Hi, what images, were you logged in, how did you delete them, what browser?
What happened when you did delete them and did they persist in the images
tab as well?

Thanks!

**Comment by ebarry** [comment]
Some images that were freestanding from the main map.

I was logged in

Chrome

Deleted and the popup warned me that this action could.not be undone, I
clicked delete again and they disappeared. But, they reappeared in export
and they reappeared on the map upon reload.

**Comment by jywarren** [comment]
Can you open the JavaScript console and see if there was an error once you
click the popup OK? Thanks.

**Comment by ebarry** [comment]
![screen shot 2015-05-01 at 11 21 16 am](https://cloud.githubusercontent.com/assets/161439/7432223/3502fee0-eff4-11e4-9d0e-95d912ecd0cb.png)

DELETE http://mapknitter.org/login 404 (Not Found)

**Comment by jywarren** [comment]
After that error are you still logged in if you go to another page on the
site?

**Comment by ebarry** [comment]
yes - i'm still logged in on other maps on mapknitter and publiclab.org

**Comment by jywarren** [comment]
> did they persist in the images tab as well?

**Comment by jywarren** [comment]
I just tried and it worked fine; is this happening in other browsers or for other users?

**Comment by jywarren** [comment]
Closing; feel free to re-open if this is reproducible in another browser. I believe we also patched some other deletion issues, so although it's hard to tell, this could've been fixed as well.

**Comment by ebarry** [comment]
so it appears that only map owners can actually permanently delete images from a map. As a non-map owner, i am able to delete images, yet on reload they reappear. Maybe we should just add a message to notify non-map owners that only the owners can delete images.

**Comment by jywarren** [comment]
Good idea - we already do this for non-logged-in users, so it wouldn't be hard. Change would happen on this line: https://github.com/publiclab/mapknitter/blob/master/app/assets/javascripts/mapknitter/Map.js#L392

Can you file a new issue?
