### ISSUE TITLE
image doesn't scale, becomes rhombus, in Safari

### ISSUE THREAD

**Issue by patcoyle** [publiclab/mapknitter#174]
For this single image map, image doesn't scale, rather stretches in one dimension or stats taking on rhomboid shape. On Mac using Safari.
http://mapknitter.org/maps/gps-track-of-tour-washington-dc#

**Comment by jywarren** [comment]
Hm, I wasn't able to reproduce this, but will try it out in Safari when I can get to a Mac.

**Comment by jywarren** [comment]
Is this using the rotate or distort tool?

**Comment by jywarren** [comment]
Created this to consolidate and get help! https://github.com/publiclab/Leaflet.DistortableImage/issues/85 -- thanks!

**Comment by jywarren** [comment]
I believe this is now solved by @sashadev-sky -- https://github.com/publiclab/Leaflet.DistortableImage/issues/85#issuecomment-474420914 !!! 🎉 

We'll publish the update soon 👍
