### ISSUE TITLE
Legacy annotations missing

### ISSUE THREAD

**Issue by ebarry** [publiclab/mapknitter#177]
The URL http://mapknitter.org/map/view/2014-06-27-nyc-statenisland-northshore redirects to http://mapknitter.org/maps/2014-06-27-nyc-statenisland-northshore where the annotations added last fall are not visible. **UPDATE: just found the link under the Annotate tab to "Click Here" to add annotations using the old system: http://mapknitter.org/embed/2014-06-27-nyc-statenisland-northshore?annotations=true -- this interface does have the tools, but doesn't display points and polygons that were previously added to the map.** Further, when using the legacy tools to add either a point or a color-coded polygon, although dialogue boxes do pop up and prompt you to add info window content, the end result fails to add a point or polygon on the map. 

Here's a screenshot of what some of the old annotations looked like:
![screen shot 2014-12-11 at 2 32 48 pm](https://cloud.githubusercontent.com/assets/161439/7776006/d58fe6a6-0085-11e5-8478-3e5c3c0eaf2e.png)

Is it planned that legacy annotations will be moved to the new mapknitter?

I am using Chrome on mac. My publiclab username is "liz"

**Comment by jywarren** [comment]
I think you may have just missed the link to the old annotations; see just above the annotations button?

![tmp_26825-screenshot_2015-05-22-13-02-25 21563272054](https://cloud.githubusercontent.com/assets/24359/7776745/0c952196-0083-11e5-9b7b-3d9f2f4bb287.jpg)

**Comment by ebarry** [comment]
UPDATE: just found the link under the Annotate tab to "Click Here" to add annotations using the old system: http://mapknitter.org/embed/2014-06-27-nyc-statenisland-northshore?annotations=true

This interface does have the tools, but doesn't display points and polygons that were previously added to the map. Further, when using the legacy tools to add either a point or a color-coded polygon, although dialogue boxes do pop up and prompt you to add info window content, the end result fails to add a point or polygon on the map.

**Comment by jywarren** [comment]
fixed http://mapknitter.org/embed/2014-06-27-nyc-statenisland-northshore?annotations=true
