### ISSUE TITLE
First upload of images requires refresh to see in images tab

### ISSUE THREAD

**Issue by skilfullycurled** [publiclab/mapknitter#179]
When you upload your images when there aren't any images already, they do not appear in the images tab until you refresh the browser.  After refreshing, subsequent uploads do appear.  Note, the use of "first" in the subject refers to the state of not having any images already.  If you delete all the images the problem will return.

Browsers: Firefox 38.0.1, Chrome 43.0.2357.81

**Comment by jywarren** [comment]
Hmm, is this related to #154? I think this *was* working at some point

**Comment by sashadev-sky** [comment]
I am closing this issue as a later one #226 is opened and its now a duplicate. I will transfer additional information the user has provided onto that issue

**Comment by jywarren** [comment]
awesome - great work, Sasha!
