### ISSUE TITLE
Remove appearance of "Looks like this is a new map" modal after deleting all images

### ISSUE THREAD

**Issue by skilfullycurled** [publiclab/mapknitter#180]
If you delete all of the images you have uploaded in the images tab, the "Looks like this is a new map" modal (see attached) appears.  I think this is unnecessary.  If you've already uploaded images, it is not a new map, and you know how to begin.

![screen shot 2015-06-01 at 12 14 07 pm](https://cloud.githubusercontent.com/assets/950291/7918463/358e19c8-0857-11e5-8d7d-5e61ad6a1a35.png)

**Comment by jywarren** [comment]
Its sort of a question of how to tell if it's a new map. We could store in
a field if its ever had an image, but right now we just guess by seeing if
it currently has any.  This is not always accurate but its pretty easy.
Maybe we only show it if there are no images and it was created recently?

**Comment by skilfullycurled** [comment]
Ah.

So the issue is that because the page refreshes anytime you modify the images (in this case delete), it is as though you have created a map for the first time.

The UX issue for me isn't that it should never appear once you've seen it, it's that it's unnecessary for it to appear after you've already seen it in the current session.  I think it's entirely reasonable to have it reappear anytime you open the map and there aren't any images.

Therefore, what about leveraging a session cookie (or something like it in a field)?  Instead of having it check if the map previously had any images in the entire history of the map's creation, instead, it checks anytime you open the map if there are any current images or if it's an un-expired session.  If either one is true, then the modal doesn't appear.

**Comment by jywarren** [comment]
That's a good solution! It can contain the current URL so the cookie
doesn't prevent this from happening on another map.

Or we could use localStorage, similarly.

**Comment by gauravano** [comment]
This can form a nice issue :) Thanks @skilfullycurled and @jywarren!
