### ISSUE TITLE
Problems with export in MapKnitter 2.0

### ISSUE THREAD

**Issue by maurogiovanni70** [publiclab/mapknitter#182]
Dear,
I have a problem with the export function in MapKnitter 2.0.
This is the original map in MP2
![caresana_mapknitter](https://cloud.githubusercontent.com/assets/12950707/8229418/d8ef995e-15b6-11e5-8c40-fcdd308c78fe.JPG)
When I export the result is the following
![caresana-archeological-site-1](https://cloud.githubusercontent.com/assets/12950707/8229431/f20cbfb6-15b6-11e5-8637-c4f0390072a1.jpg)
What can I do?

**Comment by jywarren** [comment]
Can you link to the map itself?

**Comment by maurogiovanni70** [comment]
Dear Jeffrey,
here the link.
http://mapknitter.org/maps/caresana-archeological-site

Thanks for your interest!
Giovanni


Citando Jeffrey Warren <notifications@github.com>:

> Can you link to the map itself?
> On Jun 18, 2015 6:38 AM, "maurogiovanni70" <notifications@github.com> wrote:
>
>> Dear,
>> I have a problem with the export function in MapKnitter 2.0.
>> This is the original map in MP2
>> [image: caresana_mapknitter]
>> <https://cloud.githubusercontent.com/assets/12950707/8229418/d8ef995e-15b6-11e5-8c40-fcdd308c78fe.JPG>
>> When I export the result is the following
>> [image: caresana-archeological-site-1]
>> <https://cloud.githubusercontent.com/assets/12950707/8229431/f20cbfb6-15b6-11e5-8637-c4f0390072a1.jpg>
>> What can I do?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/publiclab/mapknitter/issues/182>.
>>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/publiclab/mapknitter/issues/182#issuecomment-113695607



Giovanni Mauro, PhD
Ricercatore in Geografia

LabGIS - disugis.units.it
Dipartimento di Studi Umanistici
Università degli Studi di Trieste

Tel: 040-5583631
Skype: giovannimauro70
Twitter: @giomaud

**Comment by jywarren** [comment]
Hi - is it possible that the image is correct, if you consider that it's "unprojected" -- i.e. the exported image is not in spherical Mercator, but simply x and y are exactly latitude and longitude, which at your latitude are not equal?

**Comment by maurogiovanni70** [comment]
Dear Jeffrey,
thanks for your answer.
However, I don't think it's a problem of coordinates.
I already use MapKnitter 2.0 for the same area and with the same camera (IR camera from Long Driveway), as you can see here

http://mapknitter.org/maps/infrared-caresana--trieste-

In order to have better results, this time I tried to take pictures with the balloon placed higher (about 120 m).
But this time I have problem with MapKnitter...

best regard,
Giovanni

**Comment by jywarren** [comment]
After trying a re-export, it looks to me like the image is being cut off -- this seems to be another version of #88 - attempting a fix based on that fix. Thanks, hold on a minute!

**Comment by jywarren** [comment]
I think that worked!

**Comment by maurogiovanni70** [comment]
it's work!!! 
Tank's for your precious help.
Giovanni

**Comment by jywarren** [comment]
:-)
