### ISSUE TITLE
pick the images on top

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#184]
Not sure if this is open somewhere or not. But I'd like to be able to pick which images are set on top of which. For example this map I've been working on, (http://mapknitter.org/maps/gorilla-garden) really only works when certain images are on top, and evidently they aren't the default ones, so whenever I try to post it anywhere, it doesn't come out as good as it should.

**Comment by jywarren** [comment]
Image sorting is a very popular request which we haven't been able to implement yet; it's a bit complex and would be a big project: #116
