### ISSUE TITLE
Circles not tracking with image

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#185]
The circles that are supposed to be on the coners of my picture are not tracking with my image. I'm using Firefox with a Linux OS

**Comment by jywarren** [comment]
Screenshot? And can you post this on
https://github.com/publiclab/Leaflet.DistortableImage/issues -- there may
already be one for this. Thanks!

**Comment by steviepubliclab** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/7490478/8369313/170fed62-1b7d-11e5-9531-19f753a0752c.png)

**Comment by jywarren** [comment]
Thanks - can you close this and copy it over to the other repository? Thanks!
