### ISSUE TITLE
link export image order to the order displayed in browser

### ISSUE THREAD

**Issue by ebarry** [publiclab/mapknitter#192]
Basic level: 
- The client-side and server-side draw order should be the same: submit an `order=23,35,1,5,26,56` param on export
- Result: what the browser shows the user by default (on refresh) will be the same as what is created during export. 

Slightly more:
- client-side reordering by clicking is stored as an array of `ids` which is submitted with the export request

SuperCool level: 
- implement full custom ordering in the user interface, as in #116

**Comment by btbonval** [comment]
It sounds like SuperCool level would have an interface that looks like layers of gimp or photoshop.

**Comment by ebarry** [comment]
hey, I'm not sure where this related issue should go.

_The problem:_ It used to be that in Mapknitter1 after you reloaded the browser, the smallest image would draw on top. In Mapknitter2 this is no longer reliable. The smallest and highest-res images become inaccessible under larger images -- they can't be "clicked" on them in the graphic interface. 

_The suggested solution:_ Use the list of named images in the image tab to select / activate / bring-to-top-of-draw-order-in-the-map 

Then "client-side draw order" will really be possible!

**Comment by jywarren** [comment]
Hi, Liz - it looks like those suggestions fit nicely under #116 -- can you move them over there?

**Comment by jywarren** [comment]
This is handled in the new multi-image export process -- see #818 - thanks!
