### ISSUE TITLE
images distort when scaling

### ISSUE THREAD

**Issue by patcoyle** [publiclab/mapknitter#195]
See attached screenshot of in-progress map: http://mapknitter.org/maps/livermore-ca-mobius-with-8mm-lens
Image at bottom right is example where when attempting to scale, size, or rotate, the image distorts. Sometimes, to trapezoidal shape, sometimes "squashed" or stretched in one dimension.

```
what you did just before the problem occurred: Observed problem previously in Safari 8.07, Firefox 39, so tried Chrome 44.0.2403.125.
your browser and browser version: Noted above
your operating system: OSX 10.10.4
any web addresses needed to see the problem (such as the URL of this page): 
```

http://mapknitter.org/maps/livermore-ca-mobius-with-8mm-lens
    your PublicLab.org username (if you have one): patcoyle
    describe how urgent the problem is (desperate or just-trying-to-help!): Mapknitter is mainline tool, so if systemic, urgent.

If you are able, it may also help to quickly resolve the issue if you:

```
test if it happens in a different browser or on another computer: Noted above
test if it happens whether you are logged in or not (if applicable): NA
test if it affects other users, or whether this happens to you only sometimes: Don't know
```

![screenshot skewed image](https://cloud.githubusercontent.com/assets/5530305/9015671/4f523ce8-377f-11e5-862a-3383023d7a59.jpg)

**Comment by jywarren** [comment]
I believe this is an instance of https://github.com/publiclab/mapknitter/issues/153

Can you create a new issue over at https://github.com/publiclab/Leaflet.DistortableImage/issues so that we can close this and #153? I'd like to have it well-described because it seems that we are getting more contributions from other coders on the core library, and we should put the worst bugs front and center for folks to tackle. Thanks!!

**Comment by jywarren** [comment]
Created https://github.com/publiclab/Leaflet.DistortableImage/issues/85 to consolidate! Thanks!

**Comment by jywarren** [comment]
I believe this is now solved by @sashadev-sky -- https://github.com/publiclab/Leaflet.DistortableImage/issues/85#issuecomment-474420914 !!! 🎉 

We'll publish the update soon 👍
