### ISSUE TITLE
glitch with scaling, rotating skewing

### ISSUE THREAD

**Issue by patcoyle** [publiclab/mapknitter#196]
Jeff,

I also ran into a different glitch yesterday after the flight described in this note: http://publiclab.org/notes/patcoyle/08-03-2015/mobius-dual-rig-with-non-fish-eye-lens. 

I tried to show him how to use Mapknitter. We started this map http://mapknitter.org/maps/mikesby. However, on his Windows box with Firefox, an uploaded image had the corner dots not located at corners and they didn't function. The image just translated when trying to scale, rotate or distort. Checked today on Chrome, and did not see this issue. However, the distortion issue reported previously still persists.

Pat

**Comment by jywarren** [comment]
Ah, thank you -- if you could post a screenshot or ask him to, that would
be great.

**Comment by patcoyle** [comment]
Thanks Jeff,

I emailed asking about it.

If he provides a screenshot, I'll pass it on.

Pat

**Comment by jywarren** [comment]
From email, it sounds like this was actually in Internet Explorer, unless I misunderstood?

Could you re-file over at https://github.com/publiclab/Leaflet.DistortableImage/ and specify IE if that was the issue? There's an attempt to make it compatible with IE 10 ongoing over there. Thanks!
