### ISSUE TITLE
distortion when scale or rotate

### ISSUE THREAD

**Issue by patcoyle** [publiclab/mapknitter#204]
As shown in attached screenshot have distortion when scale or rotate with Chrome in this instance.
![screen shot 2015-11-21 at 4 47 23 pm](https://cloud.githubusercontent.com/assets/5530305/11321354/55cfa2f0-9070-11e5-8312-c4e4997c9c5b.png)

**Comment by mathewlippincott** [comment]
I'm experiencing the same issue in chrome and the images aren't being scaled down:
https://mapknitter.org/maps/prairie-island-with-base-image#

No distortions have been applied to the right-most image, only rotation:

![screen shot 2016-09-12 at 1 26 06 pm](https://cloud.githubusercontent.com/assets/1203280/18451641/a5a26226-78ec-11e6-9185-56ad207deba6.png)

**Comment by mathewlippincott** [comment]
same issue in Chrome Version 52.0.2743.116 (64-bit), and Firefox 48.0.2 on Mac OS 10.11.6

**Comment by jywarren** [comment]
Created this to consolidate and get help! https://github.com/publiclab/Leaflet.DistortableImage/issues/85 -- thanks!
