### ISSUE TITLE
[website] webserver misconfiguration

### ISSUE THREAD

**Issue by leitasat** [publiclab/mapknitter#205]
http://www.mapknitter.org/ shows default nginx's page. I know, it's not related to the code in repository, but have not found anything else to send a message on the website.

**Comment by jywarren** [comment]
Thanks! @icarito, can you check the www subdomain nginx configuration on
this and on spectralwb?

**Comment by icarito** [comment]
Thanks for reporting! Fixed in both spectralworkbench.org and mapknitter.org

**Comment by icarito** [comment]
I went ahead and fixed mapmill.org too.
