### ISSUE TITLE
auto-add people who use mapknitter to grassrootsmapping@googlegroups.com

### ISSUE THREAD

**Issue by ebarry** [publiclab/mapknitter#207]

**Comment by gauravano** [comment]
Hi @ebarry @jywarren do we still wanted this auto-addition? just confirming as issue is too old, to know about the status. Thanks!

**Comment by ebarry** [comment]
ah, this would have been great two years ago! but perhaps now we need to plan out a website tag subscription for them.

**Comment by gauravano** [comment]
So, can we close this issue?

**Comment by ebarry** [comment]
yes
--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by gauravano** [comment]
Thank you Liz for confirming!
