### ISSUE TITLE
generate /feeds/all from only maps of logged-in users

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#215]
### The problem

Spam maps can sometimes appear on the front page of MapKnitter, since we allow anonymous map creation: https://mapknitter.org
### Proposed fix

We can reduce these incidents (and discourage spammers) by displaying only maps by logged-in users, and doing the same for the https://mapknitter.org/feeds/all RSS feed. This would use the conditional:

```
if logged_in?
```

This has the drawback that anonymous map creators won't get as high visibility. If you can think of a way to reduce spam images while preserving anonymous map visibility, please suggest! (@shaief maybe?). 

Alternatively, perhaps it's good to not promote anonymous maps since they may be using MapKnitter for less public purposes, or not wish attention to be drawn to their maps?

Spam example:

![screenshot 2016-04-04 at 12 22 46 pm](https://cloud.githubusercontent.com/assets/24359/14255004/3291423a-fa60-11e5-87db-33f2e9d35db7.png)

**Comment by Pk13055** [comment]
@jywarren How would I proceed if I wanted to take this up?

**Comment by jywarren** [comment]
Hello, yes -- the feed is generated here: https://github.com/publiclab/mapknitter/blob/master/app/controllers/feeds_controller.rb#L3-L8

I think it's worthwhile to break that up over a few lines, for readability:

```ruby
    @maps = Map.find(:all,:order => "id DESC",:limit => 20, :conditions => {:archived => false, :password => ''},:joins => :warpables, :group => "maps.id")
```

Then, I believe you should be able to use `:joins => :user` -- but I'm not 100% sure. 

This codebase does not have nearly the testing that `plots2` has -- see that there are no unit tests for maps: 

https://github.com/publiclab/mapknitter/blob/master/test/unit/map_test.rb

But you could see if this'd work by creating one that attempted to use a query with `Map.find(:all, :joins => :user)` -- make sense?

**Comment by Pk13055** [comment]
@jywarren I'll get to work on this as soon as I'm back home; I hope this isn't a high-priority issue?
