### ISSUE TITLE
Images do not display in the "Images" tab after upload, requires refresh

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/mapknitter#226]
After uploading images in Mapknitter, they were not accessible from the "images" tab:

![screen shot 2016-09-12 at 1 18 43 pm](https://cloud.githubusercontent.com/assets/1203280/18451408/a0184f2e-78eb-11e6-8c4a-63e5c99ea0cd.png)

I was able to place them from the upload interface, and when I reloaded the page they appeared in the "images" tab.

Chrome Version 52.0.2743.116 (64-bit)
Mac OS 10.11.6

**Comment by sashadev-sky** [comment]
Related to #179 (closed due to duplication) additional notes to investigate from there: 

> - User stated that the need to refresh to see uploads only occurs on 1st image / set of images upload. After that subsequent uploads do appear
> - deleting all images reinitiates the problem
> 
> Browsers: Firefox 38.0.1, Chrome 43.0.2357.81

**Comment by sashadev-sky** [comment]
Also linking to #154

**Comment by sashadev-sky** [comment]
I am closing this issue as a recent one #257  is opened and it's now a duplicate. I will transfer information from the user and linked issues
