### ISSUE TITLE
Not able to move photos

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#237]
### What happened just before the problem occurred
I went to show MK to a workshop group yesterday. I was able to get an image uploaded, but I couldn't move it around. It looks like the circles you would grab on the corners of the pictures aren't pulling the photos.

### PublicLab.org username
Stevie

**Comment by jywarren** [comment]
Hi, can you add a link to the map so I can try it out?

**Comment by steviepubliclab** [comment]
Hi Jeff,
It looks like my last map didn't save where I tried to do this. I've built
out a new one to try to replicate the problem, and it didn't happen this
time, so I'm not sure. Here's my test map that didn't have the problem:
https://mapknitter.org/maps/bayou-sauvage-test-upload

-SL

**Comment by jywarren** [comment]
Hmm, if you could try and reproduce the issue again we can try to narrow
things down, but for now there's not a lot we can do. Could it have been on
a not logged in computer, a different web browser, or some other thing that
was different?

**Comment by jywarren** [comment]
Closing, but if you see this again please reopen! Thanks!
