### ISSUE TITLE
Make "maps by region" readable in JSON API

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#251]
This action allows listing maps by region:

https://github.com/publiclab/mapknitter/blob/61e803579d90868ebb9168267348f92e62759bb3/app/controllers/maps_controller.rb#L169-L176

Example:

https://mapknitter.org/map/region/Gulf-Coast?minlon=-98.8&minlat=23.6&maxlon=-79.1&maxlat=31.8

We should add something like this line to make it respond to JSON queries too - that way we can display maps on external sites by region:

https://github.com/publiclab/mapknitter/blob/61e803579d90868ebb9168267348f92e62759bb3/app/controllers/maps_controller.rb#L197

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren 😄 !
We have to add `format.json  { } ` only in `region` action of maps_controller ?
And link in the example above is not working . 
Thanks !

**Comment by jywarren** [comment]
Completed by @sagarpreet-chadha !!! 

https://mapknitter.org/map/region/Gulf-Coast.json?minlon=-98.8&minlat=23.6&maxlon=-79.1&maxlat=31.8

Could use a test maybe, but looking great!
