### ISSUE TITLE
Add "flag as spam" button

### ISSUE THREAD

**Issue by ebarry** [publiclab/mapknitter#253]
This issue is broken out from https://github.com/publiclab/mapknitter/issues/252

### What happened just before the problem occurred

Add a "flag as spam" button to all maps that all logged-in viewers can see, regardless if they are an admin or not. 

This button should trigger a notification to the moderators group, worded something like "[person X] identified [this content](link to content) by [this person](link to person's mapknitter account PR to publiclab.org account????) as potentially being spam. Please review, thanks! If it is spam, please spam the content and ban the account"

If the content is not spam, what action to moderators need to take to remove the "flag" on this content? Something to figure out. 

### Relevant URLs

mapknitter.org

**Comment by jywarren** [comment]
Code location to insert this link is here - would be a great first-timers issue!

https://github.com/publiclab/mapknitter/blob/61e803579d90868ebb9168267348f92e62759bb3/app/views/maps/_list.html.erb#L21

So we could insert this above that line:

```
<a rel="tooltip" title="Flag as spam." class="btn btn-sm btn-default" href="mailto:moderators@publiclab.org?subject=Reporting+spam+on+MapKnitter&body=Hi,+I+found+this+map+that+looks+like+spam+or+needs+to+be+moderated:++http://mapknitter.org/maps/<%= map.slug %>+by+http://mapknitter.org/profile/<%= map.user.login %>+Thanks!">
  <i class="far fa-flag"></i>
</a>
```

**Comment by slippa91** [comment]
I would like to work on this issue. I am a "first-timer".

**Comment by jywarren** [comment]
Complete in #254! Thank you @slippa91 and also @ebarry !!

**Comment by jywarren** [comment]
We'd love to have a chance to work more with you! Do check out issues over at --

 https://publiclab.github.io/community-toolbox/#r=all
