### ISSUE TITLE
Process queue to offload ImageMagick

### ISSUE THREAD

**Issue by icarito** [publiclab/mapknitter#258]
This is a note that in production we're seeing large images (I observed upwards of 15000x15000 if I believe `htop`) - causing `convert` to take a huge time and RAM and bringing the app down.

Benjamin Sugar suggested offloading to a process queue of some sort. I a not familiar with it but I think Redis is popular.

It'd be nice to not worry about this kind of downtime.
Thanks!

**Comment by icarito** [comment]
Note that alternative or interim measures to better contain ImageMagick are appreciated. Currently we use /etc/ImageMagick-6/policy.xml to limit resource usage. But I think the problem occurs because we run several processes at once.

I've further throttled to 25% cpu load and added a 2GB RAM limit per process:

```
  <policy domain="resource" name="thread" value="1"/>
  <policy domain="resource" name="throttle" value="30"/>
  <policy domain="resource" name="memory" value="2GiB"/>
```

I hope it will hold for now.

**Comment by jywarren** [comment]
I believe we can encourage people to download images one by one using this
issue: https://github.com/publiclab/Leaflet.DistortableImage/issues/83

But if we can also further modularize this code, we could come up with a
way to "send" this to another application, potentially?

https://github.com/publiclab/mapknitter/blob/master/app/models/map.rb#L204

Perhaps we could modularize this operation which runs on all images in the
map:
https://github.com/publiclab/mapknitter/blob/master/app/models/map.rb#L282-L302

The code run on each image is 117 lines long, even before it attempts to
join the images together:
https://github.com/publiclab/mapknitter/blob/master/app/models/warpable.rb#L153

That code could potentially be reworked.

However, all of this is pretty astoundingly heavy, and dense code.

**Comment by icarito** [comment]
I think if we could put outside processes in a queue and only run a few
at a time it could work. Perhaps there's a way to transparently offload
the ImageMagick commands themselves... e.g. replace those scripts with
`ssh somootherserver convert` and have both servers mount the same
shared directory, for instance.

**Comment by jywarren** [comment]
is it important that it be a separate server? I think that initially we
could try to make parts of this process asynchronous, or even to just not
run too many at once? A close read of the code may show that everything is
actually synchronous right now and that making it asynchronous without
queueing could actually be a problem.

Also note that there are both ImageMagick commands and GDAL commands. Coudl
be worth checking if we need to cage the GDAL commands too?

**Comment by icarito** [comment]
No it's not necessary to run it separately, it was just and idea to deal
with it from the system level rather than the code level.

Actually I've also read some options are possible to make a queue in the
command line with a wrapper script. That is also an option if code
itself is complex!

**Comment by jywarren** [comment]
I'm wondering if we could create a Google Cloud mini app that includes `imagemagick`, `gdal`, and some Ruby, to offload key portions of this into a cloud-based queue. 

We're also looking at how to implement this in JavaScript, but I want to be thorough and explore both means. And JavaScript won't be able to generate GeoTiffs and map tiles the way GDAL will. 

Maybe starting with this? https://github.com/geo-data/gdal-docker

Then installing imagemagick on a variant of that, and Ruby? 

Maybe we could integrate it with this? https://github.com/googleapis/google-cloud-ruby

**Comment by jywarren** [comment]
Merging into #296 and #298!
