### ISSUE TITLE
embedding maps with annotations

### ISSUE THREAD

**Issue by fiestin** [publiclab/mapknitter#26]
I am trying to embed the map-knitter preview with the annotation tool.
I am also looking for a more simple way to embed the web viewer of the map (like the map-knitter preview) to the website, overlaid on GoogleMaps or OSM.
there two problems - when i press the web viewer button here: http://mapknitter.org/map/view/vadi-asbestonim , the page never loads, and when I try the open layers button, the page loads but the map is blank, this happens with other maps as well.
last thing - There is spam and a change of location in some maps - what can I do to change it? http://mapknitter.org/map/view/beit-safafa

**Comment by jywarren** [comment]
believe this is all fixed now!
