### ISSUE TITLE
keyboard command to delete image

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#262]
I've had the problem multiple times where I'm running a workshop, or just trying to work in MK and we can't get the toolbar to show up. I can usually work around the with the commands, but there isn't a command for deleting an image which always seems to be a problem. Can we make one?

**Comment by jywarren** [comment]
Hi, thanks! I'm going to move this over to https://github.com/publiclab/Leaflet.DistortableImage/issues/98 where we can solve it -- it's part of the DistortableImage library. Thank you!!!
