### ISSUE TITLE
latest leaflet map not showing map markers

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#271]
Hi, @sagarpreet-chadha -- just updated https://mapknitter.org/ and no longer seeing the map markers, although I am seeing the new layers 🎉 

I wonder if we missed something simple? 

https://mapknitter.org/#3/45.46/1.93

https://mapknitter.org/

Thanks!

**Comment by sagarpreet-chadha** [comment]
Okay 👍 ! On it !

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren !
We want mapknitter markers to be default markers , right ?
AND do we need to give menu option to remove mapknitter layer ?

**Comment by jywarren** [comment]
Saw your PR - i think that's perfect!

**Comment by sagarpreet-chadha** [comment]
🎉
