### ISSUE TITLE
<1cm/px maps fail to export; rounding problem

### ISSUE THREAD

**Issue by patcoyle** [publiclab/mapknitter#28]
As noted in email:
Thanks Jeff. Interesting issues in results from this try:
http://mapknitter.org/map/view/livermore-ca-test-with-pl-mobius-infragram-point-and-shoot-on-parrot-ar-drone-2-0
Exports as jpeg and webviewer seem null or empty.
Edit map initially shows locked set of images as displaced, but seem to line up if pan in the editable map window.
All, may be function of the very low altitude images. Can't zoom in more to place them better. I'll note this in GetHub, but may just be due to this extreme case.

**Comment by jywarren** [comment]
Believe this is fixed now.
