### ISSUE TITLE
Map listing gets messy when images don't fit nicely into a grid

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#280]
We have this nice way of showing a grid of maps at mapknitter.org:

![image](https://user-images.githubusercontent.com/24359/47318944-6a426f80-d61b-11e8-981c-15489debf353.png)

However, as you can see, when the items are oddly shaped, they collide and pile up. They should be in a tidy grid like this:

![image](https://user-images.githubusercontent.com/24359/47318974-7fb79980-d61b-11e8-9527-3b8e7a4b46a3.png)

The HTML for this region is driven from here:

https://github.com/publiclab/mapknitter/blob/main/app/views/map/_list.html.erb

I believe some CSS could be used to make these work, OR potentially inserting an `<hr />` every 4 items?

**Comment by jywarren** [comment]
This has been added to the GCI dashboard!

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by divyabaid16** [comment]
I think this issue has been fixed now.
Thanks!
