### ISSUE TITLE
Collecting resources for MapKnitterExporter.js

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#296]
We are exploring parallel tracks for cloud-based MapKnitter exporting, and one option is a JavaScript based process. The base idea is to use Image Sequencer, possibly webgl-distort, and to run in Google Cloud. 

A more traditional Ruby/ImageMagick/GDAL approach is being explored here: https://github.com/publiclab/mapknitter/issues/258

Basic version would output a combined JPG image at a given scale or pixel size. Advanced versions might cut tiles or output GeoTiffs.

## Code to be moved off-app

* https://github.com/publiclab/mapknitter/blob/main/app/models/warpable.rb#L153-L336
    * `generate_perspectival_distort`
* https://github.com/publiclab/mapknitter/blob/main/app/models/map.rb#L231
    * `run_export`, `distort_warpables`, `generate_composite_tiff`, `generate_tiles`, `generate_jpg`

## Resources

* https://github.com/geotiffjs/geotiff.js/#writing-geotiffs-beta-version - geotiff writing in JS
* https://github.com/ddohler/gdal-js/tree/develop-js/examples/tile_tiff - cut tiles in JS with transpiled GDAL.js

## Non-JS wrappers

* https://www.npmjs.com/package/imagemagick
* https://github.com/naturalatlas/node-gdal - operate GDAL via JS

* https://github.com/geo-data/gdal-docker
* https://github.com/googleapis/google-cloud-ruby

* https://cloud.google.com/ruby/rails/
* https://cloud.google.com/appengine/docs/flexible/ruby/

**Comment by jywarren** [comment]
@tech4gt starting to collect resources!!!

**Comment by tech4GT** [comment]
Oh this is great! Also maybe we can schedule a call to discuss this a little more, I still need to wrap my head around it exactly but this looks very promising! :)

**Comment by jywarren** [comment]
For sure!!!

On Jan 12, 2019 1:11 AM, "Varun Gupta" <notifications@github.com> wrote:

Oh this is great! Also maybe we can schedule a call to discuss this a
little more, I still need to wrap my head around it exactly but this looks
very promising! :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/publiclab/mapknitter/issues/296#issuecomment-453723105>,
or mute the thread

**Comment by jywarren** [comment]
OK, updated in #298 with a more fleshed out architecture plan.

**Comment by icarito** [comment]
Just a note that Google Cloud Engine has Standard Environment and Flexible Environment and Ruby seems to only be supported on Flexible Environment which is significantly more expensive: https://cloud.google.com/appengine/docs/standard/appengine-generation

**Comment by jywarren** [comment]
https://serverless.com/blog/api-ruby-serverless-framework/

https://www.serverless-ruby.org/

**Comment by tech4GT** [comment]
Wow npmjs.com/geotiff is seriously amazing work!

**Comment by jywarren** [comment]
Closing this now in favor of https://github.com/publiclab/image-sequencer-app/
