### ISSUE TITLE
[Discussion] : Login Project

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#301]
Following problems observed:
* No proper login/signup for the website. Relies on pl.org for activity
* Improper usernames are not entertained with flash messages
* User who has given access to mapknitter once has to give it whenever they login
* Sign up mapknitter basic+alternative flow missing
* OAuth missing
* email does not work instead of username
* Clicking No option on pl.org enables the user to be logged in
* error while user is not logged in at pl.org and tries to login to the mapknitter
* if we are using third party(pl.org here) authentication at mapknitter it should redirect to the same page
* also, opening up of pl.org should be in a new tab

Refer #300.
What do you suggest @jywarren?

**Comment by SidharthBansal** [comment]
There are 2 functionalities:
* Mapknitter should have its own authentication system
* Mapknitter will use Pl.org authentication system
Currently it is improperly implemented. In which direction we have to move?

**Comment by SidharthBansal** [comment]
@jywarren @gauravano are there users who use pl but not mapknitter and users which use mapknitter but not pl.org?
This question can tell us whether we want both projects( + integration project for both )or single project(one of above).

**Comment by IshaGupta18** [comment]
Once @jywarren @gauravano suggest what to do... I could take this one up! If we begin to make a login system as good as plots2 from scratch, don't you think that it will be a big project @SidharthBansal ?

**Comment by SidharthBansal** [comment]
There are multiple choices. I also want to work on this. Let's wait for
Jeff reply.

**Comment by IshaGupta18** [comment]
Oh okay, so we'll somehow be taking help from plots, that would be great too!

**Comment by SidharthBansal** [comment]
@jywarren I think adding roles to the user profile from the plots2 is part of this issue. 
Copying from your comment in other discussion
>> Some notes on this that relate to other parts of the system:
* [ ] see if we can read `roles` from plots2 user records, ideally through a `User.role` call that somehow grabs the data from plots2

**Comment by jywarren** [comment]
Sorry, just going through this all in detail now! 

> @jywarren @gauravano are there users who use pl but not mapknitter and users which use mapknitter but not pl.org?

No, all MK users have a PL account -- because...

So one thing is that we gain a lot by relying on PL.org's user accounts -- we don't currently need to store any passwords or secrets in MK because we rely on PL.org for a lot of that infrastructure. So, I think I'm still leaning towards `* Mapknitter will use Pl.org authentication system` -- but happy to debate pros/cons a bit!

> OAuth missing

In theory we could port the connection over so that we use OAuth instead of OpenID, but at this point I don't feel like it gets us much. We can take advantage of the OAuth login more directly though, maybe by somehow displaying the PL.org login modal on MapKnitter.org? Is that possible, or can we think about how you could click "login with Google" but really get logged into PL.org, then redirected back to MK?

> * User who has given access to mapknitter once has to give it whenever they login

Yes, we could def. try to "remember" access being granted!!! Great idea. 

All the rest i agree with -- great!

**Comment by jywarren** [comment]
Yes, and related to reading roles from PL.org, could we read moderation status from there as well?

**Comment by jywarren** [comment]
Via an API call, maybe???

**Comment by SidharthBansal** [comment]
Thanks Jeff for suggesting to use plots2 authentication system only at MK without constructing MK own login/signup system.
I am searching for API call. Users will be the same, so trying to find a suitable way.

**Comment by SidharthBansal** [comment]
We are basically trying to do **Cross Domain Authentication In Rails.** 
https://www.srijan.net/blog/ruby-rails-sign-across-multiple-applications
Searching this stuff

**Comment by SidharthBansal** [comment]
@jywarren I have couple of questions in my mind:
1. Do we have separate database of Plots2 ? I assume if we have database of
plots2 separated from the main application then we can use the USERS data
from it at MK too after constructing rails logics. We will not have to copy
and paste stuff.
2. What all applications are like MK in terms of authentication?
What if we try to create same authentication model for all applications.
If there will be large number of applications in Rails then Cross Domain
Authentication System is useful.
3. We will require both the users and user tag tables for MK from plots2 as
the identity model is created from usertag model for OAuth providers at
GSoC time. Do we need to consider any other table? Roles are present in
users and identity in user tags.
4. Will there be any problem if all the applications are logged in/logged
out simultaneously? OR do we need separate applications to be logged in and
out separately?
5. Assuming Login can be handled from plots2 for MK. Let's now think for
Sign up. Suppose you are a newbie. Will you land to PublicLab.org first OR
will you land to MK first? How many chances are there of a new used willing
to come to MK without using Pl? In case it's rare then we can rely on
plots2 completely.


I want to make Authentication model highly generic so that we will have 2-3
lines of code if we want to add/subtract new repositories. (Similar to
multi tag subscription and OAuth). Above questions are really helpful in
deciding our approach.

**Comment by SidharthBansal** [comment]
Advantages of Cross Domain Authentication (in other words drawbacks of
creation of separate authentication system for MK)
- No need to recreate basic login/sign up model for MK
- No need to integrate providers
- No need to worry in case we are adding/subtracting any provider at any
one place to change it at all placed
- No need of creation of duplicate user and user tag database model.
- seamless user experience as user once logs in any app of pl then user is
free to use any app
- deletion of pl accounts which is to be created for plots2 will have n*x
burden where n is no of applications and x is amount of effort for making
deletion account feature
- Creation of redundant mailer system -- welcome emails, forget password
emails etc.

**Comment by SidharthBansal** [comment]
Let's see one similar website online.codingblocks.com
It has an Authentication model like plots2:
![image](https://user-images.githubusercontent.com/20972099/53476479-81e1a700-3a98-11e9-8eba-334389ed9efa.png)
I logged in to the website by any means. Then in the profile section, I have the following:
![image](https://user-images.githubusercontent.com/20972099/53476575-b5bccc80-3a98-11e9-84bb-bfbb07fc1d37.png)

like we have pl.org/profile/username
Key feature under profile section is this page
![image](https://user-images.githubusercontent.com/20972099/53476601-cd945080-3a98-11e9-8140-4ea75f5dcabd.png)
A striking feature is the connection of many websites belonging to company codingblocks, see this page
![image](https://user-images.githubusercontent.com/20972099/53476759-295ed980-3a99-11e9-88f2-a8fa137ea8f8.png)
I am trying to think in these terms. If we can find some good resources for similar RoR model explanation.

**Comment by SidharthBansal** [comment]
I am not able to find a single advantage for creating MK's own Authentication model. In case we will create one such model then we need to integrate with the plots2 model as many existing users of the pl.org has written many things on MK. So, that will just increase our burden today and more in future. If you are able to find advantages of independent auth model for MK then please tell @jywarren .
Apologies. I tried for 3 hours. All points suggest Cross Domain Authentication. Let us call it CDA in short for convenience.

**Comment by SidharthBansal** [comment]
We will be using CORS(Cross Origin Resource Sharing) understanding http://www.blog.bdauria.com/?p=427

**Comment by SidharthBansal** [comment]
>> We can take advantage of the OAuth login more directly though, maybe by somehow displaying the PL.org login modal on MapKnitter.org? Is that possible, or can we think about how you could click "login with Google" but really get logged into PL.org, then redirected back to MK?

For the OAuth providers we are using the user tags and for the login/sign up form + roles we are using the user model. So, we will be requiring both the models for sure.
This is a really IMMENSE project for me. Will have much more test cases, corner cases and other stuff then we had the last yr in GSoC. 

I have listed all the activities which are compulsory in #362.

**Comment by jywarren** [comment]
> I am not able to find a single advantage for creating MK's own Authentication model

I think i agree with this. Maybe the only one I could think of is that it's easier to manage things like user role, status, etc without having to reference another Rails app remotely. But we basically need to and it'd be even worse to try to manage two parallel systems. 

> Cross Domain Authentication In Rails

Yeah, i mean actually we already have it - the only missing parts seem to be:

1. that we can't yet access user record state in PL from within MK
2. that we can't yet initiate a "login with Twitter (oauth)" sequence (using PL's Oauth, not a new system)
3.  that we don't "remember" PL users approving OpenID permission being given to MK, so we have to ask each time

Is that right? I think that if so, the project could be smaller in scope than we thought. 

For (1), we could set up a JSON API endpoint (or use an existing one?) in plots2 to read status and role, which aren't private data anyways. We would want to store that in the session so we don't have to keep fetching it, but we'd have to think about when to flush it. We should just consider when for security reasons we should re-check status. Maybe this means we really have to check every 5 minutes or something...? Or just each time (that'd be pretty slow, though only for actions which require a specific role or status)

Oh, one more - mailers. Do we really need them? Noting in #362 that we can rely on PublicLab.org for much of this. We do have minimal mailers in MK already. Don't know if we need to do a lot more just yet.

**Comment by SidharthBansal** [comment]
>>i mean actually we already have it

Oh great. We basically need to modify openid then it is a much simpler task than I thought. 

>>  that we can't yet initiate a "login with Twitter (oauth)" sequence (using PL's Oauth, not a new system)

I think we can. I tried it. It is working. There are many problems with the handling of corner cases but the core CDAS is working. I logged into the MK by making account into plots2 through twitter and it works. But user experience was really bad.

**Comment by jywarren** [comment]
haha "really bad" indeed -- i just left a step-by-step in the other issue
highlighting the multiple clicks required by a user. Agreed. But also left
a suggestion for how to simplify it. I'm glad it seems simpler now but that
also means we could work to really smooth it out in the details and corner
cases. Great thinking! OK, let's keep refining the project and we'll soon
have a final plan.

**Comment by SidharthBansal** [comment]
@jywarren can you please open up this issue in a window and see. I have heavily edited this issue to make it modular so that we can manage things easily.

**Comment by SidharthBansal** [comment]
I know you are messaging me from your mobile. As this issue is edited from top to bottom, I am unable to understand your comment.
I edit it so that we can organise things in a better way.

**Comment by jywarren** [comment]
Oops! Ok, i will do so soon, but have a few deadlines today first. Thank
you!

**Comment by SidharthBansal** [comment]
No problem. You can comment in the other issues in the meantime. Thanks.

**Comment by jywarren** [comment]
OK cool - yes, i was just referring to this comment of mine: https://github.com/publiclab/mapknitter/issues/362#issuecomment-468707523

where I am proposing auto-approving OpenID requests from our own sites (MapKnitter, SpectralWorkbench), which would simplify things a lot - it'd remove the need for a management system (https://github.com/publiclab/mapknitter/issues/365) and remove a step in the UI, addressing your `But user experience was really bad.` comment. Make sense? Thanks Sidharth!!!

**Comment by SidharthBansal** [comment]
Yeah thanks

**Comment by SidharthBansal** [comment]
Moved to #301

**Comment by SidharthBansal** [comment]
Issue is properly broken up into smaller issues to be solved. Hence closed it.
