### ISSUE TITLE
Planning issue: expand test coverage with more thorough testing

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#304]
Mapknitter repository requires a lot of unit tests, integration tests, fixtures and functional tests for each MVC pattern present in the repo along with routes explorations.
So @jywarren we can discuss testing in this issue.
Refer #300

**Comment by jywarren** [comment]
I think for the unit and functional tests, the process could be:

* look at the source file (in `/app/models/` or `/app/controllers/`)
* identify a method that does not have a corresponding test in `/test/unit/` (for models) or `/test/functional/` (for controllers)
* create a test following the example of existing tests
* add a basic assertion -- `assert_response :success` for functional tests, or `assert_not_nil Map.last.function` for a unit test (where `map` is the name of the model and `function` is the name of the function you want to test. Some may require parameters!

How does this sound? This can get us a long way there. 

## Coverage tracking

We could also add a coverage badge using Coveralls or another service, like CodeClimate. 

CodeClimate actually gives MapKnitter a decent score! 

https://codeclimate.com/github/publiclab/mapknitter

Code "smells": https://codeclimate.com/github/publiclab/mapknitter/issues?category=complexity&engine_name%5B%5D=structure&engine_name%5B%5D=duplication

**Comment by jywarren** [comment]
Just chiming in that this ended up being a really good self contained update which built out node, warpable fixtures and added decent warpable unit tests! It's a good reference for further work of this kind. 

https://github.com/publiclab/mapknitter/pull/331/files

**Comment by jywarren** [comment]
https://coveralls.io/github/publiclab/mapknitter working!!!! Thanks @kaunair !!!

**Comment by jywarren** [comment]
Lots of progress to be made here... many areas are very low coverage, esp. controllers!

**Comment by kaunair** [comment]
Do we intend to change our testing framework to RSpec?
If we want to do it I think now is the best time - before our test suite becomes too large to migrate
Thoughts? @jywarren
