### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by rexagod** [publiclab/mapknitter#314]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/PublicLab.Editor/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update:** Add a `CODE_OF_CONDUCT.md` to this repository by referencing the document found [here](https://github.com/publiclab/PublicLab.Editor/blob/master/CODE_OF_CONDUCT.md) and submitting the same in your PR.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there.

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to **link to this issue by mentioning the issue # in your pull request**, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by Yugandhartripathi** [comment]
I would like to work on this.

**Comment by jywarren** [comment]
Those are specific to in-person events that need not bear on this copy,
thanks! Although it's interesting to note that by making copies we will
need to watch for any changes to the original and keep this up to date.
Thanks!!

**Comment by Yugandhartripathi** [comment]
@jywarren making copies already led to the duplication of the following in code of conduct files of all repos of this org.
![image](https://user-images.githubusercontent.com/32102845/51924324-d569c200-2412-11e9-9bd4-50dc8d83531e.png)
I opened a PR(#4724) for plots2 initially thinking it's unique case then I saw the same in imagesequencer and opened a first timer issue(#727) there for others looking to contribute.
What should be done for other repos?

**Comment by jywarren** [comment]
It's such a small set of changes maybe once this is complete we can just
quickly copy this one over all the rest. Thanks for your help!!!!

**Comment by divyabaid16** [comment]
I think this can be worked upon now.
Reference can be taken from https://github.com/publiclab/plots2/blob/master/CODE_OF_CONDUCT.md
Thanks!

**Comment by rexagod** [comment]
Closed in favor of #826.
