### ISSUE TITLE
error in  legacy editor

### ISSUE THREAD

**Issue by avsingh999** [publiclab/mapknitter#315]
### What happened just before the problem occurred
when click on legacy editor then showing this error
![mapkinter](https://user-images.githubusercontent.com/25536022/51841366-79c90700-2334-11e9-9be2-10d7e2883df1.png)

### Relevant URLs

https://mapknitter.org/maps/beer?legacy=true

### PublicLab.org username
singhav
(to help reproduce the issue)

### Browser, version, and operating system
chrome ubuntu 18.04

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by jywarren** [comment]
I think we should probably move towards deprecating the legacy editor. It's
been some years since we moved to the new one. Thank for reporting!

**Comment by jywarren** [comment]
We'd love to have your help in writing tests however! #304
