### ISSUE TITLE
Correct README.md

### ISSUE THREAD

**Issue by rexagod** [publiclab/mapknitter#322]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: There is currently a spelling error in the [`README`](https://github.com/publiclab/mapknitter/blob/main/README.md#installation) file's third point. Replace "databse" with "database", and then submit your first PR. Also have a look around this repository since we have many interesting issues for you to solve!

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by Chansamnang** [comment]
Can I take this?

**Comment by jywarren** [comment]
Yes please!

**Comment by marieram** [comment]
Has this been started? @Chansamnang

**Comment by ctam853** [comment]
Hello, 
I'm new to open source projects and I'd love to join this project.

**Comment by HarshCic** [comment]
Hi @rexagod, I had just found that the databse error on your repository is not resolved at. I'm submitting a PR in regard of this can you please help me by checking that PR and it would be great if you can able to merge that PR.

**Comment by gauravano** [comment]
Hi @HarshCic, you should ask in the issue (here) first before opening the PR so as to get update regarding the issue status. Also, before you, @marieram  and @ctam853 have shown interest in solving the issue, so if the issue has no PR, they should get the chance to take a dig at issue. But, as the issue is just a typo solving and your first PR at Public Lab, we will accept the PR. Please take a note that it's an essential part of our community to claim issue first and then open the PR, so as to not do redundant work and respecting other contributors interest. Thanks!

**Comment by gauravano** [comment]
Hi @marieram and @ctam853, sorry but this issue is solved in #335. You can find more FTO issues at https://code.publiclab.org/#r=all and in case, you don't see any unclaimed issue there, feel free to comment below, I will open issue for both of you. Thanks!

**Comment by HarshCic** [comment]
Hi @gauravano, I understand the community guidelines but I too thought the same as it is just a typo and no one resolve it till then and it is my first PR with publiclab as well which makes me somewhat excited.. but absolutely I will take care from next time. Sorry, @marieram and @ctam853.

**Comment by marieram** [comment]
Hi @gauravano! Thank you for getting back to me. I currently do not see any unclaimed issues. If there are any first-timers-only or documentation issues available, please send them my way. Thanks again. 

> Hi @marieram and @ctam853, sorry but this issue is solved in #335. You can find more FTO issues at https://code.publiclab.org/#r=all and in case, you don't see any unclaimed issue there, feel free to comment below, I will open issue for both of you. Thanks!

**Comment by gauravano** [comment]
@marieram I will surely mention you, whenever I see one open or I'll open a new issue whenever I get a chance. Thanks!

**Comment by gauravano** [comment]
Hi @marieram and @ctam853, I have created FTO's for both of you, find them at https://github.com/publiclab/plots2/issues/4820 and https://github.com/publiclab/plots2/issues/4819 . I have mentioned both of you in a issue. Please comment there to acknowledge your claim. Thanks!

**Comment by Knightrv** [comment]
Can I take this issue as I am a beginner to open source and fixing this issue will boost my confidence.

**Comment by gauravano** [comment]
The issue is already solved in #335 so please find another issue to work on. You can find more issues at https://code.publiclab.org/#r=all and if you can't find any unclaimed issue there, please feel free to comment below. Thanks!

**Comment by Anjalikamath** [comment]
Hi.I want to contribute to this project,but I am new to this and have little idea how this works.

**Comment by gauravano** [comment]
Hi @Anjalikamath, this issue is already resolved and closed. You can find more issues to work at https://code.publiclab.org/#r=all, if you don't see any unclaimed FTO there, feel free to comment here and we'll try to create one for you. 

Thank you!
