### ISSUE TITLE
Allow uploading of Images only

### ISSUE THREAD

**Issue by gauravano** [publiclab/mapknitter#329]
Although, the goal of Mapknitter is clear that images should be uploaded to make the map but for to take care of our database and spam, we should limit uploading of only images. 

I tried uploading mp4 file and to surprise no error was thrown. So, we need to fix the accept type of file.

Thanks!

**Comment by IshaGupta18** [comment]
I think changing this line:

https://github.com/publiclab/mapknitter/blob/de156283193542b10607542db5544ae400cf48bc/app/views/images/_new.html.erb#L19

to this line is doing the trick:

`<i class="fa fa-plus-circle"></i> Select images <input id="warpable_uploaded_data" name="warpable[uploaded_data]" type="file" accept="image/*" />`

Only image file options will be displayed from the user's file system:

![image](https://user-images.githubusercontent.com/40794215/52564211-9469a880-2e29-11e9-8761-05e56f7c2bc7.png)

Should I make a PR for this @gauravano @jywarren ?

**Comment by gauravano** [comment]
Hi @IshaGupta18, you have surely solved the issue. You can raise a PR or open a first-timer-issue too, however you like. Thanks :smiley:

**Comment by IshaGupta18** [comment]
I would love to open an FTO! Thanks a lot @gauravano !

**Comment by IshaGupta18** [comment]
Hey @gauravano I have created FTO #338 however I don't have the privileges I haave in plots2, like adding labels. Could you please grant me those privileges here as well or add fto label to it? Thanks a lot!

**Comment by gauravano** [comment]
Thank you so much @IshaGupta18! I checked but I am not privileged to give you write permission required to add labels to the repo. But, let's ask @jywarren. For now, I am labeling the issue. Thanks!

**Comment by gauravano** [comment]
Closing this one as FTO opened at #338. Thanks!
