### ISSUE TITLE
Provide image URLs for map JSON results

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#346]
Our API currently shows:

https://mapknitter.org/map/region/Gulf-Coast.json?minlon=-98.8&minlat=23.6&maxlon=-79.1&maxlat=31.8

Which just converts map records to json directly, and results in them having a lot of not very useful content that's not readable; the `body` attribute especially. 

We should remove `body` and instead include an `imageUrl` parameter, by appending it like we do here:

https://github.com/publiclab/mapknitter/blob/bf0b34068181aae0dc29bd98c74f8ac75aa14a46/app/controllers/maps_controller.rb#L146-L157

This would let us display an image in the popup on the Leaflet map in Leaflet Environmental Layers: https://github.com/publiclab/leaflet-environmental-layers/issues/112

**Comment by kaunair** [comment]
Hey I'd like to take this issue!
If i understand it correctly, you want to display only the image urls for all warpables in each map right?

**Comment by jywarren** [comment]
Yes! As an attribute alongside other map data. We can just use the url of
the first returned image for the map and not provide the attribute if there
aren't any!
