### ISSUE TITLE
[WIP]Planning Issue : Cross Domain Authentication (CDA) Platform for PL

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#362]
# List of Requirements:

- Decide variables to be stored in session #369

- All the conditions which were applied to https://publiclab.org/notes/bansal_sidharth2996/02-20-2018/gsoc-proposal-oauth-authentication (OAuth GSoC project) single provider needs to be applied to the plots2 api. We again have to consider all the corner cases where our system may crash before implementing the code. 

#### Basic Flows:
1. Signup at MK through plots2
   MK account is created and linked to the plots2 account for all the following cases:
   1.1 4 OAuth Providers 
   1.2 SignUp form
2. Login through PL at MK if plots2 is not already logged in
  2.1 Plots2 has linked MK
  2.2 Plots2 has not linked MK
3. Login through PL at MK if plots2 is logged in
  3.1 Plots2 has linked MK
  3.2 Plots2 has not linked MK
4. Logout through MK results in only logging out of MK
5. Logout through plots2 results in logout from all apps??(or any other suggestions??)

### Alternative Flows:
1. SignUp error validation messages should work properly
2. Login error validation messages should work properly

## Frontend
 See #365 for discussion. 

## Test Coverage
 See #372 for discussion

Refer #301 for the discussion.

**Comment by SidharthBansal** [comment]
- All the conditions which were applied to https://publiclab.org/notes/bansal_sidharth2996/02-20-2018/gsoc-proposal-oauth-authentication (OAuth GSoC project) single provider needs to be applied to the plots2 api.
I mean Plots2 will behave as a provider to the MK. So all the conditions which we applied last year for facebook provider to the plots2 are analogous to plots2 api call for authentication to the MK. So, whole last year project needs to be reapplied at a larger and wider scale.
- We again have to consider all the corner cases where our system may crash before implementing the code. All last year GSoC conditions + many others as apps are interlinked
- Creation of a demo application and link/unlink that app to the plots2 before applying it to the MK
- (Future attempt) link all similar RoR apps to plots like MK.

**Comment by SidharthBansal** [comment]
@jywarren feel free to add other remaining requirements by editing issue's body.
Thanks

**Comment by jywarren** [comment]
Noting here that if we rely on Plots2 auth system, we can leave off Welcome Email, Password Reset, & Email/Account Verification, as we'll just let those happen in plots2! 

Likewise, `Creation of intermediate gateway frontend for MK to login to pl. Present page has no validation errors, forget password options etc.` for this can we also just entirely rely on the plots2 login system with nothing extra required for MK?

For linking user tags, I am not sure we need to - if PL's current system allows login to MK, MK doesn't need to know about user tags, right?

> all 4 OAuth providers at pl.org

Here, I think we can probably just use the current OAuth links, like:

https://publiclab.org/auth/github?origin=https://publiclab.org/

We can probably generate the correct OpenID auth URL too; i wonder... when you enter your username at MK, you get something like:

`https://publiclab.org/openid?openid.claimed_id=https%3A%2F%2Fpubliclab.org%2Fopenid%2Fwarren&openid.identity=https%3A%2F%2Fpubliclab.org%2Fopenid%2Fwarren&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.realm=https%3A%2F%2Fmapknitter.org&openid.return_to=https%3A%2F%2Fmapknitter.org%2Fsessions%2Fcreate%3Fauthenticity_token%3Df%252F1DBQMxfNXIAtKn7Fhan6ABt4GNL1iEHkn6PnDLRj4%253D%26back_to%3D%252F%26open_id%3Dwarren%26commit%3DLog%2Bin&openid.sreg.required=nickname%2Cemail`

Could we do:

https://publiclab.org/auth/github?origin=https://publiclab.org/openid?openid.claimed_id=https%3A%2F%2Fpubliclab.org%2Fopenid%2Fwarren&openid.identity=https%3A%2F%2Fpubliclab.org%2Fopenid%2Fwarren&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.realm=https%3A%2F%2Fmapknitter.org&openid.return_to=https%3A%2F%2Fmapknitter.org%2Fsessions%2Fcreate%3Fauthenticity_token%3Df%252F1DBQMxfNXIAtKn7Fhan6ABt4GNL1iEHkn6PnDLRj4%253D%26back_to%3D%252F%26open_id%3Dwarren%26commit%3DLog%2Bin&openid.sreg.required=nickname%2Cemail

No, there's an error:

![image](https://user-images.githubusercontent.com/24359/53600877-b0cf4a00-3b78-11e9-80cc-ef2ced0a63d4.png)

However, something like that could likely work; we could then just show the OAuth icons as links on MapKnitter, and with the appropriate OpenID URL we could then get directed through PublicLab.org for authentication. Perhaps what needs to happen is that we need a GET route to generate the OpenID request in MapKnitter, something like `https://mapknitter.org/auth?u=USERNAME` which redirects to the much longer OpenID path I tried to use above. Then the link would be: `https://publiclab.org/auth/github?origin=https://mapknitter.org/auth?u=USERNAME`.

**Comment by SidharthBansal** [comment]
>> we can leave off Welcome Email, Password Reset, & Email/Account Verification, as we'll just let those happen in plots2!

Removing them from the issue body.

**Comment by SidharthBansal** [comment]
Regarding the OAuth. If we will carefully notice then we will be able to use the whole Plots2 auth model including Oauth as a plugin. We may not require any separate routes for the oauth at MK.

**Comment by SidharthBansal** [comment]
> However, something like that could likely work; we could then just show the OAuth icons as links on MapKnitter, and with the appropriate OpenID URL we could then get directed through PublicLab.org for authentication. Perhaps what needs to happen is that we need a GET route to generate the OpenID request in MapKnitter, something like `https://mapknitter.org/auth?u=USERNAME` which redirects to the much longer OpenID path I tried to use above. Then the link would be: `https://publiclab.org/auth/github?origin=https://mapknitter.org/auth?u=USERNAME`.

Are you suggesting 
A) have independent OAuth providers at MK OR
B) use OAuth at plots2 auth system ?

**Comment by jywarren** [comment]
I'm suggesting we could use the plots2 OAuth, but we could have a starting
point URL in MK that would initiate the OpenID permission granting. The
sequence for
https://publiclab.org/auth/github?origin=https://mapknitter.org/auth?u=USERNAME.
would be:

1. Log into PL.org using GitHub OAuth
2. get redirected back to new MapKnitter /auth URL, which:
3. redirects to start an OpenID request back to PL.org
4. approval is given (or remembered from last time it was given)
5. redirect back to MapKnitter as part of OpenID flow with approval
6. land on MK dashboard, logged in

This is convoluted, but what it gets us is the ability to smoothly use PL
OAuth from MK using our existing site integration. The only new thing I
think would be the new path in (3).

User interactions would be only:

1. click on GitHub OAuth icon from MK.org (redirects)
2. give OAuth approval from GitHub (redirects, redirects)
3. give OpenId approval from PL (redirects)

I think we could refine this even more by saying that we always
auto-approve OpenID requests from MK.org, automating (3) -- as long as the
request came from MapKnitter.org. What do you think?

**Comment by SidharthBansal** [comment]
We can continue to discuss Oauth in #378. I made many issues as things were getting twisted.

**Comment by SidharthBansal** [comment]
This issue is properly broken up into subissues. All the subissues contain information discussed here. So closing this issue.
Thanks Jeff
