### ISSUE TITLE
Mailers for login project

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#366]
Trying modular approach,
>> mailers. Do we really need them?

>> Noting here that if we rely on Plots2 auth system, we can leave off Welcome Email, Password Reset, & Email/Account Verification, as we'll just let those happen in plots2!

Part of #301

**Comment by SidharthBansal** [comment]
I agree we will not require for Welcome Email, Password Reset, & Email/Account Verification.
But do we require any other mailer? I think we need to notify the user through email about access grant of MK from plots2. This all companies do. Whenever I first authorize any application through facebook, then facebook messages me about the authorization.

**Comment by jywarren** [comment]
That's a good thought, thanks. But perhaps we could build that mailer into
`plots2` and not here? We do have mailers here, but probably are better at
keeping them maintained over at plots2.

**Comment by SidharthBansal** [comment]
No problem. I was confused at time of opening up thread, where should I open. 
Moved to https://github.com/publiclab/plots2/issues/4899
