### ISSUE TITLE
Logout not working at MK

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#367]
* Hi folks, are you able to logout from the MK. I tried but am not able to do so. @jywarren @gauravano
@jywarren when a user logs out from the plots2 should it be automatically logged out from the MK?

I was able to do so after refreshing the webpage.

**Comment by SidharthBansal** [comment]
We need to refresh the page to logout.

**Comment by jywarren** [comment]
ah, does it work to append `?_=123456` <= where the number is a unique
timestamp?

**Comment by SidharthBansal** [comment]
Probably you are talking about the cache, if I am not mistaken.
https://mapknitter.org/#2/43.0/2.8 is route after successful log out.
Now I am able to log in and out smoothly. Some problem is there which occurs sometimes.

**Comment by gauravano** [comment]
@SidharthBansal the issue still exists. Can I solve this one?

**Comment by SidharthBansal** [comment]
Yeah sure

**Comment by SidharthBansal** [comment]
Yeah sure. Sometimes it is getting logged out and sometimes not. You can
try this Gaurav

**Comment by gauravano** [comment]
Thanks, included it in my PR #383
