### ISSUE TITLE
Remove Gateway page for authentication at MK

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#368]
Chiming in here @jywarren's comment
> `Creation of intermediate gateway frontend for MK to login to pl. Present page has no validation errors, forget password options etc.` for this can we also just entirely rely on the plots2 login system with nothing extra required for MK?

Yeah we are dependent on the plots2 system but there are many places in the gateway where we will be requiring some error messages. Like:

**Comment by SidharthBansal** [comment]
Chiming in here @jywarren's comment
> `Creation of intermediate gateway frontend for MK to login to pl. Present page has no validation errors, forget password options etc.` for this can we also just entirely rely on the plots2 login system with nothing extra required for MK?

Yeah we are dependent on the plots2 system but there are many places in the gateway where we will be requiring some error messages. We need to make them work. I will be commenting on the errors asap in this thread asap.

**Comment by jywarren** [comment]
So the default might be that when you click Log In, it says "we couldn't
find a user for that...." -- which I think it may do already. Would
validation as you're proposing here happen in JavaScript? I think I'm
inclined to stick with the basics until we solve some of the other issues
that make up the Login project, but want to fully understand -- thank you!

**Comment by SidharthBansal** [comment]
Like:

![image](https://user-images.githubusercontent.com/20972099/53618827-0a845280-3c13-11e9-9001-8886ac1154c2.png)
- If red flash message is present then there should be no option for yes and no.
- Instead of green flash message, text should be present before yes and no options
- I entered correct user name but it showed ``ownloading`` I really don't know why.
- Eventhough it showed me such a weird name but I was able to log into MK.

**Comment by jywarren** [comment]
Is it possible this happened while you were logged in as `bansal_sidharth2996`? That'd be an important edge case. I believe we have had an alert that says "you are logging in as the wrong user" but am not sure that's still working? Let's document these edge cases and make a list!

**Comment by SidharthBansal** [comment]
I tried to login as bansal_sidharth2996. There is some problem with the basic flow. It is giving wrong username.

**Comment by SidharthBansal** [comment]
>> I think we could refine this even more by saying that we always auto-approve OpenID requests from MK.org, automating (3)

As per your comment in related issue, if we are automating the flow from Mapknitter, then this will become much simpler. 
Will we require any webpage after automating? I don't think. We can show the errors on plots2 or MK.
What do you think?

**Comment by SidharthBansal** [comment]
As discussed in #301 with Jeff, let's remove this gateway page.

**Comment by SidharthBansal** [comment]
Moving to plots2 repository as code is present in that repo.
Things are getting untwisted :-))))
