### ISSUE TITLE
Data fetching from the plots2 

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#369]
Currently we rely on plots2 for the authentication through open id connect. We require the roles from the user tables for posts at MK.

**Comment by SidharthBansal** [comment]
>> For (1), we could set up a JSON API endpoint (or use an existing one?) in plots2 to read status and role, which aren't private data anyways. We would want to store that in the session so we don't have to keep fetching it, but we'd have to think about when to flush it. We should just consider when for security reasons we should re-check status. Maybe this means we really have to check every 5 minutes or something...? Or just each time (that'd be pretty slow, though only for actions which require a specific role or status)

as per @jywarren's suggestion

**Comment by SidharthBansal** [comment]
@jywarren what do we require apart from roles and usernames?
Will we be requiring location or latitude of the person in the near future?

**Comment by jywarren** [comment]
Ah, that's a good point. Yes, we might try to tie that in if they've shared
it. It's stored as user tags, but we could expose it alongside the other
User model JSON API output to simplify things so it's in the same call. But
it'd be used less often than checking status.

What if we provided a URL that could be used ONLY by PublicLab.org to flush
the status/role that's saved in MK? Then we could essentially store it
locally but if it ever changed in PL.org, we could ping that URL to
invalidate. I don't know if there's an existing system for that kind of
thing. How do OAuth providers/consumers maintain record state across
domains?

**Comment by jywarren** [comment]
Once we get to rails 5.2 we could read user state remotely in Json using https://github.com/DmitryTsepelev/store_model

**Comment by jywarren** [comment]
Or maybe with https://github.com/remiprev/her

**Comment by SidharthBansal** [comment]
Thanks for the resources.
I have installed spectral workbench. Working fine. Facing some difficulty
in mk and plots2. Once it is set. I will remove the intermediate gateway
page. Then we can start with this issue.
Thanks
S

**Comment by SidharthBansal** [comment]
Plots2 working fine. But MK gives error
![image](https://user-images.githubusercontent.com/20972099/54543334-7dd3e580-49c3-11e9-9bbd-03f7a72a4cb8.png)

Trying to resolve it.

**Comment by jywarren** [comment]
ah maybe it needs `bower install` to get the assets?

**Comment by gauravano** [comment]
Can't we get more data from Openid? Currently, we fetch only nickname --- username and email from plots2 as required fields. I think, we should be able to get more data. I will see.

**Comment by gauravano** [comment]
I went through the whole code and it turns out that we can only access 8 fields allowed by Simple registration extension - https://openid.net/specs/openid-simple-registration-extension-1_0.html

Options we have:
1. Making API
2. Accessing role by another name like fullname which is allowed. But, yeah, it can confuse people.
3. These fields are maintained in openid/extensions/sreg - https://github.com/openid/ruby-openid/blob/a8e643d194acc35c7d5890109b14e0c6f590a1fe/lib/openid/extensions/sreg.rb#L6-L17

We can try to override it and add more fields?

I think making API is good, as we can use it for other purposes and by this was we won't be playing with the code of `ruby-openid` gem.

**Comment by SidharthBansal** [comment]
(1) I think we should consider making an API in case we need a lot of other things except role, status and map coordinates.
(2) We can hide the fullname from people like we did in the user_tag values for the oauth providers, 
like fullname = "status=xyz,role=pqr" etc then use split(',') method etc. Good option.
(3) I will try this. This will be the best option. But playing can go wrong too so need to be careful.

**Comment by SidharthBansal** [comment]
Thanks @gauravano for the insight. I am trying which can be the best option.

**Comment by SidharthBansal** [comment]
On thinking, I came to the conclusion that we should drop 1 and 3 idea as
1. API can be built but we already have the gem. So, it's better to use the existing code then to create it.
3. Uses all the gem related files which we need to clone and then set up. Then we will also need to manually update those files with an upgrade in the rails gem. So, this doesn't seem a great option for me.

So, I am sticking with ``fullname = "status=xyz,role=pqr" etc then use split(',') method etc. ``

**Comment by SidharthBansal** [comment]
We can add it here
https://github.com/publiclab/plots2/blob/9230253d5bdf7ab1eaff7b4532904b29f7cddd67/app/controllers/openid_controller.rb#L19 
and 
https://github.com/publiclab/plots2/blob/9230253d5bdf7ab1eaff7b4532904b29f7cddd67/app/controllers/openid_controller.rb#L287 and we will be done with this issue. Thanks Gaurav for your help.

**Comment by SidharthBansal** [comment]
Opened a PR for this issue https://github.com/publiclab/plots2/pull/5571/files

**Comment by SidharthBansal** [comment]
Please review https://github.com/publiclab/spectral-workbench/pull/447 and https://github.com/publiclab/mapknitter/pull/557/files also.
Thanks

**Comment by SidharthBansal** [comment]
https://github.com/publiclab/plots2/pull/5571 and https://github.com/publiclab/spectral-workbench/pull/447 remaining for this issue. 
Thanks
