### ISSUE TITLE
Validate user names at MK header

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#371]
We need to validate usernames here 
![image](https://user-images.githubusercontent.com/20972099/53618216-64374d80-3c10-11e9-89e1-3fb7e6f8f089.png)
if the user name has `.` and the person clicks on login at MK then page simply refreshes. Instead it should show the error.

**Comment by SidharthBansal** [comment]
Can we somehow remove the username and try to login through PL?
Somehow we will use the session created by PL at MK without username. This can enable us to reduce some flows which give errors with usernames.

**Comment by jywarren** [comment]
Hmm, could we... open a modal from PublicLab.org here? i bet that violates
some cross-domain security practice though.

**Comment by SidharthBansal** [comment]
I think we will not require modals here. We are not having a signup functionality at MK. Sign Up will be done through PL. We don't even need the password field. Also, we have 3-4 pages only in MK so we don't need linking to modals as we did previously at plots2. 
Creating/ linking the PL modal here will result in hiding the maps which we show. Right now in the header in the drop-down menu, everything is easily visible. What do you suggest?

**Comment by jywarren** [comment]
Yes, i agree. Let's aim for a minimal starting point for the PL login
sequence. Sound good?

**Comment by SidharthBansal** [comment]
So, in this issue we have to consider 4 cases:
1. User wants to signup at MK through PL. Username not found error message should be shown at the header. User should be asked to create an account at PL or use another username.
2.  User wants to login through MK through PL with any of the four provider: Custom route will be created. No flash message required
3. User wants to login through MK through PL with form(in background PL is not logged in): User is redirected to the PL then user logs in. Redirected back the original page. 
4. . User wants to login through MK through PL with form(in background PL is  logged in): User is not redirected to the PL but is logged in.

So, we will show required error messages at the header for the above cases(which can't be shown on PL).

**Comment by SidharthBansal** [comment]
Update: After removal of the gateway page(https://github.com/publiclab/plots2/pull/5472), the flows have reduced a lot.
if username at MK/SWB matches the username at plots2 
.......then user is logged in to MK/SWB
else
......flash error to ask user to again log in or try logging MK/SWB with same username as they are logged 
......in with plots2
end

**Comment by SidharthBansal** [comment]
This functionality is working. I think we can close this issue. In case you feel there are more flash error messages needed then feel free to open it @jywarren.
Thanks @jywarren.
