### ISSUE TITLE
Tests for the MK Auth System

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#372]
We need to do this project so that login/signup works on :

1. Localhost:3000/ for MK (without ssl version)
2. localhost:3000 for plots (without ssl version)
3. stable branch
4. unstable branch
5. main production branch
6. localhost:3001 for plots (with ssl version)

- Single OAuth Provider Sign Up can be checked. This will behave the same for all four providers as implementation code is exactly the same.

- Single OAuth Provider Log In can be checked. This will behave the same for all four providers as implementation code is exactly the same.

- User logs at pl for MK through Login/Signup forms

I have to see which tests are remaining. Need to check the code.

**Comment by jywarren** [comment]
This is good - it'll be a little tough perhaps because it's hard to test an
OpenId flow across domains. Ideas?

**Comment by SidharthBansal** [comment]
What is the present scenario? What we have for Mapknitter?
Do we have stable, unstable branch or is there any other naming conventions etc?

**Comment by SidharthBansal** [comment]
By present scenario I mean WAS the code functional for those branches at time you created this login?

**Comment by jywarren** [comment]
I believe we have only main and stable branches on this repo, and stable
just sources from main just before we publish. But @icarito is working on
mirroring how we do it on plots2, so this should change soon.

**Comment by SidharthBansal** [comment]
So, we are not having unstable branch, right?

**Comment by jywarren** [comment]
we will, it's just not set up yet. Thanks!!!

**Comment by SidharthBansal** [comment]
Hi, I checked all these behaviours. They are working correctly after removing the Gateway Page.
Closing this issue.
