### ISSUE TITLE
Forget Sessions for CDAS

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#374]
@jywarren should all the applications(MK, MapMill, Workbench) log out when we log out from PL.org. OR do we need to log out only MK/ Mapmill / Workbench which ever user tries to log out?

**Comment by jywarren** [comment]
I think we should simply log out of MapKnitter, not PL.org. We could
display a message like "if you'd like to log out of PublicLab.org as well,
click here" going to https://publiclab.org/logout - what do you think?

**Comment by SidharthBansal** [comment]
I think we should keep the log out feature independent. No need to club log
outs at any point.
When we log out from pl we are not logged out from fb nor we get any flash
messages. So, I think we should keep things independent.
