### ISSUE TITLE
Return_to MK on Authentication

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#375]
Currently, the MK application is able to login/sign up at pl through basic flow. The user needs to click many times. We need to have redirect back sequences.
Part of #301

**Comment by jywarren** [comment]
This is like `return_to` parameters to ensure people end up on the same
page they started the login sequence on? Thanks!

**Comment by SidharthBansal** [comment]
Correct.

**Comment by SidharthBansal** [comment]
List if routes to check for return to
* profile pages
* map/map name
* feed/
* dashboard 
* tags
* author
* search
* images
* comments
I hope there are no more links. I double checked the routes file.

**Comment by SidharthBansal** [comment]
Everything is working fine with the current changes done in the https://github.com/publiclab/plots2/pull/5472
So closing this issue
