### ISSUE TITLE
Update Bootstrap version to the latest version

### ISSUE THREAD

**Issue by stefannibrasil** [publiclab/mapknitter#377]
The project is currently using Bootstrap 3.2.0, but it would be nice to update it to the newest version (now it`s at 4.3.1).

I'm finishing some tweaks on the navbar but as soon as it's finished I can start working on this one, but feel free to suggest anything or even start working on it :)

**Comment by stefannibrasil** [comment]
@jywarren I was first taking a look at the changes between Bootstrap 3 and 4, but now I'm ready to update it.

Is it okay to use [BootstrapCDN](https://getbootstrap.com/docs/4.0/getting-started/download/#bootstrapcdn) or is it better to update it using bower?

The reason I'm asking is because: 1) If there isn't a specific need to use bower, I would rather use CDN and 2) I remember you said you were switching the package manager to yarn. Let me know how do you think is the best approach to take here. Thanks!

**Comment by jywarren** [comment]
Let's aim for bower for now, and that can be refactored later. That way we
can manage versions and ordering and everything in a consistent way, if
that's OK? Thank you!!!

**Comment by stefannibrasil** [comment]
okay, thanks!
