### ISSUE TITLE
Creation of OAuth route for MK

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#378]
Adding details from #301 and #362 about Oauth to make conversation modular
@jywarren's suggestion:
> 
Here, I think we can probably just use the current OAuth links, like:

https://publiclab.org/auth/github?origin=https://publiclab.org/

We can probably generate the correct OpenID auth URL too; i wonder... when you enter your username at MK, you get something like:

`https://publiclab.org/openid?openid.claimed_id=https%3A%2F%2Fpubliclab.org%2Fopenid%2Fwarren&openid.identity=https%3A%2F%2Fpubliclab.org%2Fopenid%2Fwarren&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.realm=https%3A%2F%2Fmapknitter.org&openid.return_to=https%3A%2F%2Fmapknitter.org%2Fsessions%2Fcreate%3Fauthenticity_token%3Df%252F1DBQMxfNXIAtKn7Fhan6ABt4GNL1iEHkn6PnDLRj4%253D%26back_to%3D%252F%26open_id%3Dwarren%26commit%3DLog%2Bin&openid.sreg.required=nickname%2Cemail`

Could we do:

https://publiclab.org/auth/github?origin=https://publiclab.org/openid?openid.claimed_id=https%3A%2F%2Fpubliclab.org%2Fopenid%2Fwarren&openid.identity=https%3A%2F%2Fpubliclab.org%2Fopenid%2Fwarren&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.realm=https%3A%2F%2Fmapknitter.org&openid.return_to=https%3A%2F%2Fmapknitter.org%2Fsessions%2Fcreate%3Fauthenticity_token%3Df%252F1DBQMxfNXIAtKn7Fhan6ABt4GNL1iEHkn6PnDLRj4%253D%26back_to%3D%252F%26open_id%3Dwarren%26commit%3DLog%2Bin&openid.sreg.required=nickname%2Cemail

No, there's an error:

![image](https://user-images.githubusercontent.com/24359/53600877-b0cf4a00-3b78-11e9-80cc-ef2ced0a63d4.png)

However, something like that could likely work; we could then just show the OAuth icons as links on MapKnitter, and with the appropriate OpenID URL we could then get directed through PublicLab.org for authentication. Perhaps what needs to happen is that we need a GET route to generate the OpenID request in MapKnitter, something like `https://mapknitter.org/auth?u=USERNAME` which redirects to the much longer OpenID path I tried to use above. Then the link would be: `https://publiclab.org/auth/github?origin=https://mapknitter.org/auth?u=USERNAME`.

**Comment by SidharthBansal** [comment]
I'm suggesting we could use the plots2 OAuth, but we could have a starting
point URL in MK that would initiate the OpenID permission granting. The
sequence for
https://publiclab.org/auth/github?origin=https://mapknitter.org/auth?u=USERNAME.
would be:

1. Log into PL.org using GitHub OAuth
2. get redirected back to new MapKnitter /auth URL, which:
3. redirects to start an OpenID request back to PL.org
4. approval is given (or remembered from last time it was given)
5. redirect back to MapKnitter as part of OpenID flow with approval
6. land on MK dashboard, logged in

This is convoluted, but what it gets us is the ability to smoothly use PL
OAuth from MK using our existing site integration. The only new thing I
think would be the new path in (3).

User interactions would be only:

1. click on GitHub OAuth icon from MK.org (redirects)
2. give OAuth approval from GitHub (redirects, redirects)
3. give OpenId approval from PL (redirects)

I think we could refine this even more by saying that we always
auto-approve OpenID requests from MK.org, automating (3) -- as long as the
request came from MapKnitter.org. What do you think?

**Comment by SidharthBansal** [comment]
> give OpenId approval from PL (redirects)
>I think we could refine this even more by saying that we always
auto-approve OpenID requests from MK.org, automating (3) -- as long as the
request came from MapKnitter.org. What do you think?

I agree with you. Let's automate it. As this is part of the intermediate gateway page, we can tackle it in #368

**Comment by SidharthBansal** [comment]
For OAuth providers the sign up and login means the same as route is same for both the sequences.

So we will be having 4 providers at bottom of 
![image](https://user-images.githubusercontent.com/20972099/53677973-7ed7f800-3cde-11e9-9784-74a03e2a7e93.png)
for all the four providers?

**Comment by jywarren** [comment]
Yep, that's great!

**Comment by SidharthBansal** [comment]
For forms we rely on pl. Right?
Will there be any problem with redundancy of providers at mk header and pl login modal?

**Comment by jywarren** [comment]
Hmm, can you break that down for me? Sorry... how do you mean redundancy?

**Comment by jywarren** [comment]
Yes, i think that's right!

**Comment by SidharthBansal** [comment]
There will be two flows
1. User clicks on the any of the providers on the header of MK at bottom of 
![image](https://user-images.githubusercontent.com/20972099/53822843-8a554880-3f96-11e9-9872-db865a0818de.png)
Now we are able to login into MK.
2. User clicks on Sign Up through PL on this header.
![image](https://user-images.githubusercontent.com/20972099/53822843-8a554880-3f96-11e9-9872-db865a0818de.png)
they get
![image](https://user-images.githubusercontent.com/20972099/53823043-f33cc080-3f96-11e9-92ec-24038fdefb75.png)
So between 1 on MK and 2 on PL there is redundancy.

**Comment by jywarren** [comment]
Ah, ok - yeah, are you saying we could have them be the same thing, and after redirecting to PL.org, ask for a username then OR prompt to sign up? (both needing a working return_to to MK.org when done?)

**Comment by SidharthBansal** [comment]
One option is to show OAuth providers at MK and modify the routes so that the flow will be
FB on MK -> FB sign up -> MK
Second option is 
Click on login on MK-> Click PL OAuth providers -> Return_to to MK page
Which one do you suggest?

**Comment by jywarren** [comment]
I think the second, which would be most in line with #2 of [the list above](https://github.com/publiclab/mapknitter/issues/378#issuecomment-468888248), where we just need an OpenID-request-generating path on MK, but the rest is on PL.org. Right? 

Thanks!

**Comment by SidharthBansal** [comment]
OK. Then we don't need any front end changes.
It will be Signup on MK -> Fb at PL Login Page -> Fill password + email at fb page -> redirected to MK.

**Comment by SidharthBansal** [comment]
Update: Design 4 is being implemented by @IshaGupta18 in https://github.com/publiclab/mapknitter/issues/385 as per @jywarren 's suggestion.
I am making the route for OAuth in this issue as per @jywarren 's suggestion (https://github.com/publiclab/mapknitter/issues/378#issue-416361527).

**Comment by IshaGupta18** [comment]
Yes absolutely! Thank you!

**Comment by SidharthBansal** [comment]
The issue just requires us to create routes.
https://github.com/publiclab/mapknitter/blob/04222fad0036ea706ac1a94f89e7948118908217/app/controllers/sessions_controller.rb#L21
I checked. open_id_url is it is localhost:3000/people/admin/identity for admin entered in the text field.
So, I went to the plots2 and found 

https://github.com/publiclab/plots2/blob/1df46d088cb88615a58719261cb1411bc8da25bd/app/controllers/legacy_controller.rb#L35-L37

linked to the route.
`/openid/:username' is linked to 
https://github.com/publiclab/plots2/blob/1df46d088cb88615a58719261cb1411bc8da25bd/app/controllers/openid_controller.rb#L145-L171
But we don't have any such <body> in any login sequence. So, presently bewildered.
Also, in the user_session_controller create action, we are using the openid as follows:
https://github.com/publiclab/plots2/blob/1df46d088cb88615a58719261cb1411bc8da25bd/app/controllers/user_sessions_controller.rb#L134


Just trying to find out the sequence of events taking place, so that we can change '/login' at pl.org to '/auth/github' at pl.org

**Comment by SidharthBansal** [comment]
Hurray!! One step closer. Found 
https://github.com/publiclab/plots2/blob/1df46d088cb88615a58719261cb1411bc8da25bd/app/controllers/openid_controller.rb#L57
If I change it to `redirect_to '/auth/github'` then I am able to login MK through GitHub. Isn't that great?

**Comment by SidharthBansal** [comment]
I guess we can have if-else conditions for these providers. Just checking it up.
May be we will need to change these lines too
https://github.com/publiclab/plots2/blob/1df46d088cb88615a58719261cb1411bc8da25bd/app/controllers/openid_controller.rb#L87
and https://github.com/publiclab/plots2/blob/1df46d088cb88615a58719261cb1411bc8da25bd/app/controllers/openid_controller.rb#L122

Things can become easier once all other work is completed.

**Comment by SidharthBansal** [comment]
Currently, user tries to login at MK through github is not able to login to MK but is able to login to the plots2.
So, we need to make the user logged in to the MK too after logging them to plots2. This can be achieved after my all other prs are merged @jywarren.

Thanks. We are almost at last stage of completion of the project now. Thank you.

**Comment by SidharthBansal** [comment]
I receive this error after user logs in github and pl
![image](https://user-images.githubusercontent.com/20972099/56497841-d9dade00-651c-11e9-84fa-f3b15c0b7950.png)
