### ISSUE TITLE
Creation of PL provider icon 

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#381]
How about creating PL icon along with the OAuth providers at the bottom of 
![image](https://user-images.githubusercontent.com/20972099/53824313-aad2d200-3f99-11e9-9999-9096cada0941.png)
PL icon can be used to sign up/log in through publiclab.org.

**Comment by jywarren** [comment]
Could we make it similar to the layout of the PL modal, like "use your
email or these providers"?

**Comment by SidharthBansal** [comment]
Actually in both these cases username is required.

**Comment by SidharthBansal** [comment]
Moved to #385
