### ISSUE TITLE
Frontend for MK authentication

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#385]
**Design 0**
Let it remain as it is
![image](https://user-images.githubusercontent.com/20972099/53948151-2f823500-40ed-11e9-90e8-8de49a851d4b.png)

**Design 1**
![image](https://user-images.githubusercontent.com/20972099/53947927-c69abd00-40ec-11e9-9127-eee797170cb2.png)
**Design 2**
![image](https://user-images.githubusercontent.com/20972099/53947221-58a1c600-40eb-11e9-851d-d9d866807d8a.png) like codechef.com
**Design 3**
![image](https://user-images.githubusercontent.com/20972099/53947530-f0071900-40eb-11e9-99a9-1ab6e68c723e.png)
**Design 4**
![image](https://user-images.githubusercontent.com/20972099/53948369-acadaa00-40ed-11e9-88c5-356ee264db00.png)

**Comment by SidharthBansal** [comment]
@jywarren I think we should have it like the Design 4. What do you think?

**Comment by IshaGupta18** [comment]
Agreed, I think design 4 looks good. I could start implementing it if that's okay @SidharthBansal @jywarren ?

**Comment by SidharthBansal** [comment]
I am doing back end. You can start doing it if you want. Once backed is complete we can link the URLs. Makes sense?

**Comment by IshaGupta18** [comment]
Should I start with the front end then?

**Comment by SidharthBansal** [comment]
Please wait for Jeff to finalyse the design

**Comment by jywarren** [comment]
Design 4 indeed! Be aware of the recent bootstrap header changes and that
@stefannibrasil is doing a bootstrap 4 upgrade! But yes and let's aim to
have it stylistically look like plots2? Thanks all!!!

**Comment by IshaGupta18** [comment]
Yes that would be great! Thanks!

**Comment by stefannibrasil** [comment]
yeah, try to get the new changes first, I didn't change a lot the login, just added some spacing between the items. Agree with having the same style as plots2 :+1:

**Comment by SidharthBansal** [comment]
Isha I am free from the exams will be trying to create the custom URLs tomorrow. You can start the work.
Let's do this in pieces. First step is to add 3 providers twitter, Facebook and github icon( don't include google icon). Use a partial for it so that we can use it at multiple places. Use plots2 code as there is no need to reinvent the wheels if we have them.

While you will be doing this, I will complete the MK custom routes. Then we can feed the routes. Does it makes sense?

**Comment by IshaGupta18** [comment]
Yes it does! I'll be on it ASAP!

**Comment by stefannibrasil** [comment]
hey everyone, please check it out the new amazing features Bootstrap 4 provides:

https://getbootstrap.com/docs/4.0/migration/

I have opened the PR for upgrading the app to use Bootstrap 4, just wanted to keep you updated before working on more this, some stuff changed a lot with this new version. Let me know if I can help with something :rocket:

**Comment by SidharthBansal** [comment]
@IshaGupta18 have you prepared the design 4?
Thanks @jywarren and @stefannibrasil for the amazing Bootstrap work.

**Comment by SidharthBansal** [comment]
@IshaGupta18 the PL icon in design 4 
![image](https://user-images.githubusercontent.com/20972099/56476882-686b4300-64bc-11e9-8a37-edfc0434a294.png)
will be linked to the same route as login button on 
![image](https://user-images.githubusercontent.com/20972099/56476880-60ab9e80-64bc-11e9-9c2c-3c341a8476fe.png)
There will be 4 providers: Github, Google, Facebook and Twitter. For that please use the plots2 code. 
Does this make sense?

**Comment by IshaGupta18** [comment]
Yes it does make sense! Thanks!

**Comment by SidharthBansal** [comment]
When are your exams ending? Just curious to know it.

**Comment by IshaGupta18** [comment]
This Friday only!

**Comment by SidharthBansal** [comment]
Great

**Comment by SidharthBansal** [comment]
I hope your exams went well.
You have to follow the following steps:
Step 1. Install Mapknitter
Step 2. Copy _login_form.html.erb as https://github.com/publiclab/mapknitter/blob/668595a4d356dd43b199ebaa658070e6539dae81/app/views/layouts/_login_form.html.erb
Step 3. Change design formed after step 2 to the design proposed by Isha by any method such that the links are working.

**Comment by SidharthBansal** [comment]
![image](https://user-images.githubusercontent.com/20972099/56850769-86093400-6924-11e9-9f54-59bc58d9e879.png)
![image](https://user-images.githubusercontent.com/20972099/56850772-8efa0580-6924-11e9-9082-9b61eb510623.png)

@IshaGupta18 I created this much. Now just we need to make it look beautiful and change the ''login'' button to public lab icon.

**Comment by SidharthBansal** [comment]
This issue is broken into ftos already. SWB is left.
