### ISSUE TITLE
Download dropdown not working

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#386]
### What happened just before the problem occurred
Hi!  I exported this map, then when I went to the dropdown menu, I couldn't see the full dropdown.
<img width="1048" alt="Screen Shot 2019-03-08 at 2 30 04 PM" src="https://user-images.githubusercontent.com/7490478/54051165-26f23300-41af-11e9-9d57-9aee0b49528f.png">

### Relevant URLs

https://mapknitter.org/maps/tidwell-park

### Browser, version, and operating system
 I'm on Chrome: Version 72.0.3626.119 (Official Build) (64-bit)

Thanks!

**Comment by gauravano** [comment]
@steviepubliclab you were not able to see contents of dropdown after the export is done(just achieved 100% status), but after refreshing the page, the dropdown worked fine?

**Comment by jywarren** [comment]
![Screen Shot 2019-03-13 at 6 08 37 PM](https://user-images.githubusercontent.com/24359/54317943-141a9c80-45bb-11e9-990b-7953fc2ac2a6.png)

Seems to be now? So maybe what @gauravano suggests is true?

**Comment by steviepubliclab** [comment]
Hi, yes for some reason it seems to be there now.

Best,
Stevie

**Comment by jywarren** [comment]
Thanks!
