### ISSUE TITLE
Setting dropdown not working

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#387]
Please see the rightmost settings icon.
![image](https://user-images.githubusercontent.com/20972099/54089653-29ac7e00-4391-11e9-8f01-437ced616c54.png)

**Comment by avsingh999** [comment]
@SidharthBansal  Can I Work on This issue.

**Comment by SidharthBansal** [comment]
Sure

**Comment by avsingh999** [comment]
@SidharthBansal  I want to know we have to remove this icon when the user is not login.because this only work(delete) when the user is not login. you can see here in code
https://github.com/publiclab/mapknitter/blob/6d8d8b5b3f6a8dfd8415f3a70efbeccefc73f044/app/views/maps/show.html.erb#L7
thanks : )

**Comment by cesswairimu** [comment]
Thanks to @stefannibrasil We now have this great layout for deleting map that only shows up when one has the rights to delete the map. The `setting dropdown icon` does not exist anymore
![mapshow](https://user-images.githubusercontent.com/17081074/55684114-664ba500-5950-11e9-93ba-ab3327f8acf8.png)

Guess we can close this now. Thanks

**Comment by stefannibrasil** [comment]
it was a little confusing, so I moved the button to be close to the other actions. Thanks, everyone!

**Comment by gauravano** [comment]
Thanks @stefannibrasil and yes, great work :tada:. Closing this now. Thanks all!
