### ISSUE TITLE
Removal of redundant /maps route

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#388]
I found that MK.org/map redirects to the MK.org
Either we can change the dashboard of MK OR delete /map route. What do you suggest @jywarren?

**Comment by jywarren** [comment]
Hmm, i think we can delete it; it predated the MapKnitter layer of Leaflet
Environmental Layers, which is a better way to view all maps anyways :-)

**Comment by SidharthBansal** [comment]
I will remove this. Last exam left.

**Comment by SidharthBansal** [comment]
I checked this. /maps route is linked to show the maps. Root page is directed to show the maps on the dashboard page. So closing this issue.
