### ISSUE TITLE
Repetition in recent authors sidebar

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#389]
![image](https://user-images.githubusercontent.com/20972099/54089708-ddae0900-4391-11e9-9d06-2ae33caae29b.png)

**Comment by shubhscoder** [comment]
@SidharthBansal , I would like to work on this!

**Comment by SidharthBansal** [comment]
Great

**Comment by govindjeevan** [comment]
Helloo @shubhscoder @SidharthBansal
Is this issue resolved?

**Comment by govindjeevan** [comment]
Hope this resolves the issue, please have a look.

**Comment by cesswairimu** [comment]
I believe we replaced recent authors with featured mappers. Closing this
