### ISSUE TITLE
Improper grid view at home page

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#391]
![image](https://user-images.githubusercontent.com/20972099/54089780-b441ad00-4392-11e9-9183-31583339e6a0.png)
Third row first two columns are empty

**Comment by avsingh999** [comment]
@SidharthBansal  we should improve also for the mobile view and in profile images grid ex. (https://mapknitter.org/profile/stevie)
thanks : )

**Comment by divyabaid16** [comment]
Hey!!
Can I work on this one?

**Comment by gauravano** [comment]
Go ahead @divyabaid16!
