### ISSUE TITLE
collapse login dropdown with map layers dropdown icon

### ISSUE THREAD

**Issue by avsingh999** [publiclab/mapknitter#393]
### What happened just before the problem occurred

![map1](https://user-images.githubusercontent.com/25536022/54109446-b3e1fa00-4404-11e9-8476-df2abd7db628.png)

### Relevant URLs

https://mapknitter.org/#4/47.95/-13.23

### PublicLab.org username
singhav
(to help reproduce the issue)

### Browser, version, and operating system
chrome ubuntu 18.04 LTS

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by gauravano** [comment]
Hey @avsingh999, you would be resolving this or should I include this bug fix in my already open PR? Thanks!

**Comment by avsingh999** [comment]
@gauravano I will try to solve this one.
thanks :smile:

**Comment by gauravano** [comment]
Great!

**Comment by jywarren** [comment]
I believe we may need to add a custom z-index here, but @stefannibrasil has
also recently implemented a new menubar, so let's be sure we don't work
redundantly!

**Comment by avsingh999** [comment]
@jywarren okay great. Then I have to close this issue.
thanks : )

**Comment by gauravano** [comment]
Closing this issue then. Thanks!
