### ISSUE TITLE
[suggestion] when click on login open popup like plots2

### ISSUE THREAD

**Issue by avsingh999** [publiclab/mapknitter#394]
### What happened just before the problem occurred
when we click on this login icon it's opening login form.
![map3](https://user-images.githubusercontent.com/25536022/54109927-07087c80-4406-11e9-9084-10b90b636bed.gif)

### Relevant URLs

https://

### PublicLab.org username
singhav
(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by avsingh999** [comment]
@jywarren @SidharthBansal  when we click on login I think must open popup like plots2. What do you think about this?
thanks : )

**Comment by SidharthBansal** [comment]
I am trying to reduce login flow a lot. It is being discussed in other
threads.
Thanks
