### ISSUE TITLE
Improve exports page for mobile

### ISSUE THREAD

**Issue by avsingh999** [publiclab/mapknitter#395]
### What happened just before the problem occurred
when we open this page in mobile it's UI, not Good https://mapknitter.org/exports
![map4](https://user-images.githubusercontent.com/25536022/54111609-45a03600-440a-11e9-984e-11d24e0f20ae.gif)

### Relevant URLs

https://mapknitter.org/exports

### PublicLab.org username
singhav
(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by avsingh999** [comment]
@SidharthBansal @jywarren I think this issue is valid but I don't know what would be the better solution.
what do you think about this @jywarren @SidharthBansal .
thanks :smile:

**Comment by jywarren** [comment]
Perhaps some of the Export columns could be made to show only at larger
screen widths, using Bootstrap styles? https://getbootstrap.com/docs/3.3/

Good idea!

**Comment by divyabaid16** [comment]
Hey!!
Can I work on this?
