### ISSUE TITLE
Dragging in an image to the "new map" screen doesn't switch to the Uploads modal

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#406]
### What happened just before the problem occurred

I dragged in an image to the map on the welcome modal screen, but nothing changed on the screen. Actually the image uploaded but since it didn't switch to the uploads modal, i couldn't tell.

### Relevant URLs

https://mapknitter.org/maps/cranston-test (delete all the images to try this)

![mapknitter](https://user-images.githubusercontent.com/24359/54317102-b2f1c980-45b8-11e9-8150-cdf56440f561.gif)

**Comment by govindjeevan** [comment]
The map on the Welcome Modal Screen being just a normal image than a map itself, Is it supposed to accept drag inputs?

**Comment by cesswairimu** [comment]
@jywarren I just tested this and its working fine both locally and online...maybe some other PR fixed it? 
![working](https://user-images.githubusercontent.com/17081074/55354109-8b15c780-54cd-11e9-944d-224c69fe63ed.gif)
