### ISSUE TITLE
Pressing Continue after uploading an image doesn't show the images list

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#407]
### What happened just before the problem occurred

After uploading an image, you can either "place" it or press `Continue` - but pressing `Continue` doesn't show the images in the images tab. There must be a JavaScript error:

![image](https://user-images.githubusercontent.com/24359/54316152-6c9b6b00-45b6-11e9-8cf0-eafaa69da1e8.png)

Refreshing the page then shows the images, but new users won't know that. 

### Relevant URLs

https://mapknitter.org/maps/cranston-test

****

## Observations

I tried it and it only happens when it's the first image! Once there's an image, it doesn't happen anymore. 

## Theory

I bet what's happening is that it's looking for an HTML element to add to, but when there are none yet, the element is not there yet to add onto. Looking in the code for what drives this to check this idea out...

Yes! It tries cloning the last image from the modal: 

https://github.com/publiclab/mapknitter/blob/24ac85cc79c89e6a5fc7cc6d3f0f912a1d935ea4/app/assets/javascripts/uploads.js#L36-L43

Hmm, when i upload one image to test this out, `$("#uploaded-images-list tr:last")` actually does still return the image. I'm not sure why it's not working, but could use help debugging this!

**Comment by govindjeevan** [comment]
Yes @jywarren 

`  jQuery(".warpables-all tbody").append($upload);
`
Will not be able to find the **".warpables-all tbody"** element as the partial [views/images/_index.html.erb](https://github.com/publiclab/mapknitter/blob/main/app/views/images/_index.html.erb) that contains the table is not rendered when there are no images.

**Comment by govindjeevan** [comment]
![image](https://user-images.githubusercontent.com/23054200/54713547-e31b0880-4b74-11e9-8b46-4fdcf4d2fbf2.png)

I have modified it to render the image table partial regardless of no image or not, and conditionally displayed a message like this.

**Comment by jywarren** [comment]
This is wonderful!!!
