### ISSUE TITLE
Update required Ruby version in README instructions

### ISSUE THREAD

**Issue by coreytegeler** [publiclab/mapknitter#412]
Towards the bottom of the **[Prerequisites](https://github.com/publiclab/mapknitter#prerequisites)** section of the [README](https://github.com/publiclab/mapknitter/blob/main/README.md) it is instructing to "install version 2.1.2 of Ruby" while MapKnitter 2 is currently using 2.4.4

<img width="370" alt="Screen Shot 2019-03-18 at 10 37 52 AM" src="https://user-images.githubusercontent.com/3860295/54538035-e8f0ce00-4969-11e9-98db-9aa164b4518f.png">

Though this seems like an open-and-shut case, this is my first time attempting to contribute here so I would like a response to confirm this does indeed need to be fixed and I am not missing something. If so, I'd be happy to claim the issue myself and can fix right away and test my first pull request.

Thanks!

**Comment by gauravano** [comment]
hey @coreytegeler, nice catch and sure, go ahead. Thanks!

**Comment by coreytegeler** [comment]
Thank you Gaurav, I've just put in a pull request https://github.com/publiclab/mapknitter/pull/416
