### ISSUE TITLE
Upgrade Export model to rely on external exporter process status, URLs

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#413]
Building on #326 and #298, we have to store records of the exports even though they'll be running off-app in the cloud, and I had thought we'd do so in the existing Export model. 

Currently the Export model has a field for each of the export products, where it will list a URL for each type, and a `status` field where it reports its status.

We can add a new column called `export_url` with the URL of `status.json`, and we can use one of these libraries to fetch the properties inside it and report things like status:

* https://github.com/DmitryTsepelev/store_model
* https://github.com/remiprev/her

Then we can refactor so that if the data is stored locally we use it, but if there's something in the `export_url` field, we fetch it remotely and report it in.

**Comment by sashadev-sky** [comment]
moving a small piece of information from jywarren commented in #483:
<blockquote>
I think next step will be to allow for it to have a remote status.json file. So, we:

add a remote_url column to Exports
check if it exists
if it does, we redirect requests to status to the remote URL (which'll be our external exporter)
we think of how the client may send a remote URL up to the MapKnitter Rails app for storage?
</blockquote>
