### ISSUE TITLE
separate title and URL fields in map creation

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#43]
this will hopefully make for better URLs rather than automatically generating them. JavaScript could monitor changes to the title field and auto-fill the URL field, swapping "-" for spaces/punctuation and removing "and" and "the", but prompting the user to enter/edit/approve the final URL.

**Comment by vpowerrc** [comment]
Hi Jeff,
I added this function by introducing new field called "url" to the map model. But there are lot of places in the app where it uses map.name to identify the maps, create images, in rxml files etc. We need to fix all of them. I may need your help regarding some of them.

**Comment by jywarren** [comment]
Hi Vidurqnga, @manleyjster and I were talking about using the friendly_url
gem to do this... There's more discussion of it in the comments here:
https://github.com/manleyjster/mapknitter/issues/1

And I also want to be sure you're working off the latest branch:

https://github.com/jywarren/mapknitter/pull/181

This is a big integration project and I apologize if it wasn't clear what
our plans for the codebase were.

**Comment by vpowerrc** [comment]
I followed your instructions in above comment in order to implement it. 
So is it already implemented?
If you want, you can look at my implementation too. I can make a pull request. 
I think I also have to merge the latest code

**Comment by jywarren** [comment]
Its not already implemented, but I will take a look in a little bit and see
what we can do. Thanks!

**Comment by jywarren** [comment]
Hi, Viduranga - I can't find your code -- it doesn't seem to be here: https://github.com/vpowerrc/mapknitter/tree/viduranga could you make a branch with it called "map-url-fields" or something? 

I'm sorry, when you didn't respond last time I didn't realize you were going to continue work on this branch. I think it's plausible (although I would have to look at the code) that you could:

a) pull the https://github.com/jywarren/mapknitter/tree/annotation-interface branch into a fresh local branch,
b) cherry-pick your map URL commits and merge them in on top of annotation-interface
c) submit a pull request

Or perhaps @manleyjster can suggest a better way. 

The other issue is whether:

1. we should adopt your code and ditch the [friendly_id](https://github.com/norman/friendly_id) based plan
2. we can integrate all or parts of friendly_id into your code, perhaps by letting friendly_id handle slug generation but using map.url to store it? Hard to say without seeing your code.
3. we could substantially rewrite your code around friendly_id
4. either approach can easily preserve old URLs with a database migration, where we save the currently auto-generated routes `/maps/foo` into either map.url or friendly_id-based saved URLs. 

Apologies again, but if we adopt @manleyjster's recommendation to treat publiclab/mapkniter master as our edge branch (and the `stable` branch as the deployed code) , it'll be more clear to new contributors what to base their pull requests on. His suggestion makes a lot of sense in light of this situation. However, in the future, can I ask you to check in on the [plots-dev discussion list](http://publiclab.org/wiki/developers) as you work, which should also help to keep synced? Thanks so much for your work.

**Comment by vpowerrc** [comment]
Hi Jeff,
I pushed my current changes without merging with https://github.com/jywarren/mapknitter/tree/annotation-interface to "map-url-fields" branch for now.
I will do the merge tomorrow.

As I said before there are lot places still need to be changed since now map is identified by the url column, not by the name column. I changed it in most of the places which I could understand. But I need help in some areas of the app.

No problem. First you can take a look at my code, then we can decide what to do.

**Comment by jywarren** [comment]
Hi, Viduranga - i hope you saw my email to plots-dev -- I think the best
thing to do may be to rebase your changes on top of the upcoming
mapknitter2 code:

https://groups.google.com/forum/#!topic/plots-dev/9dWJqchfGPM

I also think it's worth it to use friendly_id, and after browsing [the
documentation](http://norman.github.io/friendly_id/file.Guide.html), it
seems like that's possible. That means you could just use
Map.find('my-map') directly, which is cool. If you can rebase your changes,
would you consider attempting to integrate friendly_id also? Keep an eye
also on the "parameterize" function in ActiveRecord -- we def. want the
client-side slug generation you've written to work the same as
ActiveRecord's conversion if that's possible.

Jeff

**Comment by vpowerrc** [comment]
Great I will integrate friendly_id

**Comment by vpowerrc** [comment]
Hi Jeff,
Map.find('my-map') kind of queries only work with friendly_id 5.0 or greater. Otherwise we need to use Map.friendly.find('my-map')
But friendly_id 5.0 depends on active-record 4.0
How should I proceed? 
Also shall I keep a separate column like "url" for the slug(like I already did) or use the same "name" column and use friendly_id to parameterize it whenever we want?

**Comment by jywarren** [comment]
Map.friendly.find is fine! Thanks.

**Comment by vpowerrc** [comment]
Hi again
I was able to integrate friendly_id successfully. Then I cherry picked my commits like you suggested. But there were about 25 conflicts. So I decided to redo my changes on the new branch since some views were also changed. I will send a pull request as soon as possible.
Cheers

**Comment by jywarren** [comment]
super!

**Comment by vpowerrc** [comment]
I made a pull request https://github.com/jywarren/mapknitter/pull/182

**Comment by jywarren** [comment]
merged into the master development branch, thanks!
