### ISSUE TITLE
Change comment count on comment creation via AJAX

### ISSUE THREAD

**Issue by gauravano** [publiclab/mapknitter#441]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/mapknitter/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

Currently, the comment addition at https://mapknitter.org/maps/test-map-3 takes place using AJAX so no refresh happens. So, it would be better if we also increment the comment count too.  

- [ ] 📝 **Update** the file (https://github.com/publiclab/mapknitter/blob/main/app/assets/javascripts/maps.js#L60](https://github.com/publiclab/mapknitter/blob/main/app/assets/javascripts/maps.js#L60) in the https://github.com/publiclab/mapknitter repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
+    $("#comments-number").text(function(i, str) { return (parseInt(str) + 1); });
```

With this code addition, with every new comment, the comment count will be incremented at the same time.

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by gauravano** [comment]
This issue is created for @sonali9696. Thanks!

**Comment by sonali9696** [comment]
Hey @gauravano,

Thanks a lot for creating an issue for me so quickly! I deeply appreciate it. I understood what changes to do and can go ahead and raise the PR but before that, I wanted to understand the code better and try to test it. However, the link which is given above: https://mapknitter.org/maps/test-map-3 is showing "Page doesn't exist" for me.

![image](https://user-images.githubusercontent.com/12599774/54865806-38cbfc80-4d91-11e9-86e6-3b81367231fb.png)

**Comment by sonali9696** [comment]
If you find some time, it would be great if you could clarify my doubt:

While deleting a comment, the code used is:
$("#comments-number").text(function(i, str) { return str - 1; }); 

However the code you asked to add for incrementing comments-number is:
$("#comments-number").text(function(i, str) { return (parseInt(str) + 1); });

Is parseInt necessary here? If yes, why didn't it cause an issue in the code used in delete_comment function? I went to the scripts mentioned in "require" at the top of the code and the codes they in turn led to but I didn't find any references or usage of the text or str or comments-number.

**Comment by gauravano** [comment]
> Thanks a lot for creating an issue for me so quickly! I deeply appreciate it. I understood what changes to do and can go ahead and raise the PR but before that, I wanted to understand the code better and try to test it. However, the link which is given above: https://mapknitter.org/maps/test-map-3 is showing "Page doesn't exist" for me. I have raised the issue for the same here: #442

hey @sonali9696, actually the link- https://mapknitter.org/maps/test-map-3 I provided was an example, you wouldn't find that on production because there is no map with title test-map-3 in production.

But, you can reproduce this issue by commenting at https://mapknitter.org/maps/testing--8(It's a test map, I guess, it would be deleted shortly by moderators but feel free to comment for testing on this one).
You can also reproduce the issue by running the project locally - https://github.com/publiclab/mapknitter/#installation too. 

Thanks!

**Comment by gauravano** [comment]
> Is parseInt necessary here?

yes! 

> If yes, why didn't it cause an issue in the code used in delete_comment function? 

Because, if I initialize a variable `a = "3"` and perform operation as `a = a-1`, it will return 2 as a result. But, if I perform + operation on variable a = "8" i.e., a = a + 1. I will get "81" as a result as JS will treat them as a string and will perform concatenation.

![Screenshot from 2019-03-23 23-57-30](https://user-images.githubusercontent.com/20878070/54870127-75671a80-4dc8-11e9-8396-7e27a4415588.png)

> I went to the scripts mentioned in "require" at the top of the code and the codes they in turn led to but I didn't find any references or usage of the text or str or comments-number.

We are fetching the number of comments from DOM using jQuery as `$("#comments-number").text()` gives us the number of comments in string format.

**Comment by gauravano** [comment]
Solved in #443

**Comment by sonali9696** [comment]
Thank you for taking out the time to clarify my doubts :)

**Comment by sonali9696** [comment]
My Twitter handle is sonali09061996 (https://twitter.com/sonali09061996)
