### ISSUE TITLE
Page does not exist on visiting URL https://mapknitter.org/maps/test-map-3

### ISSUE THREAD

**Issue by sonali9696** [publiclab/mapknitter#442]
### What happened just before the problem occurred
This link was referenced in issue #441 however on clicking on this URL, I get a window stating that the page does not exist

### Relevant URLs

https://mapknitter.org/maps/test-map-3

### PublicLab User Name
sonali9696

### Browser, version, and operating system
Browser: Google Chrome
Version: 72.0.3626.121 (Official Build) (64-bit) (cohort: Stable)
OS: Windows 10

For bug reports, fill out the above template; for feature requests, you can delete the template.

![image](https://user-images.githubusercontent.com/12599774/54865983-957ce680-4d94-11e9-99e9-c3942215fb77.png)

**Comment by gauravano** [comment]
Closing this. Please refer - https://github.com/publiclab/mapknitter/issues/441#issuecomment-475892804. Thanks!
