### ISSUE TITLE
change icon when toggle side bar 

### ISSUE THREAD

**Issue by avsingh999** [publiclab/mapknitter#446]
### What happened just before the problem occurred
**when sidebar is hide then icon chevron-left**
it's good
![pub10](https://user-images.githubusercontent.com/25536022/54878833-f4effa80-4e57-11e9-9d3a-7a937851df06.png)

**when sidebar show then icon must be chevron-right**
> current situation

![pub9](https://user-images.githubusercontent.com/25536022/54878832-f4effa80-4e57-11e9-995c-1a91b66ffabc.png)

> require

![pub11](https://user-images.githubusercontent.com/25536022/54878860-426c6780-4e58-11e9-9a09-544a2ef773e5.png)

### Relevant URLs

https://

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by gauravano** [comment]
Would you like to work on this @avsingh999?

**Comment by avsingh999** [comment]
@gauravano sure

**Comment by gauravano** [comment]
Great!
