### ISSUE TITLE
Weekly Community Check-in #15 - "GSOC Applications Commence"

### ISSUE THREAD

**Issue by CoderJolly** [publiclab/mapknitter#447]
Hello Everyone!!!

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. The goal of our Community Check-In is for every community member to share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️ .

If you're new here, welcome 🎈, and please comment a Hello message below, we love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from last week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us 🔃 and doing well!

As always, if you're waiting for a review, or if you're stuck, you can request help here, leave a comment on your issue with @publiclab/reviewers mentioned, or ask the community in our Gitter chatroom 👐 .

### Gitter
Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation page.

### This Week's Theme
Let's complete the issues which need rebase and let the community grow. And this week the Applications for GSOC start and we hope our community is at its best to put in. 
Let's rebase and solve the issues where the contributor is not active.

### Summer of Code
@jywarren has started a brainstorming post for the ideas page for Summer of Code 2019 -It would be best to get some ideas into the discussion from the fellow community member before time. People have been brainstorming already - let's do it together!
https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019
And this is the official idea’s page:
https://publiclab.org/wiki/gsoc-ideas

### Outreachy
If you're a Outreachy aspirant and looking forward to spending your summer with us working on UI improvements of https://publiclab.org, then check out publiclab/plots2#5022 and call for Outreachy proposals is also open -https://publiclab.org/notes/gauravano/03-12-2019/call-for-outreachy-2019-proposals so do start your proposal early!

### Welcoming First Timers
Check out issues first-timers-only labeled issues in [mapknitter](https://github.com/publiclab/mapknitter/issues?q=is%3Aissue+is%3Aopen+label%3Afirst-timers-only) and [plots2](https://github.com/publiclab/plots2/issues?q=is%3Aissue+is%3Aopen+label%3Afirst-timers-only) if you are a first timer who is in search of an issue to start your open source journey. You are always welcome!

cc
@mohitRJranjan @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @geekychaser @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @rexagod, @dinaelhanan, @dependabot[bot], @oorjitchowdhary, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @romanrodriguez @Dhiraj240 @codeIriss @rishabhc32 @chirag-singhal @IgorWilbert @dhruvgupta167 @vrk99 @pdurbin @HarshKhandeparkar @aashna27 @Harshithpabbati @marieram @swiatek7 @kaunair
@niravasher

Thanks and keep contributing! Contributing to Public Lab means contributing to the Environment.

People who did the check-ins-

Sidharth Bansal (@SidharthBansal)
Cess (@cesswairimu )
Rishabh Rawat (@Rishabh570 )
Sasha Boginsky (@sashadev-sky)
Rishabh Kr Bothra (@geekychaser)
Shubham Sangamnerkar (@shubhscoder)
Siddhant N Trivedi(@sidntrivedi012)
Isha Gupta (@IshaGupta18)
Gaurav Sachdeva (@gauravano)
Harshith Pabbati (@Harshithpabbati)
Gaurav Sachdeva
Harshith Pabbati (@Harshithpabbati)
Harman Jolly (@CoderJolly )

Have a great week everyone 🎈 🎉 🎇

**Comment by HarshKhandeparkar** [comment]
Hello @CoderJolly. Thank you for the check-in!
I think the titles are not proper. You will have to leave a space between the hash `#` characters and the titles like 
`### Summer Of Code`.

**Comment by CoderJolly** [comment]
> Hello @CoderJolly. Thank you for the check-in!
> I think the titles are not proper. You will have to leave a space between the hash `#` characters and the titles like
> `### Summer Of Code`.

I have corrected that already, thanks for the update

**Comment by HarshKhandeparkar** [comment]
Mention limit exceeded and also mentioning some newcomers

@marieram @swiatek7 @kaunair @gauravano @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps
****
@subhahu123 @An0u @Jaya738 @mgroovyank 
@shreyateeza @TANGL3SIT3S @nazeem1988 @karunagoyalk @Nirvikalpa108 @cassianoblonski @EngrEric @Anjalizi @GettyOrawo @coderbeetle @corbettbw @govindjeevan @gautamig54 @daddyjab @emestabillo @letnewKid @srujana121 @jazdao @ChinwenduSilvia @aggarwal19 @Jenniline @madelinejones @helenatxu @richa031 @fabsar @kuja24 @megha070 @Aarabhi2017 @Manvi07 @siddhishree @CubikMan47 @Julius26 @VinneyJ

These are some newcomers. Welcome!!

**Comment by Harshithpabbati** [comment]
@nirvasher

**Comment by HarshKhandeparkar** [comment]
@teisenhower
@ElenaG518
@edwd42
@rmcorre
@rohithGoudM

**Comment by gauravano** [comment]
@sonali9696 @rarrunategu1 @coreytegeler @labseven @milomacphail @CleverFool77 @ananyaarun @ananya @divyabaid16 @publiclab-mimi @vaarigupta @alonpeer @madeofhuman

**Comment by rohithGoudM** [comment]
Hello!

**Comment by gauravano** [comment]
@bealearnscode @Ivilili

**Comment by HarshKhandeparkar** [comment]
Hi! Welcome!

**Comment by gauravano** [comment]
hello @rohithGoudM!

**Comment by teisenhower** [comment]
## Hey everyone!

**Comment by sashadev-sky** [comment]
Hi Everyone! 

Really awesome to be contributing to my 15th check-in with Public Lab. Time goes by so fast! 

This week I will be 
- Making sure the FTOs I opened are completed 
- Hopefully the ability to select multiple images in Leaflet.DistortableImage will be merged
- Circling back to complete an issue I opened on restructuring rake tasks in Mapknitter to complete that too
- Start looking into the Rails code for the exporter system in Mapknitter
- Reading GSOC proposals - I have seen some really interesting projects from people so far! 

Thanks!

**Comment by cesswairimu** [comment]
Hello everyone

This week I will be starting on solving some bugs on mapknitter and getting to know the code base. I will also be available to assist any of the new folks. 
Great check-in @CoderJolly, 
Good week ahead all :balloon:

**Comment by sagarpreet-chadha** [comment]
Hey everyone :)
I have planned to work on the testing and integration (to plots2) of leaflet based location blurred projects .
Thank you !

**Comment by jywarren** [comment]
Hello all! I'm writing feedback for as many Outreachy and Summer of Code as possible -- thanks all for some fantastic ideas!

Would love help from mentors and of course it's great for alums, current applicants, and anyone else to chime in with ideas and thoughts on these:

* https://publiclab.org/notes/warren/02-28-2019/call-for-summer-of-code-2019-proposals
* https://publiclab.org/notes/gauravano/03-12-2019/call-for-outreachy-2019-proposals

There's also some good guidance on how we structure and plan Summer of Code projects here:

* https://publiclab.org/wiki/gsoc#How+we+work
* https://publiclab.org/wiki/software-outreach#The+complete+series+(so+far)

Thanks to everyone who's been going into open PRs and issues and encouraging people, offering tips, helping get things moved along -- they appreciate it and so do I!!! 🎉

**Comment by HarshKhandeparkar** [comment]
I have a question. When will the survey results be declared?

**Comment by jywarren** [comment]
Soon! Not sure but @ebarry knows. Need to sort the data, compile a post
from it, etc. Thanks! I'm eager too!

**Comment by subhahu123** [comment]
@jywarren @SidharthBansal @gauravano @publiclab/is-reviewers  Please review my proposal https://publiclab.org/notes/jainsubhahu/03-19-2019/soc-proposal?_=1553445259
and demo link https://swipper-view-fix-complete-issue-complete-notcolor.stackblitz.io/ angular

**Comment by milomacphail** [comment]
Hi everyone,

My first time after my first time here and just curious about how to get
started. Should I just review issues and then just call one?

Thanks,
Milo

**Comment by ebarry** [comment]
Hi all!
I'm working in person with Jeff this week and other coworkers in
Providence. My main tasks are to onboard a new staff person, and
additionally work on reporting on the software contributors survey and
making another evaluation plan for a project we'll be doing in New Orleans
Schools this fall

**Comment by avsingh999** [comment]
Hi Everyone
This week I will open a new issue and give suggestion and send pr 
thank you :  )

**Comment by divyabaid16** [comment]
Hello everyone!!!
My goal for this week are
* Create few new issues.
* Submit PRs.
* Review PRs.

Wish everyone a great week ahead :smile

**Comment by CleverFool77** [comment]
Heyaaa,
Let's keep rocking this organisation with enthusiasm and hard work.
I'll create ftos, try my best in helping first timers.
Improve and update my proposals after considering the suggestions of everyone.
Solve issues and fix bugs.

**Comment by jywarren** [comment]
Hi all! @subhahu123 will do my best, thank you!!!

For those looking, there are a few potential FTOs to be made here: #714

And someone is asking for some support here: https://github.com/publiclab/plots2/pull/5254

Thanks to @gauravano for going in and digging out old issues we can close or re-build!

**Comment by HarshKhandeparkar** [comment]
@jywarren #714 isn't from this repo.

**Comment by gauravano** [comment]
Here's the updated link: https://github.com/publiclab/plots2/issues/714

**Comment by jywarren** [comment]
Ah, oops :-P forgot, thank you both!

**Comment by gauravano** [comment]
Also, there's an awesome cleanup PR by one of our GCI participant Valentina here -https://github.com/publiclab/plots2/pull/4417/. If anybody want to collaborate and push that to completion, it would be great!

Thanks!

**Comment by gauravano** [comment]
> My first time after my first time here and just curious about how to get
started. Should I just review issues and then just call one?

Hi @milomacphail, you can work on solving `help wanted` labeled issues and can also review other's work or create new issues for others. If you want a suggestion for an issue to work on, let me know. Thanks!

**Comment by subhahu123** [comment]
> Hi all! @subhahu123 will do my best, thank you!!!
> 
> For those looking, there are a few potential FTOs to be made here: #714
> 
> And someone is asking for some support here: [publiclab/plots2#5254](https://github.com/publiclab/plots2/pull/5254)
> 
> Thanks to @gauravano for going in and digging out old issues we can close or re-build!

@jywarren  have seen the demo link of my work , i already implemented some feature ( for demo )
 https://swipper-view-fix-complete-issue-complete-notcolor.stackblitz.io/

**Comment by niravasher** [comment]
Hello, good evening from Mumbai. My plans for this week are to complete my GSoC proposal and the shadow issue that I opened. Also my college fest is starting day after tomorrow, so ACM Bits Pilani is coding a stock market simulation. As a part of the team I am working on that too.

**Comment by HarshKhandeparkar** [comment]
Hi, good evening (night?) from Goa!

**Comment by HarshKhandeparkar** [comment]
Nirav does BITS in Mumbai organise quark?

**Comment by niravasher** [comment]
Bits is not in mumbai, there are three campuses of Bits
1) Pilani campus
2) Goa campus
3) Hydrabad campus.
I am from Pilani campus and it isn't organizing quark

**Comment by niravasher** [comment]
I am very greatful having ccpandhare as a senior of mine, completing his GSoC last year in image sequencer

**Comment by HarshKhandeparkar** [comment]
Oh I didn't know where the campusus were. Sorry. You live in Mumbai?

**Comment by niravasher** [comment]
Yes my house is in Mumbai. but I stay in a hostel here 😄

**Comment by HarshKhandeparkar** [comment]
Oh ok. I thought you currently live in Mumbai because you said "good evening from Mumbai" but anyways good luck for GSoC. I have visited BITS Goa campus a few times(for quark) and it's lovely. Some of my friends (i know them personally) study there. Hope you are having a good time! Sorry for talking too much.

**Comment by niravasher** [comment]
Hey man @HarshKhandeparkar why are you apologizing ❓  Its great talking to you.

**Comment by HarshKhandeparkar** [comment]
I kind of feel like talking here isn't very appropriate so I apologized. It is also nice talking to you.

**Comment by jywarren** [comment]
:-) no worries, chatting is fine 😄

**Comment by HarshKhandeparkar** [comment]
> We have Rakesh Sharma (first indian astronaut) as a speaker and Kiran Kumar (the ex-chairman of ISRO) as a chief guest

Great!!

**Comment by alonpeer** [comment]
Hello! 📛 

This is my first major step of contributing to OSS and I'm delighted to do so for a project such as Public Lab 🎈.

I have quite a lot of backend experience, especially with Rails apps and Drupal, so it feels quite natural for me to work on this codebase. 😄 
I especially like performance issues, and have quite a lot of experience with databases.

I started last week with writing tests for an issue that was resolved but was missing those tests. That was a nice first dive into the project.

Right now I'm looking for some help with [this impression counting PR](https://github.com/publiclab/plots2/pull/5248). I'm missing some knowledge of the production architecture and DB load, so I can't really resolve this on my own. Some help with someone with that kind of experience in the project would be great!

**Comment by ananyaarun** [comment]
Hi everyone !! :)
Its amazing how much work was done and how we grew as a community in the past few weeks !!

My goals remain

- Continue to contribute and learn
- Help new comers
- Work on opening and fixing issues

Thanks and good luck to all :smiley:

**Comment by jywarren** [comment]
😄 indeed how much we grew! Last week alone, per https://code.publiclab.org/#r=all (which counts only commits, not even helpful comments and support!): 

![image](https://user-images.githubusercontent.com/24359/54956129-9729e400-4f25-11e9-9851-656149d8bee2.png)

**Comment by Harshithpabbati** [comment]
@jywarren As the text-overlay module is already done we need to change the project in SoC ideas.

**Comment by jywarren** [comment]
:-) we'll surely find more things to add in, thanks!

**Comment by jywarren** [comment]
https://publiclab.org/notes/gauravano/03-29-2019/software-community-growth-through-first-timers-only-issues !!!! 

> Till now, nearly 409 FTO issues has been created across our projects which shows how many people have been welcomed in the Open Source 🌐 and in our community by the collaborative efforts of all of us. 
> we are proud to announce that in past 20 days, we all have created 55 #firsttimersonly issues

this is really lovely thank you Gaurav for writing it up! 🎉 👍 🎉 

@cesswairimu @gauravano @warren @CleverFool77 @Harshithpabbati @divyabaid16 @IshaGupta18 @ananyaarun @sashadev-sky @madeofhuman @HarshKhandeparkar @Divy123 @Rishabh570 @gautamig54

**Comment by HarshKhandeparkar** [comment]
@jywarren `warren` isn't a publiclab member( i guess) please change the mention to `jywarren`.

**Comment by gauravano** [comment]
Anyone interested in opening next check-in? Also, let's open check-in at https://github.com/publiclab/Publiclab.editor/. Thanks!

**Comment by divyabaid16** [comment]
I'm interested. Can I proceed?
Thanks!

**Comment by Harshithpabbati** [comment]
@divyabaid16 you can proceed. You need to follow the format.

**Comment by divyabaid16** [comment]
I have opened a new check-in at [https://github.com/publiclab/mapknitter/issues/447](https://github.com/publiclab/mapknitter/issues/447)

**Comment by gauravano** [comment]
Thanks @divyabaid16 :tada:
