### ISSUE TITLE
sidebar "Community Microscope: Intro Kit" Partial to new window

### ISSUE THREAD

**Issue by govindjeevan** [publiclab/mapknitter#449]
### What happened just before the problem occurred

![1](https://user-images.githubusercontent.com/23054200/54886388-8a69a980-4ead-11e9-8335-111d26801b86.gif)
Instead of rendering a small sized partial on click,
should we open the Community Microscope: Intro Kit Public Lab store page in a new modal?

### Relevant URLs

https://mapknitter.org

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by gauravano** [comment]
Nice idea @govindjeevan!

**Comment by jywarren** [comment]
Ah, perhaps even in a new window? But I believe this code is running from
our database-backed Features system, so I can make the change (as an admin)
if you think that makes sense? Thank you! Great idea!

**Comment by govindjeevan** [comment]
@jywarren yup, a new window is also apt.

**Comment by sashadev-sky** [comment]
Closing this one! It is outdated now because we don't link to the microscope kit at all anymore. Thank you!
