### ISSUE TITLE
remove transparency while sliding

### ISSUE THREAD

**Issue by avsingh999** [publiclab/mapknitter#454]
### What happened just before the problem occurred
when we create new map and slide up down then content transparance
![pub12](https://user-images.githubusercontent.com/25536022/54980350-7ddb7300-4fcb-11e9-8f04-58f1bc19ff28.gif)

### Relevant URLs

https://

### PublicLab.org username
singhav
(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by emestabillo** [comment]
Hi! Is this issue taken?

**Comment by avsingh999** [comment]
Hi @emestabillo  you can take this.
thanks :smile:

**Comment by igniteeng000** [comment]
Hi @avsingh999. I think this is solved now. Please check it again and close this.
If you are able to reproduce this again ping me.Thanks.

**Comment by gauravano** [comment]
Thanks @igniteeng000 for the update. Closing this one. @emestabillo we would love to have your help with other issues, as this one is solved. Thanks!
