### ISSUE TITLE
Get Cloud9 install script to pull from `main` branch instead of `master` branch

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#459]
Noticed that https://aws.amazon.com/cloud9/ automatically uses the `master` branch, but our default is the `main` branch, as outlined in our [new Quick Install instructions](https://github.com/publiclab/mapknitter/pull/420/files#diff-04c6e90faac2675aa89e2176d2eec7d8R28).

Is there any way to:

1. point it at the main branch when we input the URL?
2. OR, rewind the master branch far enough that there isn't a merge commit when pulling from `main` in the new `install_cloud9.sh` script?

See #420... I'd love help with this! Thanks!

**Comment by gauravano** [comment]
@jywarren I saw you used `git checkout -b ...` I think that's fine.

**Comment by kaunair** [comment]
Git clones from the default branch so I don't know why this should happen.
But still, I guess you can use something like this to explicitly specify the branch
`git clone https://github.com/kaunair/mapknitter -b main `
Do you think this will solve the issue?
Cheers!

**Comment by jywarren** [comment]
oh this is cool, yes we should try!

Should we guide people to fork the repository first, then pull from their
own? Is it possible to do this via commandline, which might be even easier?

**Comment by kaunair** [comment]
Yeah we can do this via the commandline as well!
The Github API lets you fork a repo using the command line
I managed to successfully fork image sequencer using this
`curl -u 'kaunair' https://api.github.com/repos/publiclab/image-sequencer/forks -d ''`
After this we can clone the forked repo

**Comment by kaunair** [comment]
Another cool idea that I got is,
We can create an interactive bash script that prompts the user for his github user name(Should be really easy to do)
Then we can use this for or fork and clone commands. If we do this, the user doesn't need to manually edit the github urls during cloning. Thus making the process easier. :tada:

**Comment by sashadev-sky** [comment]
closing this as cloud9.io is not available as of tomorrow, and Codenvy is opening on main!

**Comment by gauravano** [comment]
Cool!

**Comment by jywarren** [comment]
Awesome!!!
