### ISSUE TITLE
Leagacy Editor feature not working

### ISSUE THREAD

**Issue by igniteeng000** [publiclab/mapknitter#476]
### What happened just before the problem occurred
Leagacy Editor feature not working
![legacy](https://user-images.githubusercontent.com/25272573/55440318-d9f25880-55c4-11e9-97ec-af94b8692443.PNG)

### Relevant URLs

https://mapknitter.org/maps/sol?legacy=true

### PublicLab.org username

igniteeng000

### Browser, version, and operating system

Chrome , Windows 10
For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by avsingh999** [comment]
Hi @igniteeng000 I think this is same as #315.
thank you :smile:

**Comment by igniteeng000** [comment]
Ohh I tried the GitHub related issue beta feature.
No problem closing this issue.
Thanks.
