### ISSUE TITLE
button styling for "Place" button

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#487]
It looks like in the Bootstrap 4 upgrade, some buttons didn't quite get restyled- this `Place` button and perhaps it's neighbor are appearing as plain text:

![image](https://user-images.githubusercontent.com/24359/55584064-600bbd80-56f1-11e9-98fc-e09072094063.png)

https://github.com/publiclab/mapknitter/blob/8901fb0d0b982abd549af64ed09f48720a5ffe8e/app/views/images/_index.html.erb#L21-L22

**Comment by jywarren** [comment]
@stefannibrasil sorry i should've caught this but it seems a very small tweak -- would you mind? Thank you!!!

**Comment by stefannibrasil** [comment]
oops, I missed that one! Working on it :+1:
