### ISSUE TITLE
Prevent multiple builds for internal PRs

### ISSUE THREAD

**Issue by kaustubh-nair** [publiclab/mapknitter#490]
Currently, Travis builds twice for an internal PR. One build each for push and pr.
This hogs up on resources unnecessarily, so it would be better to build only once for a PR.
Since all our PRs are only to the main and unstable branch, we can restrict travis to build only for them by adding,

```
branches:
   only: 
    - main
    - unstable
```

**Comment by kaustubh-nair** [comment]
@jywarren @icarito What are your thoughts about this? Will this be beneficial?

**Comment by icarito** [comment]
Yes I agree - didn't know how to avoid the duplicate. If only for environmental reasons it is worth it!

**Comment by kaustubh-nair** [comment]
Great! I'll send a pull
