### ISSUE TITLE
Search by Space/blank should stop

### ISSUE THREAD

**Issue by avsingh999** [publiclab/mapknitter#520]
### What happened just before the problem occurred
It also Searches by space/blank. So I think need to add some query to stop this.

### Relevant URLs

https://

### PublicLab.org username
singhav
(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by divyabaid16** [comment]
Can I work on this issue?

**Comment by avsingh999** [comment]
@divyabaid16 Sorry, I am working on it
thank you : )

**Comment by gauravano** [comment]
I think we can impose min length of 3 chars? Let's ask @jywarren. Thanks!

**Comment by gauravano** [comment]
Also, @divyabaid16 maybe you can work on adding the test for this one? Thanks!

**Comment by divyabaid16** [comment]
Okay @gauravano 
Thanks!

**Comment by sashadev-sky** [comment]
closing this as its as its been partially address in #630 - reopening a new issue to address search constraints on the frontend side for performance improvement ill tag everyone there!
