### ISSUE TITLE
Improve login  page

### ISSUE THREAD

**Issue by avsingh999** [publiclab/mapknitter#522]
### What happened just before the problem occurred
all input fields, buttons, label, etc. are not in a proper way Because it should be in the center or left side.
But here is left margin is too much which is not required.
![pub24](https://user-images.githubusercontent.com/25536022/55924222-95029d80-5c26-11e9-95bb-e07189b94b68.png)

### Relevant URLs

https://

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by gauravano** [comment]
yes, @avsingh999, we can surely improve the login section. Also, you can coordinate with @SidharthBansal on this one and he's working on login flow. Thanks!

**Comment by SidharthBansal** [comment]
Thankd @avsingh999 for opening up an issue. We are working in #385 regarding this. Please join there.
Thanks
