### ISSUE TITLE
navbar not showing  when click on toggle side bar button

### ISSUE THREAD

**Issue by avsingh999** [publiclab/mapknitter#523]
### What happened just before the problem occurred

![pub71](https://user-images.githubusercontent.com/25536022/55926627-ad2aea80-5c2f-11e9-898c-29205f6c083e.gif)

### Relevant URLs

https://

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by avsingh999** [comment]
@jywarren @gauravano @sashadev-sky  what do you think about this. 
thank you : )

**Comment by gauravano** [comment]
I checked in Chrome and Firefox and not getting this issue. Also, @avsingh999 the screenshot is from localhost, is you clone in sync with the main branch?

I will also test locally!

Thanks!

**Comment by gauravano** [comment]
Yup, the issue can be reproduced locally. Maybe, it's related to bootstrap upgrade?

**Comment by avsingh999** [comment]
@gauravano yes I am sync with main.
thank you : )
