### ISSUE TITLE
Improving comment section

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#529]
### What happened just before the problem occurred
![Selection_133](https://user-images.githubusercontent.com/32747809/56015237-f5243d00-5d15-11e9-8e48-afbcd2b6c23f.png)

### PublicLab.org username

divyabaid16

Here, some changes that can be done are:
- [ ] The comment must also be placed in a box. We can use the panel header and body from bootstrap 4 to implement this.
- [ ] Emjois can be added.

**Comment by gauravano** [comment]
I think we can first go for comment card design? Thanks!
