### ISSUE TITLE
[Discussion]Implementation of Multi-user Synchronous Editor

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#532]
As mentioned in the issue #300, the "simultaneous multi-user UI, like Google docs" section. I would like to brainstorm about how can we implement this using Sockets and/or [Y-js](http://y-js.org/). Should we use Operational Transformation or Conflict-Free Replicated Data Types (CRDT)? Any suggestions would be very helpful.

**Comment by gauravano** [comment]
Hey @divyabaid16, do you think, we can close this one as we are holding discussions about it in https://github.com/publiclab/mapknitter/issues/609?

**Comment by divyabaid16** [comment]
Ya I just closed it :)
Thanks!
