### ISSUE TITLE
firefox Mac/desktop does not distort images

### ISSUE THREAD

**Issue by patcoyle** [publiclab/mapknitter#54]
Thanks Jeff.

I just took a quick look and noticed two issues, I put them on Github too.

In Firefox on Mac, maps have images all placed on top of each other vs in Safari, where look as expected, e.g,
http://test.mapknitter.org:3000/map/ewb-symposium-without-borders-davis-ca
also,
http://test.mapknitter.org:3000/map/livermore-ca-near-airport

**Comment by jywarren** [comment]
Thanks!! Can you post a screenshot for the Firefox bug? Also, what version
of Firefox? Thanks so much!

**Comment by patcoyle** [comment]
Thanks Jeff,

Attached pdf shows screenshots for Firefox 35.0 issues on Mac (OSX Yosemite
10.10.1) with compare of the Livermore near airport map in Safari.

Appreciate all the work bringing this version along.

Pat

**Comment by btbonval** [comment]
Hi Pat,

I think you replied to a GitHub issue using email, so the attachment was ignored by GitHub.

**Comment by patcoyle** [comment]
Oops, here are images from the pdf  attachment referred to in email. 
![mapknitter2 issues screenshots images export_page_1](https://cloud.githubusercontent.com/assets/5530305/5889686/de41a978-a3e8-11e4-934c-b30e393f10e1.jpg)
![mapknitter2 issues screenshots images export_page_2](https://cloud.githubusercontent.com/assets/5530305/5889687/de4503f2-a3e8-11e4-872b-e7d1b899f627.jpg)
![mapknitter2 issues screenshots images export_page_3](https://cloud.githubusercontent.com/assets/5530305/5889688/de45550a-a3e8-11e4-9245-67ffdf912a77.jpg)
![mapknitter2 issues screenshots images export_page_4](https://cloud.githubusercontent.com/assets/5530305/5889689/de457b20-a3e8-11e4-9d2d-1ec74121c315.jpg)
![mapknitter2 issues screenshots images export_page_5](https://cloud.githubusercontent.com/assets/5530305/5889690/de47c0ce-a3e8-11e4-9265-97605364cce6.jpg)
![mapknitter2 issues screenshots images export_page_6](https://cloud.githubusercontent.com/assets/5530305/5889691/de48f584-a3e8-11e4-9caa-b7a4d20b55bd.jpg)

**Comment by jywarren** [comment]
Moving the second bug to: #55

**Comment by jywarren** [comment]
Moving the second bug to: #55

**Comment by jywarren** [comment]
fix publishing to test server shortly!

**Comment by jywarren** [comment]
It may require a cache clear, btw!
