### ISSUE TITLE
Map view must not be scrolled

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#541]
### What happened just before the problem occurred
![Peek 2019-04-15 11-50](https://user-images.githubusercontent.com/32747809/56111254-ef786280-5f74-11e9-9ba3-d460605970ac.gif)

Position of map must be fixed on the screen and only the right column must be scrolled. 

### PublicLab.org username
divyabaid16

**Comment by sashadev-sky** [comment]
@divyabaid16 are you still getting this issue because I cannot reproduce it locally or on production site

**Comment by divyabaid16** [comment]
Closing this as it has been solved in #653 
Thanks!
