### ISSUE TITLE
Leaflet popup toolbar with image

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#542]
### What happened just before the problem occurred
![Selection_139](https://user-images.githubusercontent.com/32747809/56114061-5568e800-5f7d-11e9-89e5-1a40c970c5c2.png)

When I zoom in and zoom out the image, the toolbar is not moving with the image.
It must move with the image.

### PublicLab.org username

divyabaid16

**Comment by sashadev-sky** [comment]
@divyabaid16 this has been fixed in PR https://github.com/publiclab/Leaflet.DistortableImage/pull/201 and should be merged and upstreamed to mapknitter soon!

**Comment by sashadev-sky** [comment]
This is now merged! Now only pending thing to do is to upstream the updates to mapknitter. @jywarren  is selecting the optimal time to do this as we have a lot of different changes going on at once

**Comment by jywarren** [comment]
i made a release on DistortableImage, so we can check the bower.json
version in this repo and update it... !

**Comment by sashadev-sky** [comment]
@jywarren ok great! Just made the update locally and all the updates are there! Looks so good! I am going to open a PR with the updated bower.json to close this issue
