### ISSUE TITLE
Images preview not working during upload

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/mapknitter#549]
This was working previously not sure what broke it.

When uploading an image when you select the image(s) they are not shown on the modal
![images](https://user-images.githubusercontent.com/17081074/56443801-d2d68480-62fe-11e9-88b8-deeec5f5e3ae.png)

**Comment by jywarren** [comment]
awww, darn! Can you show a screenshot? Thanks!

**Comment by cesswairimu** [comment]
Hey @jywarren there is a sreenshot above. Thanks

**Comment by gauravano** [comment]
Solved in #562. Thanks!!
