### ISSUE TITLE
Tests fail sometimes due to bad keyservers

### ISSUE THREAD

**Issue by icarito** [publiclab/mapknitter#553]
Seems to be a common problem, here's the best doc found about it:
https://github.com/docker-library/faq#openpgp--gnupg-keys-and-verification

We've tried:
- limiting to IPv4
- using high availibility pool
- using specific server

Next I'll try https://github.com/tianon/pgp-happy-eyeballs as a workaround.

**Comment by sashadev-sky** [comment]
@icarito just going to put some PRs failing due to keyserver issues here for your easy reference: (delete this if you dont need this here)
- Add remote_url to export model #552
- Moving docs to right folder #545

**Comment by icarito** [comment]
I'm going to merge #554 which fixes this then. I don't think it needs a review but just here's a not @jywarren i'm adding a public key to let our container verify the key of our backported GDAL package.

**Comment by icarito** [comment]
> @icarito just going to put some PRs failing due to keyserver issues here for your easy reference: (delete this if you dont need this here)
> 
>     * Add remote_url to export model #552
> 
>     * Moving docs to right folder #545

Thanks I left a note on each and merged the fix to the main branch!

**Comment by sashadev-sky** [comment]
Thank you!! Is there anything you want me to note to do in case I see more of these keyserver issues, so I don't have to put them all on you?

**Comment by icarito** [comment]
:surfing_man: 
Thank you for your offer!
If you see previous PRs running into this feel free to restart builds with my apologies!
I'll issue same fix to `mapknitter-exporter` - this could surface there as well!

**Comment by sashadev-sky** [comment]
Ok sounds good!
