### ISSUE TITLE
Login consolidation

### ISSUE THREAD

**Issue by manleyjster** [publiclab/mapknitter#56]
There are currently two places on the home page where users can login.

![multiplelogins](https://cloud.githubusercontent.com/assets/1668487/5909694/7c1816d8-a578-11e4-93f3-0adf34e98f59.png)

The login link in the upper right-hand corner sends the user's auth request to the PublicLab OpenId server and then returns the user to the MapKnitter homepage once the user has successfully authenticated.

The login link the upper left-hand corner doesn't transmit the user's auth info to Public Lab, it's just a plain redirect to the PublicLab homepage. In addition, it doesn't bring the user back to where they started once authentication is complete. This is non-intuitive behavior.

The link in the upper right-hand corner is more recent (I did a bunch of work on it over the summer). As far as I can tell, it's superior to the old login link, except for anonymous login functionality (which it doesn't currently support).

We should port anonymous login to the new login form and then remove the old login form.

**Comment by jywarren** [comment]
The upper left can definitely be improved upon, but the basic intent is to:

a) make the sequence of events to map creation very visible and straightforward
b) encourage people to log in to make a map, but not *force* them if they have valid concerns

There's also the consideration that the location of the upper-left version is consistent with the location of the "new map" button when you *are* logged in, which makes some sense -- it's also in the best real estate on the page. 

Just throwing out ideas:

* the "new map" button could be disabled and could have a "log in" button which actually just opens the upper-right login form and gives it focus (we'd have to ensure that people actually notice the upper right one when it pops open)
* we could use a clone of the upper-right in a bootstrap popover or accordion which expands out of the upper-left "log in" link (this seems strained)

I could imagine other options, including just shuttling people through a login page, which is probably not ideal but would at least be really straightforward on mobile devices.

For bringing the user back, I think we can use the "return_to" parameter as part of the openid system, and the returning URL from publiclab.org will retain that URL. I *think* we have to check the return_to param and redirect in the sessions controller on the returning request from the openid process, but it's possible it's already handled.

**Comment by jywarren** [comment]
Oh, we also have to kill #52 before doing too much else :-( but it shouldn't be hard.

**Comment by jywarren** [comment]
Ah, checked -- it works to use a url like `/login?back_to=/maps/foo` so we just need to provide that on the outgoing openid request.

**Comment by jywarren** [comment]
Hey - I did some reworking; there are still two places to log in, but as I wasn't able to figure out how to get the collapsed navbar to open via JS, and also because it's an odd UI flow to direct someone up to the navbar, I inserted a small collapsed inline login form (using a partial of course) by the New Map button, which I also persisted (in disabled state) for non-logged-in users. If this looks good to you, let's close, but I'm open to other options or solutions.

**Comment by manleyjster** [comment]
With the login up in the navbar, I was copying exactly the way it's done on the Public Lab website:

![screenshot from 2015-02-03 13 15 21](https://cloud.githubusercontent.com/assets/1668487/6027337/ed0199d0-aba6-11e4-8f7f-3447f108c5e1.png)

Let me take a look at the new interface.

**Comment by jywarren** [comment]
Hi, Justin - we're very close to our [2.0 launch checklist](https://github.com/publiclab/mapknitter/milestones/2.0%20launch) being done; is this a blocking concern? I'd like to close it or remove it from the 2.0 checklist. Thanks!

**Comment by manleyjster** [comment]
Jeff - I'm not going to be able to give this the attention it deserves, so
you should make the call.

**Comment by jywarren** [comment]
OK, thanks Justin! I think we could revisit later, but the changes I made are an improvement and do address most of your comments. Personally I think that it's all right for an in-context login form to be redundant with an always-there login form in the header. But it's just one solution. Closing for now!
