### ISSUE TITLE
Add next/prev icons in pagination

### ISSUE THREAD

**Issue by igniteeng000** [publiclab/mapknitter#565]
### What happened just before the problem occurred
![image](https://user-images.githubusercontent.com/25272573/56863626-72b6a100-69d6-11e9-93e0-4ac6c2c4a40f.png)

prev and next icons are missing on both the home page and author page.

### Relevant URLs

https://mapknitter.org

### PublicLab.org username
igniteeng000
(to help reproduce the issue)

### Browser, version, and operating system
chrome, ubuntu/windows

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by cesswairimu** [comment]
Hey @igniteeng000 good catch, maybe I should have mentioned this elsewhere but I fixed the pagination buttons on #558

**Comment by igniteeng000** [comment]
Okay no problem @cesswairimu , Please mention this issue in your PR. I am closing my PR. Thanks

**Comment by divyabaid16** [comment]
I think this issue can also be closed @igniteeng000 
Thanks!

**Comment by jywarren** [comment]
Actually i think the pagination needs some extra work; we just published MapKnitter.org (yay!) but i see this:

![image](https://user-images.githubusercontent.com/24359/57738992-d3ed9e00-767f-11e9-888b-60e5715b08ab.png)

Can anyone check this out? Thank you!

**Comment by cesswairimu** [comment]
Hey @jywarren I believe #558 should fix it. Thanks

**Comment by sashadev-sky** [comment]
Closing this as its outdated and pagination is also fixed! Thank you guys!
