### ISSUE TITLE
Improve header ui

### ISSUE THREAD

**Issue by igniteeng000** [publiclab/mapknitter#566]
### What happened just before the problem occurred
![image](https://user-images.githubusercontent.com/25272573/56863702-5a935180-69d7-11e9-859c-a3c439a01f8a.png)

### Relevant URLs

https://mapknitter.org

### PublicLab.org username
igniteeng000
(to help reproduce the issue)

### Browser, version, and operating system
chrome, ubuntu/windows

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by gauravano** [comment]
Closing this as we have improved the UI: 

![Screenshot from 2019-07-13 20-58-41](https://user-images.githubusercontent.com/20878070/61173446-187ab480-a5b1-11e9-8721-8c7db513a427.png)
