### ISSUE TITLE
Map details do not show in beta annotation tool.

### ISSUE THREAD

**Issue by igniteeng000** [publiclab/mapknitter#567]
### What happened just before the problem occurred
Map details do not show in beta annotation tool.
![image](https://user-images.githubusercontent.com/25272573/56863749-de4d3e00-69d7-11e9-9475-6c4a05f4b5f0.png)

### Relevant URLs

https://mapknitter.org/maps/sol/annotate

### PublicLab.org username
igniteeng000
(to help reproduce the issue)

### Browser, version, and operating system
chrome, ubuntu/windows

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by gauravano** [comment]
Closing this as this issue seems to be solved:

![Screenshot from 2019-07-13 21-01-01](https://user-images.githubusercontent.com/20878070/61173479-75766a80-a5b1-11e9-9bf3-35472d8270fb.png)

Thanks!
