### ISSUE TITLE
Add like or dislike feature

### ISSUE THREAD

**Issue by igniteeng000** [publiclab/mapknitter#568]
### What happened just before the problem occurred
It will motivate users to place images on the map and can also help in reducing spam images.

### Relevant URLs

https://mapknitter.org

### PublicLab.org username
igniteeng000
(to help reproduce the issue)

### Browser, version, and operating system
chrome, ubuntu/windows

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by rarrunategu1** [comment]
Hello I'd like to work on this issue.

**Comment by sashadev-sky** [comment]
Closing this one because of duplication with #126 !
