### ISSUE TITLE
Do not show anonymous images on home page.

### ISSUE THREAD

**Issue by igniteeng000** [publiclab/mapknitter#570]
### What happened just before the problem occurred
Add an option to view anonymous posts by clicking on anonymous posts.
Show only registered user posts on home screen.

### Relevant URLs

https://mapknitter.org

### PublicLab.org username
igniteeng000
(to help reproduce the issue)

### Browser, version, and operating system
chrome, ubuntu/windows

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by sashadev-sky** [comment]
@jywarren @gauravano this issue never got any attention but I was actually just thinking about it too! Is this the best way to approach showing anonymous maps? Would it make more sense to make an "all" option instead next to the "featured" and "authors" sections that doesn't discriminate between anonymous / not?

**Comment by jywarren** [comment]
I think that would be great, @sashadev-sky and we should highlight this as something we may want to implement -- would anyone in SoC want to try this out? @kaustubh-nair @alaxalves or maybe @cesswairimu or @publiclab/mapknitter-reviewers ? Or @igniteeng000 you're welcome to it as well!

**Comment by divyabaid16** [comment]
I would like to work on this.
Thanks!
