### ISSUE TITLE
Problem continues w Firefox map dispaly

### ISSUE THREAD

**Issue by patcoyle** [publiclab/mapknitter#58]
See attached example image comparing map with display problems 
![1-29-15 mk2 issues ff vs safari](https://cloud.githubusercontent.com/assets/5530305/5981253/6b5737fa-a86d-11e4-9179-a147ad32d688.jpg)
in Firefox vs in Safari.

**Comment by jywarren** [comment]
Hi, Pat - it seems like the images in your Firefox screenshot haven't finished loading -- could you try again and wait a little longer, or did they stop loading at some point? 

![screen shot 2015-01-30 at 2 02 24 pm](https://cloud.githubusercontent.com/assets/24359/5981545/ffc4ecb4-a888-11e4-8106-f95efdb8a4f2.png)

**Comment by jywarren** [comment]
Closing, as this seems to have been still loading when the screen shot was taken. Feel free to reopen if it recurs.
