### ISSUE TITLE
Locked pictures allow moving the X symbol

### ISSUE THREAD

**Issue by dbeavers** [publiclab/mapknitter#59]
If you drag the X symbol on locked pictures it will move.  Click else where and then back on the picture and it is on the corner again.  I would suggest that the Xs don't appear at all on a locked picture.  What good are they?

**Comment by dbeavers** [comment]
I can't seem to label it mapknitter2.  I click on Labels with no resulting response.

**Comment by jywarren** [comment]
I tagged it, thanks. Good catch on the X dragging -- I'm moving the bug report to the Leaflet.DistortableImage tracker, which is the new library we've developed which does the distortion: https://github.com/publiclab/Leaflet.DistortableImage/issues/41

As to their use, they indicate that an image is selected, but locked; that way you know you can use hotkeys to modify it. We considered using a highlighted line around the image, but that makes it hard to see how well lined-up the image is.
