### ISSUE TITLE
Can't delete map images

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#591]
Looks like it's not possible to delete images, due to a bug! I believe @rarrunategu1 may be looking into this? Noting connection to Sairam's question at https://publiclab.org/notes/silentsairam/05-11-2019/how-to-delete-the-images-which-i-do-not-want-to-place-in-the-map

**Comment by rarrunategu1** [comment]
Yes, this is something I'm currently working on.

**Comment by rarrunategu1** [comment]
@jywarren I tested the mapknitter.org website and it deletes images and maps just fine.  If I delete an image it keeps the map ready for me under my author name.  If I delete the map, it deletes the entire thing and it doesn't show up on my authored maps anymore. Here's a picture of their creation:

![image](https://user-images.githubusercontent.com/29240939/57793872-63429200-7710-11e9-9ca2-337025130e6a.png)

Then I deleted the first map's image.  That map is still available to me but doesn't show up in the map images on the home page:

![image](https://user-images.githubusercontent.com/29240939/57794066-ca604680-7710-11e9-8470-957cfa5dea2b.png)

Now if I delete the map totally, which I'll do with the 2nd map, it deletes the entire map and image.  As you can see it's no longer in my authored maps:

![image](https://user-images.githubusercontent.com/29240939/57794311-5c684f00-7711-11e9-9b6c-3047af5be307.png)

Therefore I believe this issue can be closed.  
It would be nice, however, if the user had the option of creating another map right from the map creation and image placing url.  A button in this section sounds good.  It's easier than going back and forth for the user.  
![image](https://user-images.githubusercontent.com/29240939/57794520-d00a5c00-7711-11e9-9903-ffd9eacb6d31.png)
What do you think?

**Comment by rarrunategu1** [comment]
@jywarren I believe we can close this issue.  Image deletion works fine.  I have not had any issues with it.  Should the user be contacted to see if they're still having the same issue?

**Comment by jywarren** [comment]
Yes, can you leave a comment on their post on PublicLab? Sairam will be helping us find issues and it'll be good to be in touch!

**Comment by jywarren** [comment]
Thanks!!

**Comment by rarrunategu1** [comment]
Hello @publiclab/reviewers.  I'm boggled by what is happening here.  I can delete any image I put on a map I create with no problem.  I thought it could've been something wrong with this person's url.  Everyone else has a Url that matches their map name but in this particular situation the map name is "Garbage hot spots" with a url id going to airpollution"  I replicated the situation by changing the title of my map to see if I can make the title and url different and even with that I could delete my image.  The users's map is https://mapknitter.org/maps/airpollution.   silentsairam also has another map with no images named air pollution.  Not sure if that has anything to do with it.  Could this be a bug on one particular map that could've stuck while doing updates?  I don't even know if that's possible.
![image](https://user-images.githubusercontent.com/29240939/58978217-6114a600-8799-11e9-8d49-f69573406304.png)

**Comment by rarrunategu1** [comment]
I'm sorry to say that the image on the right of the map is mine.  I didn't think I could add one since it wasn't my map.  I tried deleting it but again this particular map does not allow that.  All other maps I've created do allow image deletion.

**Comment by jywarren** [comment]
whoa. does this happen for only anonymous maps? I was thinking perhaps it
was because there's no way to know if an anonymous user uploaded a given
image -- otherwise i think we allow map owners to delete, but if it's
anonymous, we don't know if you're the map owner. But in that case should
we, perhaps, make it possible to take it off the map, but keep it in the
images sidebar?

**Comment by rarrunategu1** [comment]
anonymous maps...I'll look into that.  Thanks Jeff.

**Comment by rarrunategu1** [comment]
The anonymous user can't delete an image nor delete a map.  Two fixes will be required.

**Comment by jywarren** [comment]
One possibility is also just showing an error message to explain this?

**Comment by sashadev-sky** [comment]
Im going to close this one as its resolved!
