### ISSUE TITLE
Planning Issue: Mapknitter Image Management and Synchronous Editing

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#593]
### Relevant URLs

https://

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by SidharthBansal** [comment]
@divyabaid16 please feel free to edit it.
Thanks

**Comment by divyabaid16** [comment]
Yes. 
Actually my exams just got over today and now I'm traveling back to my home. I will reach there by tomorrow and then edit it.
Thanks!

**Comment by SidharthBansal** [comment]
Sure. Best of luck for the results. I have 2 exams remaining. Don't wanna study for sometimes. haha

**Comment by ViditChitkara** [comment]
Will work on it after 16th. Tied up with exams till then.
Thanks!

**Comment by SidharthBansal** [comment]
No problem. We all are having exams.

**Comment by divyabaid16** [comment]
Hey, @SidharthBansal I am unable to edit the issue. I guess I don't have the required rights.

**Comment by alaxalves** [comment]
@jywarren Needs to add @divyabaid16  as collaborator in order to edit issues, create projects, add labels and such.

**Comment by gauravano** [comment]
Hi, closing this issue as we are running separate planning issues for Image management and Synchronous editing - #608 and #609. Thanks!
