### ISSUE TITLE
Increase Test Coverage

### ISSUE THREAD

**Issue by alaxalves** [publiclab/mapknitter#594]
I have realized that currently on Mapknitter we have ~60% of test coverage according to [this](https://coveralls.io/github/publiclab/mapknitter) right?!
I think that before we start we the upgrade it would be a MUST if we raised that to >80% minimum, as recommended [here](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#test-coverage). Or we could be more ambitious and set a goal of 100%.
After this we could move forward with the upgrade. What do you think @kaustubh-nair @SidharthBansal @jywarren ?

**Comment by jywarren** [comment]
Hi @alaxalves I believe Cess is already taking steps towards a Rails 4.0 upgrade here: https://github.com/publiclab/mapknitter/pull/578

CodeCov cites ~70% coverage here: https://codecov.io/gh/publiclab/mapknitter

However, I think more test coverage would be great, and 80 or near 100% would be a great goal. I think @rarrunategu1 may be helping us with this as well in the coming weeks. 

I would love to see us use this analysis tool to identify where we can increase our coverage:

https://codecov.io/gh/publiclab/mapknitter/tree/main/app

many of the low-rated files are quite simple, so I think we can pretty easily increase our coverage!

**Comment by SidharthBansal** [comment]
Regarding test coverage, I think, we have create a lot of tests too. We miss many important test cases. I examined some flows, we have only 2-3 tests for those flows but there should be more test cases for them. So, may be we can create ftos for them later on.

**Comment by kaustubh-nair** [comment]
I agree. We should aim for aroung 85% and pay special attention to edge cases

**Comment by alaxalves** [comment]
@jywarren Could you add me and @kaustubh-nair to Mapknitter's Collaborators team with "write" privileges so that I can create the things proposed [here](https://github.com/publiclab/mapknitter/issues/305#issuecomment-491815768) by @SidharthBansal ??

**Comment by jywarren** [comment]
Yeah!!! I just did.

**Comment by kaustubh-nair** [comment]
I'll start adding tests, since @alaxalves is doing https://github.com/publiclab/mapknitter/issues/598

**Comment by alaxalves** [comment]
> I'll start adding tests, since @alaxalves is doing #598

Thank you @kaustubh-nair I love DevOps, that's why I had to get #598 :smile: :smile: :smile:. Let me know if I can help you with anything. BTW, @cesswairimu said in https://github.com/publiclab/mapknitter/pull/578#issuecomment-492100825 that he started this testing stuff. Maybe you could take advantage of his work.
