### ISSUE TITLE
Split test env and production env in Travis

### ISSUE THREAD

**Issue by alaxalves** [publiclab/mapknitter#599]
### What happened just before the problem occurred

Currently our `travis.yml` file uses the `docker-compose.yml` file to run the test suite and whatever. But the problem is that our yml use the `mapknitter.env` file that defines the environment as production and not test. I feel like this might be the cause of some of our issues.

I feel like the best approach here is having multiple yaml files that explicitly defines the environment we'd want to lift, or if there's nothing that will differ that much just multiple env files will do the trick and use the same yml.

### Relevant URLs

https://github.com/publiclab/mapknitter/blob/main/.travis.yml
https://github.com/publiclab/mapknitter/blob/main/mapknitter.env
https://github.com/publiclab/mapknitter/blob/main/docker-compose.yml

### PublicLab.org username

@alaxalves

**Comment by alaxalves** [comment]
@publiclab/community-reps what you think of this?

**Comment by jywarren** [comment]
Hi, actually i think we need input from @icarito on this, as community-reps
are more focused on the community who use the website, rather than system
setup and configuration. Do take a look at how plots2 is set up here,
though, maybe this would help?
https://github.com/publiclab/plots2/tree/master/containers/

**Comment by alaxalves** [comment]
Just updated the comment @jywarren. Maybe @cesswairimu could help too, also I'll check on the plots2 config thnx

**Comment by alaxalves** [comment]
![image](https://user-images.githubusercontent.com/19597045/57727136-1ce52880-7667-11e9-9459-f89077b0a441.png)

Log in Travis available at: https://travis-ci.org/publiclab/mapknitter/builds/532203223?utm_source=github_status&utm_medium=notification

**Comment by IgorWilbert** [comment]
@alaxalves @jywarren I believe complete separation of `production`and `test` environments would be ultimately necessary to get rid of these errors. Is there any reason why they are tied?

**Comment by alaxalves** [comment]
> @alaxalves @jywarren I believe complete separation of `production`and `test` environments would be ultimately necessary to get rid of these errors. Is there any reason why they are tied?

I totally agree! It's a huge concern for PL rn.

**Comment by alaxalves** [comment]
> @alaxalves @jywarren I believe complete separation of `production`and `test` environments would be ultimately necessary to get rid of these errors. Is there any reason why they are tied?

This is being shown a lot problematic. Our current work at Rails 4 upgrade is being blocked due to this, check it out:
![image](https://user-images.githubusercontent.com/19597045/58328661-07ab8f00-7e09-11e9-88bc-fdb18b6664e9.png)

We have to get https://github.com/publiclab/mapknitter/pull/628 merged first than https://github.com/publiclab/mapknitter/pull/605 after this @cesswairimu can integrate it to https://github.com/publiclab/mapknitter/pull/578

**Comment by alaxalves** [comment]
Done in https://github.com/publiclab/mapknitter/pull/605/
