### ISSUE TITLE
ability to click on map to deselect image

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#60]

**Comment by ebarry** [comment]
this would be nice also.

**Comment by sashadev-sky** [comment]
This is now solved in my PR in LeafletDistortableImage: https://github.com/publiclab/Leaflet.DistortableImage/pull/158

Hopefully will be merged here soon too! 🎉

**Comment by sashadev-sky** [comment]
@jywarren should I close this if its resolved in LDI? Or add some kind of special tag to it like 'resolved downstream`?

**Comment by jywarren** [comment]
Yes let's close it, maybe linking to the PR if you haven't already! Thanks!

**Comment by sashadev-sky** [comment]
I can only link one issue to a PR but I added it in a new "Multiple Image" Epic I created and the merged PR is also referenced above. But yes closing via [Leaflet.DistortableImage/pull/158](https://github.com/publiclab/Leaflet.DistortableImage/pull/158).

As you have probably noticed I am really enjoy closing all of these issues 😅

Will get the toolbar updates into two sep branches and review rexagod's PR today though 💫
