### ISSUE TITLE
Configure Travis for system tests

### ISSUE THREAD

**Issue by kaustubh-nair** [publiclab/mapknitter#607]

**Comment by jywarren** [comment]
this would be great. I think they're only available in rails 5? or maybe
4... not sure.

**Comment by kaustubh-nair** [comment]
Yeah this we'll be done later. After we've got Rails 5 running

**Comment by alaxalves** [comment]
@kaustubh-nair Actually I'm not familiar with this. Could you explain me?

**Comment by kaustubh-nair** [comment]
Travis can be configured to run full stack system test to test javascript and everything. We can configure it to display screenshots of failed tests. Similar to what has been done for plots2 https://github.com/publiclab/plots2/pull/4888

**Comment by alaxalves** [comment]
> Travis can be configured to run full stack system test to test javascript and everything. We can configure it to display screenshots of failed tests. Similar to what has been done for plots2 [publiclab/plots2#4888](https://github.com/publiclab/plots2/pull/4888)

OOhhh, cool I knew those selenium tests as Acceptance tests and not System test :smile: :smile:

**Comment by jywarren** [comment]
This is looking great. What I'd love is to set up some system tests which can help us determine if dependabot JS dependencies are OK to merge. So, that make use of some of our JS deps in such a way as to help us keep them more up to date without having to manually test them out. cc @alaxalves 

Perhaps this is one of the things you both can consider now that Rails 5 is complete!

**Comment by kaustubh-nair** [comment]
list of tests here: https://github.com/publiclab/mapknitter/issues/967
