### ISSUE TITLE
Two search bars on mapknitter.org with id of "search-input"

### ISSUE THREAD

**Issue by rarrunategu1** [publiclab/mapknitter#616]
### What happened just before the problem occurred
There are two search bars with the same name and id.  I don't see a need for two search bars that do the same thing. 

![image](https://user-images.githubusercontent.com/29240939/57881283-e0443900-77ee-11e9-8e1a-aa458f11d3d8.png)

![image](https://user-images.githubusercontent.com/29240939/57881327-fe119e00-77ee-11e9-8065-f2180fcc7f40.png)

### Relevant URLs

https://mapknitter.org

### PublicLab.org username

parker_rose

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by jywarren** [comment]
Hi! Are you seeing a warning, or is there a bug when you use one of these inputs? I know browsers are getting more strict these days. Do both work the same, and do they both still work if we change the `id` of one of them?

Thank you!!

**Comment by rarrunategu1** [comment]
They both search the same information.  When you search on one and it returns the results, your search keyword appears in other search box as well. 
![image](https://user-images.githubusercontent.com/29240939/57888946-813bef80-7801-11e9-9d00-a99559b35f0b.png)
 If we changed the id what would we use the second search bar for?  It seems that they both search for any word in the map uploads to include author names.  For example, Nepal brought up a bunch of Nepal locations, Nepal titles but oddly enough it brought up AS220 in Providence.  I wondered why and it's because the upload says Nepali  in the about section of the map upload.  Maybe the search needs to be limited to title and author or should other keywords in the map upload be involved.  That's another issue but what do you think?

**Comment by rarrunategu1** [comment]
This is the other image that shows the AS220 reference of Nepal 
![image](https://user-images.githubusercontent.com/29240939/57889321-8483ab00-7802-11e9-9ef5-ea8802afdf4c.png)

**Comment by jywarren** [comment]
Hmm. I think we just didn't used to have a search bar in the nav bar. Maybe
now that we do, we can remove the lower one. It's not formatted properly
anyways. Let's just take it out!

**Comment by rarrunategu1** [comment]
Will do.
