### ISSUE TITLE
Add Leaflet FullHash object for dynamic URL 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/mapknitter#621]
Hi, this is a first-timers-only issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

🤔 What you will need to know.
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

📋 Step by Step
🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

📝 Update 

We have added leaflet-fullHash library in the bower and included the link to this library on the index page . 

Let's add leaflet-fullHash object which makes the URL dynamic in accordance to selected layers of the map . 

Add this lines of code after this line https://github.com/publiclab/mapknitter/blob/9aac51944a212e9c1c2cda06406c11f630d9c10a/app/views/maps/index.html.erb#L205  in **index.html.erb** : 

```js
var allMapLayers = {
      "BL1": baselayer1,
      "Purple": PurpleAirMarkerLayer,
      "STruth": SkyTruth,
      "FracTL": Fractracker,
      "ToxicR": ToxicRelease,
      "OdorR": OdorReport,
      "MapK": MapKnitter,
      "OIMPower": OpenInfraMap_Power ,
      "OIMapTelecom": OpenInfraMap_Telecom ,
      "OIMPetroleum": OpenInfraMap_Petroleum ,
      "OIMWater": OpenInfraMap_Water ,
      "JMincome": Justicemap_income,
      "JMamericanIndian": JusticeMap_americanIndian ,
      "JMasian": JusticeMap_asian ,
      "JMblack": JusticeMap_black,
      "JMmulti": JusticeMap_multi ,
      "JMhispanic": JusticeMap_hispanic ,
      "JMnonWhite": JusticeMap_nonWhite,
      "JMwhite": JusticeMap_white ,
      "JMplurality": JusticeMap_plurality ,
      "Clouds": clouds ,
      "cloudsclassic": cloudscls ,
      "precipitation": precipitation ,
      "precipcls": precipitationcls ,
      "rain": rain ,
      "raincls": raincls ,
      "snow": snow ,
      "pressure": pressure ,
      "pressurecontour": pressurecntr ,
      "temp": temp ,
      "wind": wind ,
      "Cities": city  ,
      "windrose": windrose 
    };

    var hash = new L.Hash(Mapknitterunique, allMapLayers);
```

💾 Commit your changes

🔀 Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, here is a great tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

🏁 Done Ask in comments for a review and **also add a screenshot of the address bar of browser showing URL** :)

Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update within a week of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance!

If this happens to you, don't sweat it! Grab another open issue.

Is someone else already working on this?
🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- If someone seems stuck, offer them some help! Otherwise, take a look at some other issues you can help with. Thanks!

🤔❓ Questions?
Leave a comment below!

Part of #510 :)

**Comment by sashadev-sky** [comment]
assigned to @konolga!

**Comment by Divyanshu29** [comment]
Is the issue still open? Can i contribute still?

**Comment by sashadev-sky** [comment]
@sagarpreet-chadha this issue has really not made sense to me for months now, and I think it is best if you just solve it at this point, because it is not productive to open PR then not respond to people's questions on it (tho that happens to all of us!!) But even when I tested it I couldn't find a difference so if you just did it you could show us.

Just want to be done w this one lmao

**Comment by sagarpreet-chadha** [comment]
Hey!
Apologies...had been going super busy with new LEL features and plots2 integration. 
It looks like LEL features have been removed from mapknitter although it is still in package.json.
@jywarren ...is there any reason for this?

I am assigning this issue to myself  but this issue will not be solved in the immediate future bcoz LEL is not there now.

PS: I promise this will be done, thanks for the patience! 😃

**Comment by jywarren** [comment]
Ah, no that wasn't intentional! Let's perhaps ping @cesswairimu about using
the new simple LEL constructor to do this in a way that'll be simpler than
the way it had been done? It's now documented nicely in the LEL readme.
Sagarpreet is working hard on geo features on plots2 so may not be as
available for this right away! Thanks, all!

**Comment by sagarpreet-chadha** [comment]
Infact LEL has evolved very much now. The issue is stating old API function. I am closing this issue.

Fyi, after adding these lines you should have selected a LEL layer on  map from the control bar in top-right corner, then check the browsers URL --- it will have the name of the layer you selected! Thanks!

**Comment by sashadev-sky** [comment]
@sagarpreet-chadha there was an issue connected to this I guess we'll need to close that too https://github.com/publiclab/mapknitter/pull/622 :/
