### ISSUE TITLE
Page number buttons formatted incorrectly

### ISSUE THREAD

**Issue by kaustubh-nair** [publiclab/mapknitter#623]
![Screenshot_20190520_202411](https://user-images.githubusercontent.com/30197132/58031037-3f7eb200-7b3d-11e9-8d42-7ea796f570ee.png)

**Comment by Danielshow** [comment]
Hey @kaustubh-nair, I think I can work on this if it has not been fixed

**Comment by kaustubh-nair** [comment]
Sure @Danielshow go ahead!

**Comment by sashadev-sky** [comment]
Closing this its been fixed! Don't have the exact PR #.
