### ISSUE TITLE
Warpable test failing

### ISSUE THREAD

**Issue by alaxalves** [publiclab/mapknitter#627]
### What happened just before the problem occurred

Test for Warpable is breaking.

### PublicLab.org username

@alaxallves

Check https://github.com/publiclab/mapknitter/pull/578/files#r285558211 and https://github.com/publiclab/mapknitter/pull/605#issuecomment-494199024

This test is blocking my work at #605 and consequently a lot of upcoming work.

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by cesswairimu** [comment]
also linking #625 might be related

**Comment by alaxalves** [comment]
@cesswairimu Is it breaking on the `main` branch or in https://github.com/publiclab/mapknitter/pull/578

**Comment by cesswairimu** [comment]
Yes it is...Could you please try on your end

**Comment by alaxalves** [comment]
Fixed at https://github.com/publiclab/mapknitter/pull/605/commits/654361e0e451ee3c473efde379c295ab50860b43
