### ISSUE TITLE
Fix singularization case for "images"

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#636]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/mapknitter/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

On [mapknitter.org](https://mapknitter.org) the number of images used to created a map is listed for each post, but if you come across a map with only 1 image you can see that "images" is not singularized here is as it should be:

<img width="941" alt="Screen Shot 2019-05-26 at 7 48 49 PM" src="https://user-images.githubusercontent.com/41092741/58388700-0b4d3a80-7ff0-11e9-9ef6-5821d052b24a.png">

## Solution

Let's fix this so the output for 1 image looks like this:

<img width="925" alt="Screen Shot 2019-05-26 at 7 47 43 PM" src="https://user-images.githubusercontent.com/41092741/58388712-38015200-7ff0-11e9-955a-42765fa3a864.png">

Update this line from this: https://github.com/publiclab/mapknitter/blob/dc96adae1b376e7a90a3410c535dd547230caf5e/app/views/maps/_list.html.erb#L26

to this:

```Ruby
<%= map.warpables.length %> <%= map.warpables.length == 1 ? "images".singularize : "images" %> | <%= map.comments.length %> comments
```

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo [README instructions](https://github.com/publiclab/mapknitter/blob/main/README.md)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by PoseidonSigmaX** [comment]
Hey, I'd like to work on this, shall I get started?
