### ISSUE TITLE
Image ordering in sidebar

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#638]
Option to sort the images based on
- [ ] Size of the file
- [ ] Name of the file
- [ ] Time of upload
- [ ] Based on the image placement on the map. i.e the topmost image must be placed on the top of the sidebar.

These can be arranged in descending as well as ascending order.

Steps to follow:
- [ ] Create a basic UI
- [ ] Implement the function of sorting

**Comment by divyabaid16** [comment]
@jywarren @gauravano Should I also implement the option for the user to drag and drop the image and arrange them in the order they want in the sidebar? This can be considered as manual sorting.

**Comment by gauravano** [comment]
Yeah, that would be good.
