### ISSUE TITLE
Change cursor to pointer

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#639]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [x] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [x] 📝 **Update**

![Selection_162](https://user-images.githubusercontent.com/32747809/58415913-989a9880-809d-11e9-8b62-74ac0840a6b9.png)

**Changes**: Chance cursor to pointer download and pan to this image
Make changes in file app/views/images/_index.html.erb Change 
https://github.com/publiclab/mapknitter/blob/dc96adae1b376e7a90a3410c535dd547230caf5e/app/views/images/_index.html.erb#L42
https://github.com/publiclab/mapknitter/blob/dc96adae1b376e7a90a3410c535dd547230caf5e/app/views/images/_index.html.erb#L43
- [x] 💾 **Commit** your changes

- [x] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [x] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by zelol** [comment]
Still open for first-timer? :)

**Comment by divyabaid16** [comment]
Yes @zelol you can work on this.
Thanks!

**Comment by joreneng** [comment]
Hi, is this still open?

**Comment by divyabaid16** [comment]
@zelol are you working on this?

**Comment by zelol** [comment]
@divyabaid16 Oops I forgot. I will work on it immediately. Sorry again.

**Comment by divyabaid16** [comment]
Go ahead on solving this @zelol 
And we will create another issue for you @joreneng 
Thanks!

**Comment by zelol** [comment]
@divyabaid16 Seems that it requires various installation and I honestly do not have the time right now.
I cannot work on it this week, too. I'll leave my place to @joreneng. Sorry again.

**Comment by divyabaid16** [comment]
No problem @zelol you can try some other time.
@joreneng would you like to work on this now?
Thanks!

**Comment by joreneng** [comment]
@divyabaid16 I'll work on it!

**Comment by metonymic-smokey** [comment]
Hey @divyabaid16 what's the status of this issue at present?
If no one else is working on it, I'd like to take it on as my first contribution to mapknitter!

**Comment by divyabaid16** [comment]
Since the user hasn't been active for more than a month, you can work on it. We would be glad to help you out.
Thanks!

**Comment by metonymic-smokey** [comment]
Cool!
Will get started. Currently trying to get the dev environment working on my system.

**Comment by metonymic-smokey** [comment]
@divyabaid16 I had a few small queries.
I'm working using the Codenvy environment for now.
1. I'm not able to locate the image you've linked in this answer. Where exactly is it located so I can re create this issue?
2.If I understood right, I have to change to a pointer, with the already existing tooltip text, shown when the pointer hovers over this image?

**Comment by metonymic-smokey** [comment]
@divyabaid16 got the dev env running locally! Sorry for the delay.
Could you please clarify the above?
Thanks!

**Comment by divyabaid16** [comment]
Okay, so now, follow the instructions to go to the image tab:
1. Click on "Make a Map+" option that is present on the front page. 
2. You will be redirected to a page where you can create the map. Add the title and the location.
3. The map corresponding to that location will open up. There, start by uploading an image. After you upload an image, you will get there 3 buttons. In that simply change the cursor to the pointer when the mouse hovers on them. 

> If I understood right, I have to change to a pointer, with the already existing tooltip text, shown when the pointer hovers over this image?

Yes!

**Comment by metonymic-smokey** [comment]
@divyabaid16 I've changed the cursor to pointer and made the commits on my fork.
I had to change _new.html.erb too along with _index.html.erb, since changing only _index.html.erb didn't change it to pointer.
Here are the screenshots:
![Download_later](https://user-images.githubusercontent.com/48997495/62857769-0b6af580-bd16-11e9-9e44-88a530cb30aa.png)
![pan_later](https://user-images.githubusercontent.com/48997495/62857778-1160d680-bd16-11e9-8072-5389b89076e7.png)
2 other things:
a.The tooltip text appears to the left of the page for Download and Pan right from the beginning. Does this happen to other users too on their local systems?
b.The title of my image,being rather long, clashes with the buttons. Is there a limit on the no. of characters for a title or so to avoid this?
This is the first screenshot of MapKnitter:
![download_before](https://user-images.githubusercontent.com/48997495/62857831-45d49280-bd16-11e9-94da-e152d9db8584.png)
So wanted to ask if these happen with other users on their local systems too.
If you're okay with this, I'll open a PR.
Thanks!

**Comment by divyabaid16** [comment]
These changes are great. 
Firstly open a PR to change the cursor to a pointer. 

>The tooltip text appears to the left of the page for Download and Pan right from the beginning. Does this happen to other users too on their local systems?

For this, I have already made a PR #923 which solves this problem.

And for the last one, 
You can create a separate issue and then create the PR for the same. I guess limiting is not a good option since while uploading we are not changing the name of the file and it has the same name as it is stored in the laptop. So rather, we can make the long name append down to the next line so that overlapping problem can be solved. 
What are your views on this?

Thanks and welcome to Public Lab :balloon:

**Comment by metonymic-smokey** [comment]
I'll create an issue about the second point @divyabaid16 .
I'll take some time to try and resolve the issue since I'm first exploring the codebase, etc. but I'll try my best to do it. I'll revert to the maintainers in case of any doubts.
In the meantime, I'll look for similar issues I could solve.

Thanks a lot!
