### ISSUE TITLE
maps don't preserve zoom bounds upon initial save after finding location

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#64]
When I go to make the map after I've found my location, it zooms me out away from the site.

**Comment by jywarren** [comment]
Can you post some screenshots of the sequence of events? Is there a page
load in the middle? I think I know what's going on but just want to be
sure.

**Comment by steviepubliclab** [comment]
I can in a second when I do it again, I just found my site manually.. but now I'm uploading infragram images and getting this 

![not acceptable](https://cloud.githubusercontent.com/assets/7490478/5984509/91bc0ba8-a89c-11e4-9464-55373dd4e800.png)

**Comment by btbonval** [comment]
Instead of "Not Acceptable", we should probably have Earl of Lemongrab.
http://media2.giphy.com/media/QUaqJRizED5NC/200_s.gif

**Comment by steviepubliclab** [comment]
Ha! ok but whyyy :(

**Comment by btbonval** [comment]
Sorry I'm not actually familiar enough with mapknitter. I just get all these issues emailed to me ;)

Maybe you should create a separate issue for the "Not Acceptable" problem, though. It seems unrelated to the zoom problem in this issue.

**Comment by jywarren** [comment]
Hi, Stevie - please file different bugs in separate issues to help us keep debugging well organized. But the upload issue is not a bug -- we've disabled uploading in this test version for now. Sorry, i know the email had a lot of info and you might've missed that. I'm going to delete your image so this issue stays tidy.

**Comment by jywarren** [comment]
Ah I see you've already moved it; copying my comment over to #65

**Comment by steviepubliclab** [comment]
ok, Going to make a map of New Orleans City Park. I type in the location on the right and it pulls me right to my location: 
![city park](https://cloud.githubusercontent.com/assets/7490478/5984734/c91eba6c-a89e-11e4-9f56-52bc805b0f17.png)

Then when I click create map, it zooms me back out to the city of New Orleans:
![all map](https://cloud.githubusercontent.com/assets/7490478/5984742/d9dca850-a89e-11e4-8731-4e4484b52ee0.png)

**Comment by jywarren** [comment]
Great, I think this is now fixed; can you test?

**Comment by steviepubliclab** [comment]
Yes! Neat! this all looks great!

**Comment by jywarren** [comment]
thanks! very exciting.
