### ISSUE TITLE
[URGENT] API key commited?

### ISSUE THREAD

**Issue by tech4GT** [publiclab/mapknitter#646]
<img width="681" alt="Screen Shot 2019-05-29 at 8 13 30 AM" src="https://user-images.githubusercontent.com/25617855/58525550-becd4f00-81e9-11e9-85fd-e382bca74b19.png">
The email says that it is contained here https://github.com/publiclab/mapknitter/blob/cf1015ae69ebc3640e886634329775e683227edc/app/models/map.rb

@sashadev-sky @jywarren Is this intentional??

**Comment by tech4GT** [comment]
<img width="666" alt="Screen Shot 2019-05-29 at 8 18 10 AM" src="https://user-images.githubusercontent.com/25617855/58525710-59c62900-81ea-11e9-9048-1edb358a3022.png">

**Comment by jywarren** [comment]
Was this maybe pushed by accident?

https://github.com/publiclab/mapknitter/commits/cf1015ae69ebc3640e886634329775e683227edc/app/models/map.rb

It should be ok and we should be able to turn off that key, but good catch
if it wasn't intentional!

**Comment by jywarren** [comment]
Hi! Ok I checked and it's just a maps API key. Not a big deal. Thanks
anyway!!!

**Comment by tech4GT** [comment]
Glad to hear it! :smile:
