### ISSUE TITLE
Update Developers section in Readme

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#647]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** 

In README.md add these in the developers section, i.e after line no 142
```
* Find lots of info on contributing at http://publiclab.org/wiki/developers
* Join our gitter chat at https://gitter.im/publiclab/publiclab
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by nycbeardo** [comment]
Will try my hand at this!

**Comment by spShashankGit** [comment]
I would like to claim this issue if not already claimed.

**Comment by spShashankGit** [comment]
I tried commit my fix to the main branch as well as to a newly created branch called 'first-timer-issue-647' but both the times I got error msg saying 'remote: Permission to divyabaid16/mapknitter.git denied to spShashankGit.' 
Could you please let me know what I am missing?
I am sorry to bother you over such a trivial problem :(

**Comment by spShashankGit** [comment]
Above problem is solved.
I did not fork your repo hence the whole problem.
All good now!

**Comment by sashadev-sky** [comment]
@spShashankGit sorry to tell you this issue already has an open PR for it that is ready for merge. Are you still looking for an FTO? If so you can add your name to the FTO issues tracker in https://github.com/publiclab/plots2/issues/4963 and say you want something for Mapknitter specifically and we'll assign you. 

Or you can grab this open FTO from the leaflet-environmental-layers repo: publiclab/leaflet-environmental-layers#177
