### ISSUE TITLE
Images not acceptable 

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#65]
I get this when I try to upload infragram images: 
![not acceptable](https://cloud.githubusercontent.com/assets/7490478/5984693/414fb762-a89e-11e4-9d45-3ffa3c645580.png)

**Comment by jywarren** [comment]
Hi! The upload issue is not a bug -- we've disabled uploading in this test version for now. Sorry, i know the email had a lot of info and you might've missed that. I'm going to delete your image so this issue stays tidy.
