### ISSUE TITLE
Cloud Setup - add Codenvy

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#654]
**Codenvy** - workspaces are disabled as of tomorrow so the whole **AWS** section will have to be removed and replaced with Codenvy.

**Comment by jywarren** [comment]
Thanks! +1 CodeEnvy, folks have been using it! It's not perfect but it does
work.

**Comment by sashadev-sky** [comment]
@jywarren they probably setup before the merge conflict then! It works just I think its good to consider a way where that doesn't happen. I also spend a lot of time with FTOs so its been on my mind how to make setup easier with rails. 

Maybe codeEnvy has a way to change the default branch. I will check ☺️. I also was thinking, have you ever used **Gitpod**? I think it might be a complete game changer. It has the easiest interface and is so fast.

You download the github extension then every issue will have a gitpod button to open the repo for it:

<img width="1098" alt="Screen Shot 2019-05-31 at 6 52 43 PM" src="https://user-images.githubusercontent.com/41092741/58738800-55aa2f00-83d5-11e9-918c-926c58679e55.png">

then the interface doesn't even make you feel like you're in the cloud. And is directly integrated with Github. So theres no "middle man", logging in, account setup, etc.:

<img width="1635" alt="Screen Shot 2019-05-31 at 6 53 59 PM" src="https://user-images.githubusercontent.com/41092741/58738886-b0438b00-83d5-11e9-9bd5-1ffd020e9244.png">

<img width="360" alt="Screen Shot 2019-05-31 at 6 56 57 PM" src="https://user-images.githubusercontent.com/41092741/58738951-e6810a80-83d5-11e9-99a7-69f779dc615a.png">

**Comment by gauravano** [comment]
Hey @sashadev-sky Gitpod looks great. They have an Open source plan too which gives 100 hrs/month. If the # of hours is sufficient then, we can think about it too?

**Comment by jywarren** [comment]
Oh my gosh it does look nice!
