### ISSUE TITLE
Understanding/Upgrading the image upload feature

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/mapknitter#656]
### What happened just before the problem occurred
I am upgrading Rails from 3.2 to 4.2. The image upload feature is not working right now, nothing happens when you hit the upload button.
![images](https://user-images.githubusercontent.com/17081074/58700142-fd106d00-83a7-11e9-9afa-b7ac6100144f.gif)
Nothing is registered in rails logs as well as js so its hard to debug :confused: .

### Relevant URLs
https://github.com/publiclab/mapknitter/pull/578

### Way forward
I will be brainstorming here on the possible fixes I have tried and at the same point try and understand more how the upload process works. Any input or direction is appreciated :slightly_smiling_face:

**Comment by cesswairimu** [comment]
There was a confusion on what the create action  https://github.com/publiclab/mapknitter/blob/main/app/controllers/images_controller.rb#L26-L43 . So when changing from to strong parameters. I passed all the warpable attributes in the params hash like so
```
def image_params
params.require(:warpable).permit( :parent_id, :map_id, :image_content_type ...
end
```
That did not work. I tried a couple of things but the next "correct" path I followed was to leave it as is and just have mass assignment security in the warpable model Here is that commit https://github.com/publiclab/mapknitter/pull/578/commits/8282d5254308bb85cf6b7d9e0708bef05486b2ef. It is what is currently in the branch it is not working but the images_controller_tests are passing which makes me think it is a javascript error(not sure) but looking into that. Any pointers are appreciated.

**Comment by cesswairimu** [comment]
Pinging @jywarren @gauravano @sashadev-sky any pointers? Thanks.

**Comment by sashadev-sky** [comment]
@cesswairimu I pulled your branch and made commit suggestion that should fix it! If that works you, you understand the upload feature and it was just a bug 👍👍

**Comment by cesswairimu** [comment]
Thanks so much @sashadev-sky for taking a look. Giving it a try in a few.

**Comment by cesswairimu** [comment]
Closing this. Thanks again @sashadev-sky :raised_hands:
