### ISSUE TITLE
OAuth providers uses PL system for authentication

### ISSUE THREAD

**Issue by kaustubh-nair** [publiclab/mapknitter#657]
Clicking on Twitter/Github/Google login uses the public lab authentication system
Is this something to be done in the future?

**Comment by kaustubh-nair** [comment]
@SidharthBansal @jywarren

**Comment by jywarren** [comment]
Sorry, is there a problem? We want the user accounts to be run out of PL.org, and to enable using PL.org's OAuth -- i think this is working now, is it not? 

Thanks @kaustubh-nair !!!

**Comment by kaustubh-nair** [comment]
@jywarren  Ah I see how it works now...
I got a little confused because I'm logged in to my PL account that uses Github as the Oauth provider, mapknitter would log in to the same PL account no matter which provider used.
So if I'm already logged in on PL, twitter/google/github/facebook yields the same account on mapknitter.
So I guess this is not a problem? we should be okay as long as it yields the logged in account?

**Comment by jywarren** [comment]
Ah, yes, that is the idea. If @SidharthBansal has anything to add, though,
I defer to him, as he wrote the system! Thanks!
