### ISSUE TITLE
Use exif.js to attempt to place images 

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#67]
Code for this may already exist in Vidun's work, but I'm not sure if it uses exif.js -- the new Mapmill does, however: https://github.com/publiclab/mapmill

This is partially working; sandbox it here: http://mapknitter.org/maps/exif-test

**Comment by jywarren** [comment]
This is largely working now! Much refactoring and now pushing to production!!!

**Comment by jywarren** [comment]
Still would like to enable rotation and altitude scaling, and ALSO we need to change the scale of the image so that if it's placed at the wrong zoom level, it doesn't attempt to place an image across all of north america. Maybe a quick fix would be a default zoom before initiating -- only if we're too zoomed out?

**Comment by xvidun** [comment]
Hi everyone,

Sorry for being out of touch lately, have been busy with semesters.

I realised that GPS placement is working only for lat/long placements in
MapKnitter 2, the summer work took care of most of the features mentioned.
I think what you mentioned above was already taken care of, if you are at a
wrong zoom level and you attempt to place an image, the image would still
get placed with the correct scale only if your zoom is too far off you
wouldn't be able to see your image unless zoomed to the correct level.

Please do ping me if anything is required from my end.

Thanks.
