### ISSUE TITLE
Add margin to sidebar content

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#673]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [x] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [x] 📝 **Update** 

![Selection_169](https://user-images.githubusercontent.com/32747809/59086209-aa423280-891e-11e9-9e6b-2ae2b4207865.png)

The sidebar content overlaps the sidebar header. It can be seen as the border coming in between the contents of the header.

Add margin-top to the sidebar contents to solve the problem. 

https://github.com/publiclab/mapknitter/blob/03deef103df0d76a84c6de1a3c73e9712fd6f539/app/assets/stylesheets/maps.css.scss#L115

```
margin-top: 15px;
```
- [x] 💾 **Commit** your changes

- [x] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [x] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by theghostyced** [comment]
Hi @divyabaid16.. Has someone else claimed this yet? If not I would love to do it
