### ISSUE TITLE
README Update Mapknitter spelling

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#676]
### What happened just before the problem occurred

We have at least 4 different names for mapknitter in the README:

- MapKnitter 2

- MapKnitter

- Mapknitter

- Map Knitter (This one is in the license!)

Can we standardize to one name? I think Mapknitter is sensible?

**Comment by sashadev-sky** [comment]
@publiclab/mapknitter-reviewers @gauravano @jywarren

**Comment by gauravano** [comment]
Is there any reason for MapKnitter 2? If not major rewrite or so, then agree with Mapknitter.

**Comment by sashadev-sky** [comment]
I think its because there was once a version of it and we're revitalizing it! In `bower.json` its registered as mapknitter though (not sure if that matters)

It wouldn't be a huge update. Its mentioned in the actual library only a few times

**Comment by sashadev-sky** [comment]
@jywarren Confirmed MapKnitter. Will open PR.
