### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by kaustubh-nair** [publiclab/mapknitter#679]
While trying to login on localhost I get the error
```
undefined method `+' for nil:NilClass
app/controllers/sessions_controller.rb:43:in `create'
```

**Comment by kaustubh-nair** [comment]
@publiclab/mapknitter-reviewers Can anyone please try this out and confirm it not working?

**Comment by cesswairimu** [comment]
Is this for the upgrade? If so I already fixed that.

**Comment by kaustubh-nair** [comment]
No this is happening on the main branch as well

**Comment by cesswairimu** [comment]
Oh gotcha. This was my fix for upgrade  https://github.com/publiclab/mapknitter/pull/578/commits/934dc8f7c50c2ea0e390f437684f30ea99132b2a maybe it could help whoever takes up to fix the issue

**Comment by kaustubh-nair** [comment]
Ah awesome that works
Thanks! @cesswairimu!

**Comment by kaustubh-nair** [comment]
Looks like it happened when @alaxalves changed the scope of the variables here using rubocop's autofix feature https://github.com/publiclab/mapknitter/commit/713e387bdbe8baaa64847dadf552ec29e4a0b2aa#diff-d5241d488259f32ecbe2f636133e5dda
@publiclab/mapknitter-reviewers Just a heads up, please be careful while autofixing rubocop errors!

**Comment by cesswairimu** [comment]
Good catch @kaustubh-nair , could that be a reason why `development` branch is failing on unstable?

**Comment by jywarren** [comment]
Will this need a fix, then? Thanks for the catch!

**Comment by kaustubh-nair** [comment]
Yes I think it needs a fix but I also think it's kind of weird that login works for `main`

**Comment by kaustubh-nair** [comment]
Oh turns out it doesn't work on `main` either
