### ISSUE TITLE
Correct stable url.

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/mapknitter#683]
The stable url given in the readme file https://github.com/publiclab/mapknitter/blob/main/README.md  is for unstable. Change the url under  **Staging infrastructure and testing** where we have

```
We also have a stable build at http://mapknitter-unstable.laboratoriopublico.org/ which builds off of our main branch. 
```
to

```
We also have a stable build at http://mapknitter-stable.laboratoriopublico.org/ which builds off of our main branch
```

**Comment by jywarren** [comment]
cc @icarito just FYI - and let's merge this!

**Comment by amac714** [comment]
Hello, I am a first timer. Can I work on this?

**Comment by cesswairimu** [comment]
Hi @amac714, yeah sure go ahead
