### ISSUE TITLE
Add chat-in-different-ways badge to README

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#688]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/mapknitter/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

We want to add a new badge to the README file:

[![Join the chat at https://publiclab.org/chat](https://img.shields.io/badge/chat-in%20different%20ways-blue.svg)](https://publiclab.org/chat)

## Solution

At the top of the README, where you'll find other badges, lets add the following line:

```
[![Join the chat at https://publiclab.org/chat](https://img.shields.io/badge/chat-in%20different%20ways-blue.svg)](https://publiclab.org/chat)
```

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo [README instructions](https://github.com/publiclab/mapknitter/blob/main/README.md)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by sashadev-sky** [comment]
assigned to @st3v0o!

**Comment by gowtham5699** [comment]
Can you assign me? I'd like to work on it.

**Comment by sashadev-sky** [comment]
@gowtham5699 all yours!! Thank you :)

**Comment by gowtham5699** [comment]
@sashadev-sky  Thank you so much!!! I learned how to push commits to github.
I tried to push it yesterday but it was unassigned, so didn't have the access.
Now its done.

It would be so kind of you, if you can walk me through what i can do next.

**Comment by sashadev-sky** [comment]
@gowtham5699 the labels don't have any effect on permissions their just for organization! I don't see any PRs from you, so i'll paste the instructions I usually provide for making a PR:

1) Fork the main repo from the main page https://github.com/publiclab/mapknitter, otherwise you'll only get anonymous credit
2) clone your forked version by clicking the "clone or download" button - copy paste the url given and use the command `$ git clone <paste_url>` locally
3) Follow the README instructions for any local setup (technically you don't need any local setup because you're updating the README not database, etc. - but you're welcome to give setup a try if you'd like)
4) Make your changes on a new feature branch (create this with `$ git checkout -b <new_branch_name` and use `$ git branch` to make sure you are on this branch)
5) `$ git push origin <new_branch_name` to submit a pull request then visit the main repo page on Github and you'll see a prompt to create your PR

Let me know if you have more questions :)

**Comment by gowtham5699** [comment]
@sashadev-sky  PR created. Please Review.
