### ISSUE TITLE
Upload modal to list uploaded images.

### ISSUE THREAD

**Issue by xvidun** [publiclab/mapknitter#7]
Should we have the upload modal show the list of uploaded images. This would be especially useful when there are a lot of images, providing info like locked, hidden or anything that would be relevant. Options to delete images could also be provided using the in the list.

Edit:
Comments from research note:

"Another thing is that as we transition to just showing all images for your viewport, rather than having people create a map which "contains" images, the list of images may just be those currently shown in your viewport, which could update whenever you move the viewport. This does complicate ordering (which then has to be ordered in relation to any nearby image... the order index numbering would have to contain all images globally in MapKnitter), but we can probably put off thinking too hard about that for the time being since I don't think we have someone working on ordering. Perhaps at that time, we'd allow you to order upon assembling a set of images to export, and store just local (not global) order in the Export record. Or, we could (gasp) use decimals for order, and just allow images to be ordered with near-infinite precision, never having to "run out of integers" when ordering, the way CSS breaks down. Perhaps we could use a rough starting order # based on extent, which maps global size to some initial order decimal." - jywarren

"As we get into the map annotations with embedded pictures/notes/audio, some sort of file management zone seems to become important. Maybe the map image zone isn't the place to play with that.
you'll have to sell me on the idea of only listing images in the current window area-- it sounds like a "bouncy" menu that will change as I move around the map and drive me kinda nuts with its rapid movement. I'm thinking of menus on phones that change between the time I think to touch them and when my finger gets there (think Google Maps suggestions). I understand that when people get to lots and lots of images in Mapknitter a "master list" may get a bit unwieldy. I think that can be manageable if the correspondence between image in map and image in list is maintained by highlighting images on the map when clicking on the list and vise versa." - mathew

[Gsoc update link](http://publiclab.org/notes/xvidun/05-28-2014/gsoc-update-week-1)

**Comment by jywarren** [comment]
fixed in MapKnitter 2
