### ISSUE TITLE
send an "intro" email with links to your map, edit pages, docs, on map creation

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#71]

**Comment by jywarren** [comment]
@ebarry and @steviepubliclab - can I ask for some help drafting this email? It'd go to any new user and perhaps once (the first time) to all users.

**Comment by gauravano** [comment]
@publiclab/community-reps any progress regarding this issue, you want to add here? Thanks!

**Comment by jywarren** [comment]
I think we should wrap this up and focus on the welcome email for PublicLab.org esp since we are probably going to continue to rely on the auth system there. Thanks, Gaurav!

**Comment by gauravano** [comment]
Great!
