### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by kaustubh-nair** [publiclab/mapknitter#711]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** 

In `README.md` file, 
1. Replace `sudo npm install -g bower` with `sudo npm install -g yarn` (In the prerequisites section)
2. Replace `bower install` with `yarn install` (In the standard installation section)

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

**Comment by CheykoBlack** [comment]
Hi! I'm a first time contributor to any open source project and have to do so for my first summer internship (yay!) and I would like to claim this as my first practice step. =D Please and thank you!

**Comment by CheykoBlack** [comment]
I went ahead and submitted a pull request, had a more experienced employee help me with the git commands and filling out the thread post attached with the pull request but I did everything else myself so it wouldn't be surprising if I messed something up. Just let me know, and thank you so much! =D
