### ISSUE TITLE
"log in" button not working

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#719]
### What happened just before the problem occurred
I'm on google chrome, and went to Mapknitter to search for some maps. I'm not logged in on this computer, but when I tried to use the button on the left-hand side of the page, it wasn't working. I kept getting a flash of a dropdown, but nothing happens when I click it.

![Screen Shot 2019-06-18 at 10 06 49 AM](https://user-images.githubusercontent.com/7490478/59691604-44249d80-91b1-11e9-95df-071ba942e72c.png)

### PublicLab.org username
stevie

**Comment by kaustubh-nair** [comment]
Thanks for the issue @steviepubliclab 

https://github.com/publiclab/mapknitter/blob/5673c037ea653bef190cc2c02aa38d870a69069d/app/views/maps/index.html.erb#L23
The `mini-login` event seems to be missing here

**Comment by jywarren** [comment]
Thanks! @divyabaid16 would you be able to address this in your #717 PR? Thanks, all.

**Comment by divyabaid16** [comment]
Sure!

**Comment by divyabaid16** [comment]
I have fixed the issue @jywarren 
Thanks!

**Comment by jywarren** [comment]
awesome, thank you!!!!

**Comment by jywarren** [comment]
I believe we have to find a new place for the "anonymous" option - that is, perhaps prompt people to log in and explain the benefits, when they click the new "create a map" button on the new front page. @divyabaid16 would you be interested in taking this up?

**Comment by divyabaid16** [comment]
Yes @jywarren, I will do it now.
Thanks!
