### ISSUE TITLE
Jenkins and Travis are inconsistent with each other

### ISSUE THREAD

**Issue by kaustubh-nair** [publiclab/mapknitter#732]
Based on my changes in https://github.com/publiclab/mapknitter/pull/725, it seems jenkins and travis are not in sync
The the pr linked above, Jenkins is passing but Travis is failing.
Also in the Yarn upgrade, #702 Travis is passing but Jenkins is failing.
Are they running on the same environment? 
This is a critical issue and we should be fixing this as soon as possible

**Comment by kaustubh-nair** [comment]
Pinging @alaxalves @jywarren @icarito here

**Comment by alaxalves** [comment]
@kaustubh-nair Can you post the config file for Jenkins here? I could take a look into it

**Comment by kaustubh-nair** [comment]
@alaxalves So jenkins runs on `production` and Travis runs on `test`. I guess that makes sense? 
I think the only problem is that our current `database.yml.example` does not work on Travis, which is causing the problems. I've made a pull request https://github.com/publiclab/mapknitter/pull/725 to try and fix it on Travis but it doesn't seem to be working. Can you have a look at it?

**Comment by alaxalves** [comment]
> @alaxalves So jenkins runs on `production` and Travis runs on `test`. I guess that makes sense?
> I think the only problem is that our current `database.yml.example` does not work on Travis, which is causing the problems. I've made a pull request #725 to try and fix it on Travis but it doesn't seem to be working. Can you have a look at it?

I was just guessing, because this was happening on Travis, anyway I'll into it. :D

**Comment by alaxalves** [comment]
@icarito Can you give us input on this? Where can I find the Jenkins scripts? Do I have access to those?

**Comment by gauravano** [comment]
Solved in https://github.com/publiclab/mapknitter/pull/891. @kaustubh-nair @alaxalves please verify. Thank you!
