### ISSUE TITLE
Annotation js not loading

### ISSUE THREAD

**Issue by kaustubh-nair** [publiclab/mapknitter#734]
The js files for annotations are not loading correctly
This might be an ordering issue similar to https://github.com/publiclab/mapknitter/pull/733 
Relevent errors:
![DeepinScreenshot_select-area_20190622114122](https://user-images.githubusercontent.com/30197132/59960219-ba434000-94e2-11e9-9c2d-7e06412acc5c.png)

**Comment by kaustubh-nair** [comment]
I think I've got this fixed, but the maps are still not loading. I'm guessing it's still because of https://github.com/publiclab/mapknitter/issues/742

**Comment by jywarren** [comment]
I think this is unrelated and we now have a fix for #742 in #786 ! Were you working in a PR on getting the annotations system running? I thought i saw that somewhere... but can't remember! 😆

**Comment by kaustubh-nair** [comment]
I hadn't sent a pull request since there wasn't a way to test it properly before fixing #742. I fixed the dangling references that you can see in the screenshot, but still I don't think the annotations are working. I'll send a pull now

**Comment by kaustubh-nair** [comment]
Okay weird. Annotations are working on stable now. If anyone else is facing this issue feel free to reopen this

**Comment by jywarren** [comment]
I had to rework the asset pipeline ordering and nesting for the 3.0 launch
so maybe that fixed it?
