### ISSUE TITLE
Image deletion menu with icons

### ISSUE THREAD

**Issue by rarrunategu1** [publiclab/mapknitter#741]
### What happened just before the problem occurred
Usually when you click on an image you upload on a map a menu with icons, including the trash icon pop up so that you can edit your image.  It's no longer showing when running locally.  If you double click on the image it just zooms in on the map.  If you drag and drop an image it works on that image but that in itself has another issue which I'll open up.

### Relevant URLs

http://localhost:3000/maps/testmap

### PublicLab.org username

parker_rose

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by divyabaid16** [comment]
Even I had this issue but I forgot that I had created a map anonymously. 
The trash icon is only shown when the user is logged in and not in an anonymous map.
Maybe you haven't logged in? Can you please check it once?

Hi @rarrunategu1 this is working for me

I'm getting the trash icon.

![Selection_192](https://user-images.githubusercontent.com/32747809/60164373-137cdd80-981b-11e9-96c8-9a38ba2916e3.png)

**Comment by rarrunategu1** [comment]
@divyabaid16 it looked like I was logged in but when I logged out and in again, it worked.  Thanks.
