### ISSUE TITLE
Multiple map images will not display.  Only one image at a time.

### ISSUE THREAD

**Issue by rarrunategu1** [publiclab/mapknitter#742]
### What happened just before the problem occurred
testing a map upload and realized it didn't have deletion menu which is mentioned on issue #741 , but when I drag and drop it had that option but the picture did not seem to save but it did.  Once I deleted the first image the drag and drop image showed up but not the other ones.  This image however no longer had the pop up menu option to delete

### Relevant URLs

http://localhost:3000/maps/testmap

### PublicLab.org username

parker_rose

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by kaustubh-nair** [comment]
This might be similar to https://github.com/publiclab/mapknitter/issues/728, caused to due incorrect ordering of assets
I see this on the console
```
TypeError: t is null
leaflet.self-3650930c25d93e8dc7e5d25ec5d3ce44172f088a4a7f405342064e1f3463bf32.js:6:13433
    project http://localhost:3000/assets/leaflet/dist/leaflet.self-3650930c25d93e8dc7e5d25ec5d3ce44172f088a4a7f405342064e1f3463bf32.js?body=1:6
    latLngToPoint http://localhost:3000/assets/leaflet/dist/leaflet.self-3650930c25d93e8dc7e5d25ec5d3ce44172f088a4a7f405342064e1f3463bf32.js?body=1:6
    project http://localhost:3000/assets/leaflet/dist/leaflet.self-3650930c25d93e8dc7e5d25ec5d3ce44172f088a4a7f405342064e1f3463bf32.js?body=1:6
    _latLngToNewLayerPoint http://localhost:3000/assets/leaflet/dist/leaflet.self-3650930c25d93e8dc7e5d25ec5d3ce44172f088a4a7f405342064e1f3463bf32.js?body=1:6
    latLngToNewLayerPoint http://localhost:3000/assets/leaflet-distortableimage/dist/leaflet.distortableimage.self-62eeb4dd85546124b3cc68a68ad7bd2d82cf9990a1d923f3197662c20dac26a8.js?body=1:347
    _calculateProjectiveTransform http://localhost:3000/assets/leaflet-distortableimage/dist/leaflet.distortableimage.self-62eeb4dd85546124b3cc68a68ad7bd2d82cf9990a1d923f3197662c20dac26a8.js?body=1:411
    _animateZoom http://localhost:3000/assets/leaflet-distortableimage/dist/leaflet.distortableimage.self-62eeb4dd85546124b3cc68a68ad7bd2d82cf9990a1d923f3197662c20dac26a8.js?body=1:349
    fire http://localhost:3000/assets/leaflet/dist/leaflet.self-3650930c25d93e8dc7e5d25ec5d3ce44172f088a4a7f405342064e1f3463bf32.js?body=1:6
    _animateZoom http://localhost:3000/assets/leaflet/dist/leaflet.self-3650930c25d93e8dc7e5d25ec5d3ce44172f088a4a7f405342064e1f3463bf32.js?body=1:6
    _tryAnimatedZoom http://localhost:3000/assets/leaflet/dist/leaflet.self-3650930c25d93e8dc7e5d25ec5d3ce44172f088a4a7f405342064e1f3463bf32.js?body=1:6
    <anonymous> self-hosted:991
```

But I'm not familiar with the `leaflet` modules. @publiclab/mapknitter-reviewers Any idea which dependencies leaflet and LDI has?

**Comment by jywarren** [comment]
Is this only in development, since in production all assets are precompiled? Thanks!

**Comment by jywarren** [comment]
Can you point at a page where this is happening on stable? Thanks!

**Comment by jywarren** [comment]
Trying to find an online example of this issue -- perhaps in http://mapknitter-stable.laboratoriopublico.org/maps/ceres--2/ -- yes!

![image](https://user-images.githubusercontent.com/24359/60528883-69da9800-9cc3-11e9-864d-ae503e0d9c6d.png)

No images are showing. Great. reproduced!

**Comment by jywarren** [comment]
Error looks like:

```js
Uncaught TypeError: Cannot read property 'lat' of undefined
```

in a segment doing: `new L.latLng(l.nodes[3].lat,l.nodes[3].lon)`

Here's a bit of context although mine is minified... not so readable:

`],!0),h.html("<i class='fa fa-download'></i>")},c[0].src=$(".img-download-"+l.id).attr("data-image")});var e=[new L.latLng(l.nodes[0].lat,l.nodes[0].lon),new L.latLng(l.nodes[1].lat,l.nodes[1].lon),new L.latLng(l.nodes[3].lat,l.nodes[3].lon),new L.latLng(l.nodes[2].lat,l.nodes[2].lon)],i=new L.DistortableImageOverlay(l.srcmedium,{keymapper:!1,corners:e,mode:"lock"}).addTo(window.mapKnitter._map);bounds=bounds.concat(e),window.mapKnitter._map.fitBounds(bounds),images.push(i),i.warpable_id=l.id,s.readOnly||(L.DomEvent.on(i._image`

OK! We're looking at this:

https://github.com/publiclab/mapknitter/blob/cc7e9242f559ee53b581f94c8b43adfcc8c28229/app/assets/javascripts/mapknitter/Map.js#L91-L108

**Comment by jywarren** [comment]
I think it's because we're trying to run this code on images that haven't been placed yet, so have no nodes. Something upstream may have changed... but the easy fix for now is to just change this line to ensure we have 4 nodes per image:

https://github.com/publiclab/mapknitter/blob/cc7e9242f559ee53b581f94c8b43adfcc8c28229/app/assets/javascripts/mapknitter/Map.js#L44

I'll do this and see if it works, but then we'll investigate further. Why would there be images with only 2 nodes?

**Comment by jywarren** [comment]
Aha - something bad is going on with our JSON at http://mapknitter-stable.laboratoriopublico.org/maps/ceres--2/warpables.json

```
"nodes":"[#\u003cNode id: 2593754, color: \"black\", author: \"anonymous\", lat: -0.377664063648e2, lon: 0.1449828654528e3, way_id: 0, order: 0, created_at: \"2019-02-27 23:13:20\", updated_at: \"2019-02-27 23:13:20\", name: \"\", description: \"\", map_id: 0, way_order: 0, body: nil\u003e, #\u003cNode id: 2593755, color: \"black\", author: \"anonymous\", lat: -0.377650239004e2, lon: 0.1449831980467e3, way_id: 0, order: 0, created_at: \"2019-02-27 23:13:20\", updated_at: \"2019-02-27 23:13:20\", name: \"\", description: \"\", map_id: 0, way_order: 0, body: nil\u003e, #\u003cNode id: 2593756, color: \"black\", author: \"anonymous\", lat: -0.377652020107e2, lon: 0.1449844533205e3, way_id: 0, order: 0, created_at: \"2019-02-27 23:13:20\", updated_at: \"2019-02-27 23:13:20\", name: \"\", description: \"\", map_id: 0, way_order: 0, body: nil\u003e, #\u003cNode id: 2593757, color: \"black\", author: \"anonymous\", lat: -0.377665844718e2, lon: 0.1449841207266e3, way_id: 0, order: 0, created_at: \"2019-02-27 23:13:20\", updated_at: \"2019-02-27 23:13:20\", name: \"\", description: \"\", map_id: 0, way_order: 0, body: nil\u003e]"
```

Weird!

**Comment by jywarren** [comment]
These nodes are being inserted as Ruby objects and not JSONified...

**Comment by jywarren** [comment]
Maybe something in Rails 4 changed here: 

https://github.com/publiclab/mapknitter/blame/main/app/controllers/images_controller.rb#L92

**Comment by cesswairimu** [comment]
Good catch taking a look too

**Comment by jywarren** [comment]
https://github.com/publiclab/mapknitter/pull/786 !!!
