### ISSUE TITLE
Comment is added two times

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#750]
### What happened just before the problem occurred
When I try to give some comment on the map, the comment is generated two times.
There are two duplicate comment.

![Peek 2019-06-26 15-23](https://user-images.githubusercontent.com/32747809/60170653-83449580-9826-11e9-8c0b-d874dec9b917.gif)

### Relevant URLs

https://

### PublicLab.org username
divyabaid16
(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by divyabaid16** [comment]
@publiclab/mapknitter-reviewers please have a look at this.
Thanks!

**Comment by cesswairimu** [comment]
Good catch @divyabaid16 . Funny thing when you refresh the duplicates disappear :thinking:  Looking into it

**Comment by divyabaid16** [comment]
Yes, exactly.

**Comment by gauravano** [comment]
If after refreshing there's only one then it should be AJAX bug where we are appending the new comment twice.

**Comment by divyabaid16** [comment]
I guess the problem is there in https://github.com/publiclab/mapknitter/blob/85ec0c62a51caf93af72af12a441d46037ff90e0/app/assets/javascripts/maps.js#L66

This line is getting executed 2 times.

**Comment by cesswairimu** [comment]
Hi @divyabaid16 I tried to replicate this seems like its fixed...could u try it on your end?

**Comment by divyabaid16** [comment]
Yes, it is fixed so closing it. Sorry for the delay.
Thanks!
