### ISSUE TITLE
Can't open existing maps

### ISSUE THREAD

**Issue by kaustubh-nair** [publiclab/mapknitter#760]
# First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/mapknitter/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

The maps which already exist in the database are not loading. (Loaded from seeds I think?)
Here's the error message if it helps

``` 
Couldn't find all Nodes with 'id': (1, 3, 4, 5) (found 0 results, but was looking for 4)
app/models/warpable.rb:130:in `nodes_array'
app/views/images/_index.html.erb:50:in `block in _app_views_images__index_html_erb__3285024035478129285_70298420935660'
```

## Solution

In the file db/seeds.rb remove this line

https://github.com/publiclab/mapknitter/blob/main/db/seeds.rb#L44 

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo [README instructions](https://github.com/publiclab/mapknitter/blob/main/README.md)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/mapknitter

**Comment by jywarren** [comment]
Hmm, does this affect production or just development? Should we consider priority for 3.0 release tomorrow? Thanks!

**Comment by kaustubh-nair** [comment]
It's is affecting only `development`. I think there might be some problems with the seeds

**Comment by cesswairimu** [comment]
We can remove the nodes addition from the seed file..updated this to be an FTO. Thanks all

**Comment by tollhoff** [comment]
Hi, 
i'd like to clain this issue and start working on it, if it's not claimed by someone else.

**Comment by kaustubh-nair** [comment]
Sure go ahead @tollhoff!

**Comment by tollhoff** [comment]
Thanks a lot @kaustubh-nair!
I'm done with the changes!
