### ISSUE TITLE
New "view only" map page

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#761]
So building on the new designs in #743 we're looking to make a new "view only" page that is loaded when you click on a map. The URL might be `/m/map-name`, and it'd look like page 17 of this mockup doc: https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit#slide=id.g4f12792b5d_0_0

![image](https://user-images.githubusercontent.com/24359/60283120-754e4d80-98d6-11e9-9df0-854889e42aa2.png)![image](https://user-images.githubusercontent.com/24359/60283130-7b442e80-98d6-11e9-9527-de72fae2f31d.png)

@cesswairimu what do you think? Not everything is in place yet to make it happen 100%, but we can make a new template, use the same code as in the "embed" view, which seems to use the `show` template?

https://github.com/publiclab/mapknitter/blob/a6718529640a4469ba7e61443f4f23bf5ab657d2/app/controllers/maps_controller.rb#L83-L87

In any case it's got a white band above it but it is supposed to be a view-only map: https://mapknitter.org/embed/cranston-test and it basically works! So, this would be the top map in this mockup. 

Also, we used to have a page for this kind of of view-only here: https://github.com/publiclab/mapknitter/blob/main/app/views/map/view.html.erb so maybe that could now be deleted or recycled?

What do you think, @cesswairimu ?

**Comment by jywarren** [comment]
Also, your new front page should be live here shortly, i think: http://mapknitter-stable.laboratoriopublico.org/front-page

**Comment by cesswairimu** [comment]
Looks good @jywarren, I will start working on it and will let you know if something comes up

**Comment by jywarren** [comment]
Great!!!

**Comment by cesswairimu** [comment]
Well good news the '/front-page' url is now working on the stable server. Bad news my css is somehow not working http://mapknitter-stable.laboratoriopublico.org/front-page :thinking: beats me since this was working fine on unstable http://mapknitter-unstable.laboratoriopublico.org/front-page...working to find fix this asap

**Comment by cesswairimu** [comment]
Sorry, false alarm,  Its fine maybe I tried before the build was finished

**Comment by jywarren** [comment]
Hmm, yes, i also saw the CSS not loading initially ... not sure why! Glad
it's working now though!
