### ISSUE TITLE
Optimization of front page

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#767]
Hi @cesswairimu I realized that stable front page is quite slow and that it's most likely the listing of mappers. I think we need to make a cache around that -- at least for now, and then somehow optimize that query... It's really slow, and makes sense because it's counting all maps?

We can work on this on Monday!

**Comment by jywarren** [comment]
And maybe there are other better ways to feature mappers anyways!

**Comment by jywarren** [comment]
Like, why don't we manually tag maps we want to feature and we'll show mappers whose maps are tagged with a special tag like "featured"? That's much better anyways! And we can randomize the order.

**Comment by jywarren** [comment]
I like this idea, it'll feature a rotating set of mappers from around the world!

**Comment by cesswairimu** [comment]
Hey Jeff, yeah I noticed it was quite slow too. Yeah that be great will look into this. Thanks

**Comment by alaxalves** [comment]
What would be your suggestion of caching tool? Are we using something like Redis? @jywarren @cesswairimu

**Comment by cesswairimu** [comment]
I think just normal rails caching should be fine https://guides.rubyonrails.org/caching_with_rails.html without using a tool since its for the mappers images alone

**Comment by jywarren** [comment]
Yeah I think caching (1 day) would be a fine short term fix as we get the
other type of featuring implemented. Thanks!

**Comment by alaxalves** [comment]
> I think just normal rails caching should be fine https://guides.rubyonrails.org/caching_with_rails.html without using a tool since its for the mappers alone for now

Got it, if you need any help with this I might of some use :smile:. I have implemented rails caching with Redis before here -> https://gitlab.com/klara-org/klara-api/merge_requests/11/diffs. I think that it might be of some help either if we're using Active Support's caching. LMK :muscle: :muscle: :muscle:
