### ISSUE TITLE
(Priority)Search Bug

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#769]
### What happened just before the problem occurred

Some backend search constraints were implemented in #630 by me which cut out some extra database queries if your search query is less than 3 characters long. 

Since then the entire UI has been updated - but if you make any query it re-renders the old UI and you can't get back to the new one:

![search constraint2](https://user-images.githubusercontent.com/41092741/60409736-d30ebe00-9b92-11e9-8278-0c6dbac07d82.gif)

Less priority - 
Was initially going to open this issue to say constraint performance could be improved on a lot by adding frontend JS constraints - because currently a query less than 3 chars long still causes a page reload. 

### Relevant URLs

https://

### PublicLab.org username

(to help reproduce the issue)

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by sashadev-sky** [comment]
@divyabaid16 @jywarren @gauravano @avsingh999 

Sorry if this isn't priority feel free to remove that header but I think its a pretty significant bug

**Comment by gauravano** [comment]
The production doesn't have this issue as that PR is not pushed to stable yet, so I think we can remove the priority keyword. Or, lets just fix it, as we don't need to wait for a PR to break things.

Running localhost to observe the interface closely. Thanks, @sashadev-sky for reporting.

**Comment by gauravano** [comment]
Hmm, so how exactly we want our search page to look? I think sidebar needs work so as to follow the updated template?

**Comment by jywarren** [comment]
Ah, ok - so this may be priority because I'm really hoping to publish `main` to the live site today or tomorrow... i'm working on some other optimizations and display changes, so if anyone else can try this that'd be great. I believe we now have templates at /gallery that could be used to show results? Thanks for the catch!

**Comment by cesswairimu** [comment]
Hey all,  do we want this search to be available on the front-page(if so how do we display this or should it be a redirect to gallery page?) or show I make it only available on the gallery page? Wonna hear your thoughts. Thanks

**Comment by jywarren** [comment]
Let's have the search from any page (via navbar) direct to the gallery
template, but retain the current URL schemes -- can that work?

**Comment by cesswairimu** [comment]
Guess so...looking into it. Thanks Jeff
