### ISSUE TITLE
Weekly community Check-In #27 - Overestimated Issues

### ISSUE THREAD

**Issue by alaxalves** [publiclab/mapknitter#772]
Hi everybody :smiley: !

We all at Public Lab :balloon:  - learn, grow, work, brainstorm ideas, contribute together so why not share about our _weekly goals and the awesome work_ we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: .

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100:

If you're new here, welcome, and please comment a _Hello_ below, we would love to work with you. If you're looking for new issues, please try some of our [first-timers-only](https://code.publiclab.org/#r=all) issues.

We're SO EXCITED to have your help!

**Is there anything, you would like to share with us from past week's work? What is your plan for this week?**

If you have not planned yet, just leave a Hello! :wave: so that we know that you are in sync with us :arrows_clockwise: and doing well!

The coming weeks will be full of code :computer: , tasks :spiral_notepad:, fun :tada: and excitement :smiley:!!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input. :raised_hands:

#### Gitter

Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up [there](https://gitter.im/publiclab/publiclab) for these updates or just to join the conversation. You can also join us through http://publiclab.org/chat :speech_balloon:.

**This Week's Theme:**

**Overestimated Issues**: Issues that seemed hard but turned out to be very simple.

This week I'd like to hear from all some situations that we got an issue to fix and seemed to be very complex at first, but when we started doing it, it turned out to be pretty easy.

You can find our list of previous check-ins [here](https://github.com/publiclab/plots2/issues/5627) 

## Note to Summer of Code interns:

Hi, we request all the SoC students to include the below-mentioned points in their check-in comment:
- FTOs created in the previous week
- Progress for your project
- Upcoming week's goals 
- PR reviewed by you in the previous week
- Work completed last week.
- What things you did collaboratively last week? This is really important we want team spirit.
It is like a weekly scrum. Be flexible. 
- Feel free to tell us about your absence too, if you're taking a break.
- Issue/PR you're struggling with (if any)

With FTOs and PR reviews, we are seeking to develop a much more friendly and collaborative platform. We want you all will involve people in your project. You all will develop skills like leadership along the way.

Thank you!

**Comment by alaxalves** [comment]
One of the issues I thought that would be the hardest was this one -> https://gitlab.com/klara-org/klara-api/merge_requests/4, in this case, I had to implement a distributed database with replication among the clusters. In the end it turned out to be more easier than I thought.

**Progress**

Currently I have finished with Mapknitter's Rails 5.2.3 upgrade, I have removed the deprecation warnings, fixed the remaining tests, started defining routes and removed the generic routing. Also, I have fixed the travis pipeline caching for bundle install and yarn.

**Upcoming goals**

I intend to solve the upcoming issues that will come up with the Rails 5 upgrade and in the meantime I intend to start the upgrade to 6-rc1 version. I also intend to implement the same improvements I've made on Mapknitter to Plots2, when it comes to travis, codecov, caching, refactoring and perharps the rails upgrade too.

**Work completed last week**

- Bumped rubocop version and added the performance cop.
- Removed generic routes
- Using nested routes and added the specific routes.
- Fixed yarn and bundle caching in Travis pipelines(Reduced the CI running time in half)

**Before caching:**
![image](https://user-images.githubusercontent.com/19597045/60455123-05a8cd00-9c0c-11e9-9e9b-4263f541c078.png)

**After caching:**
![image](https://user-images.githubusercontent.com/19597045/60455136-0ccfdb00-9c0c-11e9-9e25-9a961970b783.png)

** What things I did collaboratively last week?**

I have given tips to Image Sequencer's Yarn migration and reviewed some PRs. I have also helped with Codecov's fix when generating a report. I have also reviewed some PRs but I can't remember the ones to link.

**Comment by sashadev-sky** [comment]
Hi! 

This is a good topic - it took me a little bit of thinking. The only one that comes to mind is that I recently looked into deprecating Bower and updating to use NPM only for LDI. I thought it would be an ordeal - but the switch turned out almost as simple as 1. Delete bower.json 2. Add package-lock.json 

Not a GSOC student but this template is useful anyway! 
What things you did collaboratively last week? This is really important we want team spirit.
- The mySQL installation has been a big barrier to newcomers for a while - especially for users of MacOS Mojave, where installation does not work without really specific configuration changes for the build. A new contributor has been helping me on their FTO to debug the progress with me so I can get the right commands down for future users. https://github.com/publiclab/mapknitter/pull/622#issuecomment-499888481. She has really gone out of her way to help out!

**Comment by gauravano-cultgear** [comment]
Great progress @alaxalves! And, thanks @konolga for the help with MySQL issue :tada:

**Comment by rmd6502** [comment]
Hey y'all, working on an open source sensor platform here: https://github.com/ProgressiveCoders/EnviroTrack-Node, currently working on the MQTT->Prometheus gateway (https://github.com/inuits/mqttgateway), then I'll work on converting the voltage readings into ppm of measured toxins

**Comment by gauravano** [comment]
Great progress @alaxalves! And, thanks @konolga for the help with MySQL issue :tada:

**Comment by gauravano** [comment]
@milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @ananyaarun @ananya @publiclab-mimi @ananya @hc-barker @starkblaze01 @aSquare14 @vaarigupta @alonpeer @pdurbin @HarshKhandeparkar @aashna27 @harshithpabbati @niravasher @jesus-montano @michelelong @cryptoclidus @mohamed-elalem @konolga

**Comment by gauravano** [comment]
@aSquare14 @vaarigupta @alonpeer @aashna27 @harshithpabbati @jesus-montano @michelelong @cryptoclidus @mohamed-elalem @konolga

**Comment by michelelong** [comment]
I think both of my PR's are basically done on my end (#5962 and #5896). Unfortunately, my life imploded yesterday and I'll be moving across the country alone with no job or any other certainty. I don't know when or if I'll be back online. I hope you can use what I have committed to finish up. Thank you for welcoming me here. I was happy to be able to help a little.

**Comment by cesswairimu** [comment]
Hey @michelelong thanks for helping  with the issues and sorry to hear about the your setbacks. Hopefully you will find a job or something soon. Take care :purple_heart:

**Comment by gauravano** [comment]
All the best @michelelong and thank you so much for your contributions and you're always welcome in our community.

**Comment by jywarren** [comment]
Thank you so much @michelelong and please take care!

**Comment by ViditChitkara** [comment]
Hey all, I'm working on integrating action cable on top of the rails 5 upgrade branch on mapknitter. Will have to make certain events in Leaflet.DistortableImage to handle all realtime changes when placing images. 

Had a discussion with @jywarren @divyabaid16 @gauravano @jainaman224 [here](https://github.com/publiclab/mapknitter/issues/609). Any suggestions would be really helpful!! Let us know if anyone wants to be a part of it.

And yes rightly said by @sashadev-sky , I too had the MySql issue when setting up the project. Was not able to figure out at the end. So, had to setup using sqlite locally. I think a better mysql documentation would be helpful.

**Comment by ViditChitkara** [comment]
Connecting https://github.com/publiclab/Leaflet.DistortableImage/issues/328 here as well. Any help here would be highly appreciated.
Thanks.

**Comment by IshaGupta18** [comment]
Hey everyone!
I am working with simple-data-grapher in this Summer of Code and I am at a ver exciting stage now, as I am integrating the library with plots2.

I am doing all the integration locally and I haven't published a PR due to some reasons, but I will be doing it pretty soon.

I have also started to work on creating a "Per-User data" page, where the users can see some information regarding the files they upload and have the option to delete those files etc.

There's also some discussion going on about "Creating a Research Note" out of the plotted data although it's a bit complex, but I will be going about that one too soon.
https://github.com/publiclab/simple-data-grapher/issues/65
https://github.com/publiclab/simple-data-grapher/issues/60
https://www.npmjs.com/package/simple-data-grapher

Have a great week everyone!

**Comment by gauravano** [comment]
Anyone interested in opening new check-in?

**Comment by gauravano** [comment]
Also, we have Open Code Call tomorrow - http://publiclab.org/opencall [Reminder]

**Comment by ananyaarun** [comment]
@gauravano I'll do it :)
When should I and in which repo ?

**Comment by gauravano** [comment]
You can open check-in by tomorrow and in any repo of your choice. Also, please mention people mentioned https://github.com/publiclab/mapknitter/issues/772#issuecomment-508118284 and https://github.com/publiclab/mapknitter/issues/772#issuecomment-508118617as we don't want to disturb others. Also, feel free to add names if you recognize a new contributor or from https://code.publiclab.org. Thank you!

**Comment by ananyaarun** [comment]
Sure @gauravano !!
I'll open it in by tomorrow :smiley:

**Comment by ananyaarun** [comment]
New check in up at LEL
https://github.com/publiclab/leaflet-environmental-layers/issues/231
Thanks everyone !!
