### ISSUE TITLE
Images can load incompletely on Firefox for Android or Mac

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#78]
![screenshot_2015-02-01-16-55-17](https://cloud.githubusercontent.com/assets/24359/5994042/7c191d7a-aa33-11e4-97ed-49dacf21c7ea.png)

![screenshot_2015-02-01-16-56-12](https://cloud.githubusercontent.com/assets/24359/5994045/889931ca-aa33-11e4-8f7f-746e6ecfba9c.png) 

http://test.mapknitter.org:3000/map/nature-center-infrag

Doesn't happen on chrome android. Also possibly related, firefos initially was zoomed out all the way to level 0.

**Comment by jywarren** [comment]
This is happening on Firefox v35 for mac too, and doesn't seem to be related to loading; attached screenshot shows images are fully loaded by browser, but not fully displayed:

![screen shot 2015-02-05 at 1 36 14 pm](https://cloud.githubusercontent.com/assets/24359/6066883/7a0e424a-ad3e-11e4-95b2-a66a795c96be.png)

**Comment by jywarren** [comment]
More interesting evidence: between normal FF and FF in private mode, the images load to differing degrees; here, left is FF and right is FF-private, which I loaded *second*.

![screen shot 2015-02-05 at 2 42 26 pm](https://cloud.githubusercontent.com/assets/24359/6067820/5b5bbdbc-ad45-11e4-8126-268702f666a3.png)

**Comment by jywarren** [comment]
Hmm, in different tabs of the same FF private window, the exact same amount of image loading is shown. But now in either new FF private windows (not new tabs) and in non private FF windows, the images load fully. Perhaps they are somehow cached as partially loaded, but once fully loaded the issue no longer occurs?

![screen shot 2015-02-05 at 3 36 57 pm](https://cloud.githubusercontent.com/assets/24359/6068803/0f49119c-ad4d-11e4-925c-63d5e6876945.png)

Resizing the images (to trigger recalc of the distortion CSS matrix) does not fix the images.

**Comment by jywarren** [comment]
Interestingly, if I instantiate an `<img>` element with the src of one of the images on the page, it appears fully rendered.

**Comment by jywarren** [comment]
OK, I believe this is now fixed -- @patcoyle and @fiestin, can you clear your firefox caches and check for partial image loads? 

https://support.mozilla.org/en-US/kb/how-clear-firefox-cache?redirectlocale=en-US&redirectslug=How+to+clear+the+cache

**Comment by patcoyle** [comment]
Jeff that worked. I tried
http://test.mapknitter.org:3000/map/ewb-symposium-without-borders-davis-ca
and got the partial images, cleared the cache and reloaded page, came in
fine.
Thanks,
Pat

**Comment by jywarren** [comment]
Super! Thanks!!
