### ISSUE TITLE
Images are not showing up properly on the map

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#780]
### What happened just before the problem occurred

When I created a map and was adding the images, only the first image that was added is shown in the map that too at the top left the corner. Other images though they are shown placed, after the refresh of the page they can't be seen.

**Comment by divyabaid16** [comment]
@publiclab/mapknitter-reviewers

**Comment by kaustubh-nair** [comment]
This is being caused by https://github.com/publiclab/mapknitter/issues/742
