### ISSUE TITLE
All Maps not displayed

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#781]
**Description**
@jywarren 
I guess with https://github.com/publiclab/mapknitter/commit/8d2bb866f0cf191d9af3d238b96b9f95fb75bdc8 the author is not showing up.

I think we should revert it back.

The error for reference:
![Selection_195](https://user-images.githubusercontent.com/32747809/60505617-b9c85780-9ce1-11e9-87bc-57cbd9e056d5.png)

**Comment by jywarren** [comment]
Oh no! I think the logic here was a bit off. Could you try to submit a fix?
It's running ok on stable now... isn't it?

**Comment by jywarren** [comment]
Just noting here is the error: http://mapknitter-stable.laboratoriopublico.org/gallery
