### ISSUE TITLE
Show which sort on image is performed

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#796]
**Description**
As suggested by @sashadev-sky there is currently no way to show how the user is sorting the images. Therefore there should be some label or some way to show which of the sorting on which option is performed.

Thanks!

**Comment by divyabaid16** [comment]
How does this look to show in which order the images has been sorted?
Currently, as seen, it is sorted by name.

![Selection_198](https://user-images.githubusercontent.com/32747809/60681631-a4a02400-9ead-11e9-96cb-ae67b1552790.png)

@publiclab/mapknitter-reviewers @jywarren 
Or if someone can suggest any other way?
Thanks!

**Comment by gauravano** [comment]
We can change the button text to Sort by and can show options in the dropdown?
