### ISSUE TITLE
Featured Mappers not shown in localhost

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#797]
**Description**
Even though the Featured mappers is shown in unstable and stable, it is not shown in localhost.
I have pulled the lastest changes.

![Selection_196](https://user-images.githubusercontent.com/32747809/60675854-04d99a80-9e9b-11e9-8e21-79e1b9b6b0ca.png)

@cesswairimu @jywarren

**Comment by jywarren** [comment]
I think this is due to location sharing bit working in non-https, and so
nothing being shown there if you haven't shared location. But we should
make it look better and more useful for people who don't share location!
Thanks!

**Comment by divyabaid16** [comment]
Ya, that can be done. 
Maybe we can just remove ```|``` before All maps so that it seems complete?!
Do let me know if I can help here in some way.
Thanks!

**Comment by cesswairimu** [comment]
Yeah we should move the `|` in the if block... Would you like to change that? Thanks @divyabaid16

**Comment by divyabaid16** [comment]
Ya, I will do it.
Thanks!

**Comment by divyabaid16** [comment]
After solving for this issue I think that we don't need ```|``` at all. Because Featured Mappers is like a complete subsection. What do you think @cesswairimu ?

Maybe we can just delete ```|``` and I will create the FTO for this if it is fine?

**Comment by cesswairimu** [comment]
I think we need it..beause if you have your location shared this is how the interface looks like..

![maps](https://user-images.githubusercontent.com/17081074/60682380-d90ae480-9e9b-11e9-9020-1f72b741a98d.png)

Or maybe you have ideas of a better display? Would could explore other ideas

**Comment by divyabaid16** [comment]
Oh yeah, you're right. I will just do it.
Thanks!
