### ISSUE TITLE
Tags display with "tour"

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#807]
The new front page is awesome: http://mapknitter-stable.laboratoriopublico.org/

We're looking forward to adding such a "top map" as shown below, to the tags page, for example: https://mapknitter.org/tags/featured

![image](https://user-images.githubusercontent.com/24359/60730288-c4b5fe80-9f12-11e9-92c1-9222ecfeeb5d.png)

We could combine the new gallery template (http://mapknitter-stable.laboratoriopublico.org/gallery) with the a top map, and what would be even cooler is if we had a button that offered a "tour" that uses `map.flyTo(...)` to cycle through the different maps on the page. (we'd have to calculate a bounding box perhaps to zoom to, or something, based on each map's images).

This isn't top priority but the basic addition of a map doesn't look like it'd be too hard; the "fly around" tour could come later!

**Comment by jywarren** [comment]
Hi @divyabaid16 would this by chance be something you'd be interested in working on?

**Comment by divyabaid16** [comment]
Ya, I will do it.

**Comment by jywarren** [comment]
Noting connection to https://github.com/publiclab/mapknitter/issues/834 -- the "regions" route there seems like it could be modified to include a `tag` parameter to filter for maps with a tag!
