### ISSUE TITLE
"Create a collection" button on view page

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#808]
Our new view pages #761 will be awesome. Given that tags can be used to make a collection of maps (see #807), let's put a note by the tag input that suggests `Make a collection of maps` and explains that using a unique tag on a set of maps creates a page at `https://mapknitter.org/tag/_____` where you can show your maps together.

------
We are participating in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more

**Comment by cesswairimu** [comment]
Hey @jywarren, is putting the note as the placeholder here, what you had in mind?  Thanks
![tags](https://user-images.githubusercontent.com/17081074/64925206-cf83ee00-d7f5-11e9-9db0-fa04ac86764b.png)

**Comment by cesswairimu** [comment]
@jywarren kindly take a look :point_up: when you get a moment. Thanks

**Comment by jywarren** [comment]
Ah, this would be perfect. We could put it in a `<small>` element in grey text just under there?

**Comment by jywarren** [comment]
It could be a link like `Create a collection »` and then when you click it, it displays extra information about how to use tags to do this, just with `.toggle()`?

**Comment by cesswairimu** [comment]
awesome thanks.

**Comment by cesswairimu** [comment]
Will add this to gci

**Comment by cesswairimu** [comment]
We are participating in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more

**Comment by SidharthBansal** [comment]
Published on GCI dashboard
