### ISSUE TITLE
Issue with Featured Locations Maps (Zooming In)

### ISSUE THREAD

**Issue by publiclab-mimi** [publiclab/mapknitter#822]
Hey guys! Loving the new MapKnitter updates and really impressed by the new homepage.

While exploring in Safari, I'm having issues with the "map of maps" for the featured locations. I'm not able to zoom in, whenever I click to zoom or use the +/- zoom buttons I'm taken from wherever I am into the middle of the ocean or another place that isn't the intended one. I can't recreate the issue in Chrome, so it may just be a Safari issue and not something that can be tackled on our end. I've made some screen recordings to more clearly show what's happening and you can view them here: https://drive.google.com/drive/folders/1q_giH0fEIy4NirzMpAnsehgYAIm-455f?usp=sharing 

### Relevant URLs

https://mapknitter.org

### PublicLab.org username

@mimiss

### Browser, version, and operating system
Issue in Safari, Version 12.1.1 (14607.2.6.1.1) on Mac OS Mojave

**Comment by sagarpreet-chadha** [comment]
This is strange, yes it seems to be problem with Safari . I will have to go to the our code to make sure this is not happening on our end . 
Can you help me by telling whether you clicked **Yes** to _**allow location access**_  the pop-up ? 

Thanks!

**Comment by sagarpreet-chadha** [comment]
And thank you for sharing this 😄 !

**Comment by jywarren** [comment]
This is linked to #792 most likely! Thanks, both of you -- and I think the `leaflet-fullhash` integration may be the issue?

**Comment by jywarren** [comment]
OK, i think i found the issue! https://github.com/publiclab/mapknitter/pull/833

There could be a second bug hiding. But I hope this resolves most or all of this!

**Comment by jywarren** [comment]
I think i got this! Can you test it out on https://mapknitter.org now?
