### ISSUE TITLE
GDAL status w/sinatra app

### ISSUE THREAD

**Issue by MargaretAN9** [publiclab/mapknitter#829]
### What happened just before the problem occurred
Just a quick question on the use of GDAL in mapknitter: 

The mapknitter info site says that GDAL is going to be replaced with a sinatra app, 
" Component 3 is a set of calls to GDAL (Geospatial Data Abstraction Library) and ImageMagick, which perform the distortions, geolocations, and produce export products like GeoTiff, TMS, jpg, etc. These are baked into the Warpable and Map models, as well as the Export controller, and could use some consolidation.
 
 Component 3 is soon to be replaced with an external exporter service built in a small Sinatra app called mapknitter-exporter-sinatra using the mapknitter-exporter gem".

Questions:
Is the goal to import GDAL (with ruby bindings) to the Sinatra app or replace GDAL all together? 

### Relevant URLs

https://github.com/publiclab/mapknitter/blob/main/README.md

### PublicLab.org username

MaggPI

### Browser, version, and operating system
not relevant

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by jywarren** [comment]
Hi! The sinatra app is in production now - see
https://publiclab.org/wiki/mapknitter-exporting-your-map#Cloud+Exporting

https://github.com/publiclab/mapknitter-exporter-sinatra/

It's based around a gem which wraps GDAL:
https://github.com/publiclab/mapknitter-exporter

Hope that helps!

**Comment by jywarren** [comment]
I think this is wrapped up now, thank you!
