### ISSUE TITLE
images wont load completely in firefox (desktop), with chrome it loads well

### ISSUE THREAD

**Issue by fiestin** [publiclab/mapknitter#83]
![screen shot 2015-02-04 at 11 10 35 am](https://cloud.githubusercontent.com/assets/4379825/6037626/7d3a9558-ac5e-11e4-8414-cb9a94cd4f31.png)

**Comment by jywarren** [comment]
Hi, Hagit - can you check Safari as well? This showed up in Firefox mobile
too, and I'd thought it was just a connectivity (slow internet) problem, or
maybe an issue with memory on a smartphone, but clearly it's a more
generalized issue. @patcoyle also saw this behavior.

**Comment by fiestin** [comment]
I checked it again in Firefox and Safari, there wasn't a problem with loading. maybe it was connected to connectivity. But the Zoom buttons were not working in Safari. I'll file another issue for that. and the menu bar on the right side wasn't loading at all in Safari (Desktop).

**Comment by jywarren** [comment]
I just reproduced the issue above in Firefox v35 for Mac on desktop; will look into it further now. But merging into #78 and closing this duplicate. Thanks!
