### ISSUE TITLE
Change docker yml version

### ISSUE THREAD

**Issue by alaxalves** [publiclab/mapknitter#850]
### What happened just before the problem occurred

Our docker-compose.yml version defined in https://github.com/publiclab/mapknitter/blob/main/docker-compose.yml#L1 works properly, but currently not supported by Jenkins. All we have to do is change from '3.5' to '3.3' and Jenkins will work. I have hotfixed `unstable` branch, but we need this in `main` branch as well.

### Relevant URLs

https://jenkins.laboratoriopublico.org/job/Mapknitter-Unstable/145/console

[This line](https://github.com/publiclab/mapknitter/blob/main/docker-compose.yml#L1) should look like this:

``` yaml
version: '3.3'
```

**Comment by devevignesh** [comment]
I would like to claim this.

**Comment by alaxalves** [comment]
Open the PR then attach with this issue @devevignesh

**Comment by devevignesh** [comment]
@alaxalves Created [PR](https://github.com/publiclab/mapknitter/pull/852). Thanks
