### ISSUE TITLE
Bug reporting on Rails 5 upgrade

### ISSUE THREAD

**Issue by kaustubh-nair** [publiclab/mapknitter#857]
- [ ] Nothing happens when clicking on login ( Issue only on `unstable`. Works fine locally )
- [ ] Images not placed. Place an image on map and hit refresh
- [ ] Map on homepage does not load ( Only on `unstable` )
- [ ] Google maps api not loading while creating maps ( Only on `unstable` )
- [ ] Recaptcha error: `ERROR for site owner: Invalid site key`

**Comment by kaustubh-nair** [comment]
I think most of these have something to do with yarn packages. I see a lot of reference errors on console
@alaxalves Any idea why packages are not being installed?

**Comment by alaxalves** [comment]
@kaustubh-nair 
https://github.com/publiclab/mapknitter/pull/803

**Comment by alaxalves** [comment]
I'm working on Jenkins environment.

**Comment by alaxalves** [comment]
> @kaustubh-nair
> #803

**Comment by jywarren** [comment]
Linking this back to #891, are we still looking into these? Thank you!

**Comment by alaxalves** [comment]
> Linking this back to #891, are we still looking into these? Thank you!

Everything we have reported here have been fixed, I have forgot to comment here. Sorry about that. What's pushing us back to merge Rails-5 is the Map Creation issue that popped up on main.
