### ISSUE TITLE
Some geolocated addresses don't have any shown maps

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#859]
I opened MapKnitter in Detroit, MI, USA, and there was only 1-2 maps in the default view, so ideally we'd want to zoom out. I can't decide if we should set the default zoom further out, or if that'd be annoying for areas with LOTS of maps... should we do it dynamically, i.e. if there are few maps, we zoom out until there are more? Or should we just set a lower zoom level for the initial zoom? @cesswairimu what do you think?

**Comment by cesswairimu** [comment]
I think doing it dynamically would be better but I think that would probably increase the map load as already is, if so, maybe  a lower zoom level would be safe ?

**Comment by jywarren** [comment]
Yeah, ok, let's just do a quick fix of lower zoom level!
