### ISSUE TITLE
right sidebar for maps pages doesn't load in Safari

### ISSUE THREAD

**Issue by fiestin** [publiclab/mapknitter#86]
![screen shot 2015-02-05 at 5 23 52 pm](https://cloud.githubusercontent.com/assets/4379825/6062900/f0bca95a-ad5b-11e4-95ab-fa560ab099cb.png)

**Comment by jywarren** [comment]
I think it's just pushed down off the page. Darn, i'll try it in different window sizes to see if I can figure out why.

**Comment by jywarren** [comment]
Hmm, I'm not sure -- it seems to be fine on Safari Version 6.1.5 (8537.77.4) -- see attached. Can you check what version you have? 

![screen shot 2015-02-05 at 12 36 55 pm](https://cloud.githubusercontent.com/assets/24359/6065489/d1528e4a-ad33-11e4-8d29-ea42415e13a9.png)
![screen shot 2015-02-05 at 12 36 51 pm](https://cloud.githubusercontent.com/assets/24359/6065490/d1546ac6-ad33-11e4-966e-b47b1eff2338.png)

**Comment by jywarren** [comment]
Anyone else with safari notice this? @steviepubliclab or @mathewlippincott or @ebarry?

**Comment by jywarren** [comment]
I'm going to close this, but Hagit, please re-open if the issue persists; however, it looks like you may be using an older version of Safari (judging from your menubars) -- can you check?
