### ISSUE TITLE
Update L.Control.Layers initializer to class factory syntax

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#860]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/mapknitter/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

**What's supposed to happen:**

From the official [Leaflet docs](https://leafletjs.com/reference-1.0.0.html):
<blockquote>

Class Factories
You may have noticed that Leaflet objects are created without using the new keyword. This is achieved by complementing each class with a lowercase factory method:

new L.Map('map'); // becomes:
L.map('map');

</blockquote>

**What actually does happen:**

We use Leaflet's `L.Control.Layers` to initialize a layers control, but we don't take advantage of their suggested class factory syntax. Let's update the code in the files indicated below.

## Solution

**Where to find the relevant lines of code**: 

Remove the `new` keyword from the following code block and update `L.Control.Layers` to `L.control.layers` :

1) https://github.com/publiclab/mapknitter/blob/7954bf153540162845fbdf6f9e6c17a829e6512b/app/assets/javascripts/mapknitter/Map.js#L610

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo [README instructions](https://github.com/publiclab/mapknitter/blob/main/README.md)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by sashadev-sky** [comment]
@jywarren my favorite FTO ever 😂

**Comment by OzunaEdd** [comment]
Can you Assign This to me? if it has not been assign yet

**Comment by sashadev-sky** [comment]
@OzunaEdd Assigned :)

**Comment by OzunaEdd** [comment]
@sashadev-sky I updated but one of the test failed can you please tell me why and how can i fix it ? and if there is anything else I need to fix before it get merged ?

**Comment by OzunaEdd** [comment]
@sashadev-sky I did everything you told me too and it still failed one check it out.

**Comment by kaustubh-nair** [comment]
I think he might be referring to the failing codecov check? @OzunaEdd ?
That can be ignored, we're facing some inconsistencies with it

**Comment by sashadev-sky** [comment]
@kaustubh-nair @OzunaEdd ok! I thought it could have been due to something else during the commit process - but I merged the other PR!! Thank you both 🎉
