### ISSUE TITLE
Maps not displaying when 'All maps'  is selected

### ISSUE THREAD

**Issue by MargaretAN9** [publiclab/mapknitter#872]
### What happened just before the problem occurred

Mapps gallery dowws not show thumbnail images or displays default picture of PL balloon kit
### Relevant URLs
https://mapknitter.org/gallery
https://
![image](https://user-images.githubusercontent.com/37722313/61580429-3def4d00-aae0-11e9-9120-68b7125ce87c.png)

### PublicLab.org username

MaggPi
### Browser, version, and operating system

Windows 10  Chrome 
For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by jywarren** [comment]
I think @cesswairimu has fixed this one in the latest main branch? Thanks for reporting!
