### ISSUE TITLE
In README.md add how to run test on a particular file

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#874]
Currently, in README.md it is shown how to test the whole code.
Method to perform the test on a particular file must be added.

Thanks!

**Comment by alaxalves** [comment]
We'll get this better executed when we get Rails 5 on main. In Rails 5, all we gotta do is `rails test the/path/of/the/test.rb`

**Comment by gauravano** [comment]
Added in https://github.com/publiclab/mapknitter/pull/876. But, I think one of the command added in PR is rails 5 based. We would be merging rails 5 branch very soon right? @alaxalves
