### ISSUE TITLE
white edges + image offset when exporting maps

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#88]
Working to export two maps of a site in NOLA. The data of the maps is clear, but when I export them, I get white edges around some of the pictures:

Edit:
![clear](https://cloud.githubusercontent.com/assets/7490478/6067942/ee891bb4-ad3d-11e4-9c8a-a83dcb64a059.png)

Export:
![white](https://cloud.githubusercontent.com/assets/7490478/6067948/f47cab76-ad3d-11e4-968b-466ec7c7b6da.png)

**Comment by jywarren** [comment]
Is this in MapKnitter 2 or the current 1.0 site?

**Comment by steviepubliclab** [comment]
current 1.0

**Comment by jywarren** [comment]
oh, hmm. OK, is this a high priority issue at the moment? I'd prefer to
attempt fixing it in the MK2 release, if it's even present there.

**Comment by steviepubliclab** [comment]
ok there are 4 maps done today with high school students and we haven't
been able to export any. If I can export these later on MK2 that's fine,
but I'd rather not throw out their work. Also, when we go to export them,
they distort and move.


http://mapknitter.org/map/view/wetland-watchers-park

http://mapknitter.org/map/view/haaas-mapster

http://mapknitter.org/map/view/bayoustjohn2

http://mapknitter.org/maps/city-park-nir

**Comment by jywarren** [comment]
We'll be able to export them later, but the other possibility is that there may not be a need to export them in MK2 because they can be displayed distorted online without exporting. It depends on the use case, but I don't see any scenario where we'd delete their work. 

> when we go to export them, they distort and move.

Can you provide more detail about this?

**Comment by steviepubliclab** [comment]
For example, this exported map looks nothing like the one you see when you
are in the edit format:

http://mapknitter.org/map/view/wetland-watchers-park

**Comment by jywarren** [comment]
Hmm, that map looks identical except for the white edge pushing each image down -- the corners are all in the same places. Is that not the same as the issue you described above, or am I seeing something different?

Note to devs: this seems related to https://github.com/jywarren/mapknitter/issues/127

**Comment by steviepubliclab** [comment]
Oh I see, the white is pushing it down and that's why it looks distorted.
Ok.

**Comment by jywarren** [comment]
Hi, @steviepubliclab  - can you check if this still happens?

**Comment by numeroteca** [comment]
Coping images from the duplicated issue #166:

Map in mapknitter:
![macaba-mapkintter](https://cloud.githubusercontent.com/assets/1223722/7234893/cdf8a9d2-e78a-11e4-9fa9-20ce9e7788af.png)

Exported image:
![2015-04-14-barcelona-macba-2](https://cloud.githubusercontent.com/assets/1223722/7234856/81d6a004-e78a-11e4-87c6-7286aab1e0e8.jpg)

Map: http://mapknitter.org/maps/2015-04-14-barcelona-macba#

**Comment by numeroteca** [comment]
Maybe this helps to debug: this bug is only happening in these maps:

- http://mapknitter.org/maps/2015-04-14-barcelona-macba#
- http://mapknitter.org/maps/placa-salvador-segui-barcelona#

It might be interesting to see why this is **not** happening in other similar maps;

- http://mapknitter.org/maps/placa-folch-i-torres-barcelona#
- http://mapknitter.org/maps/ramblaravalnovum#

**Comment by jywarren** [comment]
The difference I see is that for the maps which are broken the EXIF orientation 6, and for working ones, it's 1. This means the camera was at an odd angle for some flights; we've previously fixed this for some angles in https://github.com/jywarren/mapknitter/issues/127. Checking which.

**Comment by jywarren** [comment]
OK, we fixed it for EXIF=3; this time it's EXIF=6. Relevant lines: https://github.com/publiclab/mapknitter/blob/master/app/models/warpable.rb#L192-L194

**Comment by jywarren** [comment]
I've attempted to duplicate the fix for EXIF=3 in EXIF=6 by switching height/width. Trying export on the Macba map.

**Comment by jywarren** [comment]
This fix seems to be good! Take a look at the Macba map. Merging into master.
