### ISSUE TITLE
Leaflet listed twice on the MapKnitter about page

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#883]
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/mapknitter/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

Leaflet is listed twice on our about page:

![image](https://user-images.githubusercontent.com/41092741/61925940-79ed3c80-af3c-11e9-9196-419ae583ce3b.png)

## Solution

Remove the following line:

https://github.com/publiclab/mapknitter/blob/e2c890d5be81863f7e7d78ad158d9f73cad54d00/app/views/front_ui/about.html.erb#L18

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo [README instructions](https://github.com/publiclab/mapknitter/blob/main/README.md)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by robbedec** [comment]
Hi, can I take this?

**Comment by shivam-51** [comment]
I would like to claim this issue .!!

**Comment by sagarpreet-chadha** [comment]
Yes please go ahead :)

**Comment by shivam-51** [comment]
Hey there . I submitted my first pull request hope that's satisfactory. Thanks for a easy beginning . :)

**Comment by sashadev-sky** [comment]
closed via #887
