### ISSUE TITLE
(Priority) Cannot make a new map in localhost

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#884]
When creating a new map, the location doesn't load as you type it in. 
- If you submit it anyway, you get an error page,
-  if you update the lat lngs manually then submit it, it goes through but the map is blank (gray) and you cant and you get an error when trying to upload images to it
- Ive been seeing this issue for maybe over a week now. I think it comes and goes? Not sure.

**Comment by sashadev-sky** [comment]
@jywarren @alaxalves @gauravano @kaustubh-nair

**Comment by sashadev-sky** [comment]
@alaxalves @kaustubh-nair I am pretty sure this is related to the fact that the map doesnt show on unstable. similar error messages and seeing the grey map:

![image](https://user-images.githubusercontent.com/41092741/61954785-9bbfe100-af87-11e9-95be-1c6e90fae76a.png)

**Comment by gauravano** [comment]
Hi @sashadev-sky,  I tried to reproduce the issue but wasn't successful. I tried these cases:
1. Pulled master and tried for logged in and w/o user
2. Ran `yarn install` and then tried for both users

In all the cases, the Location autocomplete is working for me :confused:

**Comment by kaustubh-nair** [comment]
@sashadev-sky which branch is this on? I just checked it works fine on `main`

**Comment by sashadev-sky** [comment]
Weird it is still not working for me! I also just saw a user post this issue : #886

**Comment by sashadev-sky** [comment]
Not working in safari or chrome. I recently (yesterday) nuked the node_modules cache

**Comment by sashadev-sky** [comment]
perhaps clearing your cache will reproduce it?

**Comment by gauravano** [comment]
Hmm. I tried in chrome. Will try in Safari and also the cache case.

**Comment by jywarren** [comment]
Are you logged in or not logged in? (hiiii!)

**Comment by sashadev-sky** [comment]
not logged in!

**Comment by sashadev-sky** [comment]
also does not work when logged in

**Comment by kaustubh-nair** [comment]
That's weird, I tried deleting cache and doing it in chrome and it works for me
I even tried it on the live site, it works there as well. :/

**Comment by kaustubh-nair** [comment]
Did you try deleting `public/lib` and `yarn.lock` and reinstalling assets?

**Comment by gauravano** [comment]
> That's weird, I tried deleting cache and doing it in chrome and it works for me
I even tried it on the live site, it works there as well. :/

Same. Also, tried the live site on safari. Working.

**Comment by sashadev-sky** [comment]
so weird! I have tried:
```
$ rake tmp:cache:clear
$ rm -rf node_modules
$ rm package-lock.json
$ rm yarn.lock
$ npm cache clean
$ be bundle install
$ yarn install
$ rails s
```
then opening in Firefox which I never use and same results. another notable thing is that the sidebar toggle does not work again, which i have had issues with before.

**Comment by sashadev-sky** [comment]
Sorry everyone I fixed!!!! @jywarren sorry for interrupting the vaca 😿right before bed last night I had bumped the LDI package and completely forgot and it was breaking everytinhg

**Comment by gauravano** [comment]
No issue @sashadev-sky. Glad everything worked out :+1:

**Comment by sashadev-sky** [comment]
Not gonna lie 4 hours later am starting realize it didnt work out haha

**Comment by sashadev-sky** [comment]
It keeps telling me classes I mention from LDI are undefined, like L.distortableImageOverlay and L.EditAction

**Comment by gauravano** [comment]
Hmm. If you want, I can try a new installation in Mac OS. Do you think, it would help?

**Comment by sashadev-sky** [comment]
@gauravano I just uploaded a PR to fix it. I am so confused how this is working for everyone else. We use two variables - `window.mapKnitter` and `window.mapknitter` inconsistently throughout the repo - even within the same file. 

The only one we actually define is here: 
https://github.com/publiclab/mapknitter/blob/3ca0b08749d31d9f354518ae29ece4690a1248ca/app/assets/javascripts/mapknitter/Map.js#L9

But this is not saved globally (on window or without a var), so files besides `Map.js` can't access it. That is why `jQuery.getMap()` was failing. 

Features created in other files, such as the sidebar, were not working either, because they are attempting to access a variable from the window that hasnt been saved there, or using camelCase for some reason:
https://github.com/publiclab/mapknitter/blob/3ca0b08749d31d9f354518ae29ece4690a1248ca/app/assets/javascripts/maps.js#L19-L26

after changing  `var mapknitter = this;` to `window.mapknitter = this` and updating all camelCase to `mapknitter` everything is working again for me (see PR #892)
