### ISSUE TITLE
Update initializers to class factory syntax

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#888]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/mapknitter/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

**What's supposed to happen:**

From the official [Leaflet docs](https://leafletjs.com/reference-1.0.0.html):
<blockquote>

Class Factories
You may have noticed that Leaflet objects are created without using the new keyword. This is achieved by complementing each class with a lowercase factory method:

new L.Map('map'); // becomes:
L.map('map');

</blockquote>

**What actually does happen:**

We use built-in Leaflet classes such as `L.Control.Layers`, `L.Map`, and `L.LatLng`, but we don't take advantage of their suggested class factory syntax. Let's clean up the below file a bit to do that:

## Solution

1. remove the `new` keyword and change the initializer to `L.map`
https://github.com/publiclab/mapknitter/blob/fb876407671f27e0bc97cb9da1edb2baa8797ac0/app/views/map/_leaflet.html.erb#L57

2. remove the `new` keyword and change the initializer to `L.control.layers`
https://github.com/publiclab/mapknitter/blob/fb876407671f27e0bc97cb9da1edb2baa8797ac0/app/views/map/_leaflet.html.erb#L70

3. remove the `new` keyword and change the initializer to `L.latLng`
https://github.com/publiclab/mapknitter/blob/fb876407671f27e0bc97cb9da1edb2baa8797ac0/app/views/map/_leaflet.html.erb#L73

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo [README instructions](https://github.com/publiclab/mapknitter/blob/main/README.md)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by flyside** [comment]
Hellow, I would like to work on this.

**Comment by sashadev-sky** [comment]
@flyside go ahead thank you!

**Comment by NitinBhasneia** [comment]
@flyside is this work or can i work on this remaining

**Comment by NitinBhasneia** [comment]
@flyside are you working on this or may I work?

**Comment by sashadev-sky** [comment]
@NitinBhasneia would you like me to make you one

**Comment by flyside** [comment]
@NitinBhasneia please fix it) thx!

**Comment by sashadev-sky** [comment]
**Uploaded on GCI dashboard**

**Comment by SidharthBansal** [comment]
Published
