### ISSUE TITLE
export not working

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#912]
### What happened just before the problem occurred
I'm trying to help someone download a map so they can get it printed, but the export currently isn't working. I can get the image on a jpeg from the cloud export, but we're looking for a larger file than this. 

### Relevant URLs

https://mapknitter.org/maps/nottingham-city-centre### PublicLab.org username

**Comment by steviepubliclab** [comment]
here's an image of what we see when we try to export

![Screen Shot 2019-08-08 at 9 51 58 AM](https://user-images.githubusercontent.com/7490478/62708842-2eb63d80-b9c2-11e9-8ccf-55334f523cea.png)

**Comment by cesswairimu** [comment]
I was able to replicate this locally the error is 
``ActiveRecord::StatementInvalid (Mysql2::Error: Field 'bands_string' doesn't have a default value: INSERT INTO `exports` (`map_id`, `user_id`, `status`, `created_at`, `updated_at``
Trying different fixes also pinging @sashadev-sky who have been working on the export a lot and might have some pointers

**Comment by jywarren** [comment]
Thanks, all - i've merged #913 and also agree with @sashadev-sky that we should do a more permanent solution in the db. However if we completely switch to cloud export soon enough, we may be able to address it by removing in-app exports entirely as an alternative. Thanks for you swift responses!

**Comment by jywarren** [comment]
And depending on how we decide to address this please feel free to open an issue for the longer-term fix. 👍

**Comment by jywarren** [comment]
Looking to http://mapknitter-stable.laboratoriopublico.org/ to test out as soon as it builds!

**Comment by jywarren** [comment]
Hmm, i seem to be getting an error on all maps -- will look at the logs. http://mapknitter-stable.laboratoriopublico.org/gallery

**Comment by jywarren** [comment]
aha - `ActionView::Template::Error (Mysql2::Error: Table 'mapknitter.versions' doesn't exist: SHOW FULL FIELDS FROM `versions`):` due to https://github.com/publiclab/mapknitter/pull/862 i am guessing?

**Comment by jywarren** [comment]
Hmm, we don't track schema.rb in mapknitter. So, we could either include a `rake db:migrate` in our container deploy process... or start tracking schema.rb?

**Comment by jywarren** [comment]
OK, this seems resolved now, I believe. Let's coordinate any follow-ups here! @cesswairimu @sashadev-sky @steviepubliclab 

Thanks, all!
