### ISSUE TITLE
Database migration not running in stable

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#915]
I just saw that MapKnitter stable test server is failing every time; thought it was related to version numbers in #862 but i see error:

```

[1Bdocker-compose exec -T web bash -l -c "sleep 10 && rake db:migrate && rake assets:precompile"
mesg: ttyname failed: Inappropriate ioctl for device
rake aborted!
Bundler::GemNotFound: Could not find request_store-1.4.1 in any of the sources
/app/config/boot.rb:3:in `<top (required)>'
/app/config/application.rb:1:in `<top (required)>'
/app/Rakefile:4:in `<top (required)>'
/usr/local/bundle/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
Makefile:16: recipe for target 'redeploy-container' failed
make: *** [redeploy-container] Error 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

https://jenkins.laboratoriopublico.org/job/Mapknitter-Stable/239/console

I confirmed that `schema.rb` is not updated, so `rake db:migrate` has not run; but it seems like the first command in the sequence `docker-compose exec -T web bash -l -c "sleep 10 && rake db:migrate && rake assets:precompile"` -- ...hmm...

Looking deeper now.

**Comment by jywarren** [comment]
OK, noting that this error only affects the most recent stable build. And that all previous stable builds failed for different reasons, so I can't confirm that we've actually broken something here...

Production is not yet on a container, so I can't say if we're going to see this issue there... cc @icarito

**Comment by jywarren** [comment]
Aha, the only build of this on unstable faced the same error:

```

[1Bdocker-compose exec -T web bash -l -c "sleep 10 && rake db:migrate && rake assets:precompile"
mesg: ttyname failed: Inappropriate ioctl for device
rake aborted!
Bundler::GemNotFound: Could not find request_store-1.4.1 in any of the sources
/app/config/boot.rb:3:in `<top (required)>'
/app/config/application.rb:1:in `<top (required)>'
/app/Rakefile:4:in `<top (required)>'
/usr/local/bundle/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
Makefile:16: recipe for target 'redeploy-container' failed
make: *** [redeploy-container] Error 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

https://jenkins.laboratoriopublico.org/job/Mapknitter-Unstable/196/console

**Comment by jywarren** [comment]
This could be simply an unavailability of the `request_store-1.4.1` gem?

**Comment by jywarren** [comment]
Hmm. RubyGems shows https://rubygems.org/gems/request_store/versions/1.4.1 is the latest, so it should be available there...?

**Comment by jywarren** [comment]
OK, and noting that `paper_trail` depends on `request_store`, so that's how we started getting it:

```
paper_trail (10.3.0)
--
130 | activerecord (>= 4.2, < 6.1)
131 | request_store (~> 1.1)
```

**Comment by jywarren** [comment]
Hmm. I tried manually installing the gem on the stable server (not in the container, though), and it worked. I'm trying rebuilding the stable server now to see if it picks up the now-installed gem, but at least we know that the server /can/ fetch that gem at `v1.4.1`

**Comment by jywarren** [comment]
Either way, `mesg: ttyname failed: Inappropriate ioctl for device` could be the clue as to why it wasn't able to fetch it?

**Comment by jywarren** [comment]
For whatever reason, it worked to manually install the gem, and stable is running now. Since this affects only containerized editions, and production is not yet in a container, I'll publish to production after some manual testing.

**Comment by sashadev-sky** [comment]
@jywarren I saw a message about papertrail in my terminal today - could be relevant:
![image](https://user-images.githubusercontent.com/41092741/62764117-1f370300-ba5b-11e9-8018-a688826a5123.png)

**Comment by sashadev-sky** [comment]
@jywarren 
this was added 5 days ago in `paper_trail.rb`:
```
PaperTrail.config.track_associations = false
PaperTrail.serializer = PaperTrail::Serializers::JSON
```

Could be unrelated to this but I guess we should do what the message says and remove it?

**Comment by jywarren** [comment]
Oh thanks for the help! Actually working a subsequent issue I could use
help on in #916 if you have a moment!

**Comment by jywarren** [comment]
Also noting a warning, cc @divyabaid16 -- just a heads up, I don't know if it's meaningful! 

```
COMPOSE_PROJECT_NAME=mapknitter_stable PORT=6002 docker-compose exec web rake assets:precompile
Association Tracking for PaperTrail has been extracted to a separate gem. To use it, please add `paper_trail-association_tracking` to your Gemfile. If you don't use it (most people don't, that's the default) and you set `track_associations = false` somewhere (probably a rails initializer) you can remove that line now.
```

**Comment by jywarren** [comment]
Not sure how it's related, but (after manually installing the gem above) i later got the build to complete, after adjusting `uglifier` gem too -- https://github.com/publiclab/mapknitter/issues/916#issuecomment-519859839 -- in case it's relevant!

**Comment by jywarren** [comment]
OK, seems the migration ran ok on stable, to be honest i'm not sure how, but maybe because i manually installed the gem...

**Comment by jywarren** [comment]
OK, so this is now an issue only on stable for future builds that require new gems, i think?

**Comment by jywarren** [comment]
to reproduce, we may have to uninstall the gem and rebuild to ensure the container can properly fetch it...

**Comment by divyabaid16** [comment]
So should we just remove this line? 
```   PaperTrail.config.track_associations = false```
To get rid of the message?

**Comment by jywarren** [comment]
That sounds right, yes! Can you open a PR for that please? thank you!

**Comment by divyabaid16** [comment]
Yes, I will just open it now.
Thanks!
