### ISSUE TITLE
Downloads (generated by export) not appearing

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#921]
Export seems to be running now but the menu of downloads generated doesn't seem to be loading for this map:

https://mapknitter.org/maps/mapping-nottingham-s-urban-greening--3

@cesswairimu @divyabaid16 @publiclab/mapknitter-reviewers any idea if there's an issue with the template to display export formats? Thank you! cc @steviepubliclab

**Comment by divyabaid16** [comment]
Maybe this has something to do with:
![Selection_224](https://user-images.githubusercontent.com/32747809/62818063-1b8ca480-bb5f-11e9-8396-8f44c9552b2d.png)

**Comment by jywarren** [comment]
Hmm, we should see if the files exist at all? 

Also adding these notes:

I want to check old maps to see whether all download display is affected or only new down
*downloads
Then, see if the controller is correctly looking up downloads for the map
But new export generation on production seems fine, it just doesn't display the export outputs.

**Comment by jywarren** [comment]
Some of this debugging is possible even without being able to generate local exports. But divya, I think you may just not have all the exporting dependencies installed, like gdal?

**Comment by jywarren** [comment]
https://github.com/publiclab/mapknitter/blob/d5c9565a34e89a954cb9e16fbb4ac7e1a9cc447f/app/controllers/maps_controller.rb#L129

And

https://github.com/publiclab/mapknitter/blob/main/app/views/maps/_exports.html.erb

Should be the controller and view used to populate the exports drop-down.

**Comment by jywarren** [comment]
OK, finally got to a laptop and it seems to be an error with `Popper`? part of bootstrap?

```
Uncaught TypeError: Bootstrap's dropdowns require Popper.js (https://popper.js.org/)
```

@sashadev-sky @divyabaid16 @cesswairimu have we modified Bootstrap in a way that'd cause this, or did we just not catch it when we did the Bootstrap 4 upgrade?

**Comment by sashadev-sky** [comment]
I think that might've been me who removed it. There was some sort of problem with it. It makes sense that maybe its throwing that error for the exports now, they are a dropdown. How are the other dropdowns in the app made? 

ccing @alaxalves in case he remembers if there was something wrong with popper

**Comment by gauravano** [comment]
Hey @sashadev-sky, I checked out to the state before your commit and it wasn't working at that time too. Although, you did removed a popper from maps.js but I have added it in application.js this time as bootstrap popups depend on it.

**Comment by jywarren** [comment]
OK, let's see if this builds properly in stable. My concern was that there may be a second bug where even if the popup opens, the map exports don't get displayed in it. Then we can try to solve that.

Also via Sasha, #597 may be a mitigating factor so let's remember to refresh the page before testing the Downloads dropdown until that is also fixed.

**Comment by jywarren** [comment]
OK, popper not working on stable, but i wonder if this is the issue with the container not recompiling assets. I'll try doing that manually and see.

**Comment by jywarren** [comment]
OK, compiled and restarting...

**Comment by jywarren** [comment]
Great, popper issue resolved. Generating export at http://mapknitter-stable.laboratoriopublico.org/maps/unnamed-road-wichita-ks-67211-usa to test.

**Comment by jywarren** [comment]
OK, that worked!

![image](https://user-images.githubusercontent.com/24359/63052659-ead5a380-bead-11e9-99ac-942abbd91092.png)

**Comment by jywarren** [comment]
Closing and I'll publish this to the live site!

**Comment by jywarren** [comment]
Thank you all!!!

**Comment by jywarren** [comment]
cc @alaxalves this means we should be good to move forward on Rails 5 now!
