### ISSUE TITLE
Toolbar icons not being displayed

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#922]
It is shown blank:

![Selection_222](https://user-images.githubusercontent.com/32747809/62817918-550fe080-bb5c-11e9-94bc-ee9d4e94b214.png)

cc: @sashadev-sky

**Comment by sashadev-sky** [comment]
@divyabaid16 what is ur operating system / browser? Is this problem in the production, locally, or both for you? I cannot reproduce this problem in either and I did thorough cross browser / platform testing upstream in LDI but maybe there are some blind spots! 
Possibly can you try clearing your cache in browser and in Rails?

**Comment by divyabaid16** [comment]
My operating system is Linux Mint 18.2 and I have checked in Chrome as well as Mozilla firefox. 
For me, it just happened locally when I fetched all the recent commits to the main branch. 
I cleared the cache and I'm still getting the same result.

**Comment by sashadev-sky** [comment]
@divyabaid16 would you mind running https://github.com/publiclab/Leaflet.DistortableImage locally and letting me know if you see the icons there? Sorry thats a little time consuming, it'll just narrow down the issue a lot quicker

**Comment by sashadev-sky** [comment]
Or quick check would be here: https://sasha.mapknitter.org/examples/select.html because it has the latest updates. Browser stack doesn't have Linux but the icons work for me there back to IE 11 Windows 7

**Comment by divyabaid16** [comment]
> Or quick check would be here: https://sasha.mapknitter.org/examples/select.html because it has the latest updates.

I can see icons in this one.

**Comment by sashadev-sky** [comment]
@divyabaid16 The latest update only has 8 tools in the toolbar. It looks like your main branch is up to date, are you sure you running the server from it?

**Comment by sashadev-sky** [comment]
just double checked logged in and logged out scenarios to debug and ruling that out

**Comment by divyabaid16** [comment]
Ya, I just checked on everything, I'm not sure what is wrong here.
Can anyone else confirm if they are facing the same issue @publiclab/mapknitter-reviewers

**Comment by cesswairimu** [comment]
Its working fine on my end.. @divyabaid16  did you run `yarn install` after pulling the changes

**Comment by divyabaid16** [comment]
Oh I forgot ```yarn install``` and now it's working fine. 
Thank you @cesswairimu @sashadev-sky

**Comment by divyabaid16** [comment]
This is happening for me again and this time I'm not even able to place the images on the map.
@sashadev-sky @cesswairimu

**Comment by cesswairimu** [comment]
Hi Divya,  will try it on my end and see if it is working for me.

**Comment by cesswairimu** [comment]
Its working fine on my machine :thinking: are there any errors in console?

**Comment by gauravano** [comment]
I remember encountering such error a week ago while reviewing PR - 935 but it's working fine now on main. @divyabaid16 update your main and try if you are getting the error again. Thanks!!

**Comment by sashadev-sky** [comment]
Confirmed its working fine! @divyabaid16 please provide a snapshot of your current view with the icons not working so we can see what you are seeing

**Comment by sashadev-sky** [comment]
and any errors in the console that appear relevant!

**Comment by divyabaid16** [comment]
Now it's working fine.
Thanks all!
