### ISSUE TITLE
anonymous image upload not working

### ISSUE THREAD

**Issue by adamdgriffith** [publiclab/mapknitter#95]
One of my students tried to upload an image after creating an anonymous map.  It said you must be logged in.  See screen cap.  I also noticed that the anonymous user in Ukraine has created a map anonymously, but there are no images in them.  Perhaps they also can not upload images.
Using Chrome browser.
![untitled](https://cloud.githubusercontent.com/assets/1449163/6168866/1a686e84-b297-11e4-8490-8c630cef579f.jpg)

**Comment by jywarren** [comment]
This is resolved in MapKnitter 2 which will launch starting tomorrow at 10am ET. Thanks!

**Comment by adamdgriffith** [comment]
Oh AWESOME!  Thanks!
