### ISSUE TITLE
double-check export functionality before 2.0 launch

### ISSUE THREAD

**Issue by timwaters** [publiclab/mapknitter#96]
For mapknitter 2 the exports do not seem to work

![image](https://cloud.githubusercontent.com/assets/48941/6169999/3a64955a-b2c9-11e4-9175-ec16f7ded423.png)

ubuntu 12, chrome 41

**Comment by jywarren** [comment]
Hi, Tim - I believe this is because we haven't set up the prerequisites on the test server; it runs fine locally. I'll double check this before launch. Thanks!

**Comment by timwaters** [comment]
:+1:
