### ISSUE TITLE
Add border to Authors in gallery template

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/mapknitter#965]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

![Selection_246](https://user-images.githubusercontent.com/32747809/63650237-16864280-c766-11e9-93c6-944a3e09eb6a.png)

In https://mapknitter.org/gallery "Authors" tab, sometimes when the image is completely white, it becomes difficult to distinguish the image from the gallery template. So add a border here.
After [this](https://github.com/publiclab/mapknitter/blob/main/app/assets/stylesheets/style.scss#L179) line add
```
border: 1px solid #ddd;
```

To get help installing the application on your computer, see [the project README](https://github.com/publiclab/mapknitter/tree/main/README.md) and get help at #307 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by Sravanksk** [comment]
Hello @divyabaid16  Can I take this ?

**Comment by divyabaid16** [comment]
Ya go ahead @Sravanksk

**Comment by Sravanksk** [comment]
Yeah , Thank you.

**Comment by TantumErgo** [comment]
@divyabaid16 Is this issue still open? I took a look at the pull request, but it was left unfinished 8 days ago.

**Comment by pkayres** [comment]
Hey i'm sorry about this. I'm first timer to open source and I pulled this down and fixed the issue without realizing you're only supposed to fix this once. Just thought I'd let you know just in case that makes things difficult for any reason. Sorry again!

**Comment by cesswairimu** [comment]
No worries @pkayres, did you find another issue yet or you still looking for one?

**Comment by pkayres** [comment]
Hey @cesswairimu I didn't. Got a little intimidated after that hahaha.

**Comment by pkayres** [comment]
Awesome thanks!

**Comment by b18050** [comment]
if this issue is  still open, i will like to work on this..

**Comment by cesswairimu** [comment]
Fixed in https://github.com/publiclab/mapknitter/pull/966 closing this
