### ISSUE TITLE
Delete unwanted initializer

### ISSUE THREAD

**Issue by alaxalves** [publiclab/mapknitter#987]
This file https://github.com/publiclab/mapknitter/blob/main/config/initializers/column_definition.rb seems to be totally useless. I think it's a nice idea to delete it.

**Comment by alaxalves** [comment]
@sashadev-sky @jywarren Am I right?

**Comment by sashadev-sky** [comment]
@alaxalves I would not delete this! I started seeing MYSQL errors after it was commented out. In fact, I think it should be uncommented, or the database fixed up! I left all of the relevant notes regarding it in the column above it

**Comment by sashadev-sky** [comment]
closed via #959
