### ISSUE TITLE
Puma server is not working 

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#996]
Replicate this:

- rebase branch with upstream main
- bundle install
- yarn install
- rails s  ---> `No such file or directory @ rb_sysopen - app/tmp/pids/puma.pid (Errno::ENOENT)`

Tried also
- gem install puma
- `puma config.ru` ---> same error

From Procfile
- `puma -C config/puma.rb` --> same error

Also it seems that the default environment has been set to production? Do we mean to use `passenger` for development and `puma` for production? Or `puma` for both because its ncessary for action cable? @alaxalves

**Comment by sashadev-sky** [comment]
@publiclab/mapknitter-reviewers @alaxalves @kaustubh-nair @jywarren

**Comment by alaxalves** [comment]
@sashadev-sky Puma is needed to run actioncable and passeger is needed to serve MK. In order to run passenger and puma you have to install the forego package and `forego start`.

**Comment by alaxalves** [comment]
BTW I was'nt able to reproduce this issue.

**Comment by sashadev-sky** [comment]
@alaxalves we cannot also serve MK on puma? I think that is what im doing / its working in #959 

It is a local setup! the `tmp` folder is not inside the `app` folder so that error makes sense

**Comment by alaxalves** [comment]
> @alaxalves we cannot also serve MK on puma? I think that is what im doing / its working in #959
> 
> It is a local setup! the `tmp` folder is not inside the `app` folder so that error makes sense

@sashadev-sky Puma is not very good/recomended to serve on production, because it's too slow. I think that's why we use Passenger instead. But using it only for ActionCable is not a problem.

**Comment by sashadev-sky** [comment]
@alaxalves gotchya! Ok well i reversed the puma configs in #959 (except for the pidpath which locally, should actually be `tmp/pids/puma.pid`

Would you mind reviewing #959 im keen to get it merged :)

**Comment by alaxalves** [comment]
@sashadev-sky In order to run Passenger and Puma you have to [install ForeGo](https://dl.equinox.io/ddollar/forego/stable). After that you can `forego start`. I found out there's an error on puma.rb file that makes it work only inside docker, I'll submit a PR fixing it

**Comment by alaxalves** [comment]
The puma config on #959 looks completely OK to me. I'll test it on docker and if everything goes well I'll approve it.

**Comment by sashadev-sky** [comment]
@alaxalves sometimes I decide to have devOps days 😅
