### ISSUE TITLE
.yarnrc /public/lib/ for yarn assets

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter#999]
Hi all, just making a good place for us to figure this out together -- back in #885, @alaxalves noted:

> Experiencing this super annoyin issue rn, but I think it's because of our dependencies folder definition in .yarnrc file. Yarn looks for the dependencies by default on node_modules/ folder and not the public/lib/ defined by us.

This deletion of `.yarnrc` may be causing us some trouble... the `.yarnrc` setting is needed to preserve public accessibility of yarn assets such as images, stylesheets, fonts. 

I added it back in in `main` branch but we should try to work this problem. cc @kaustubh-nair @sashadev-sky !

We're testing things out on unstable now... let's see.

**Comment by jywarren** [comment]
https://github.com/publiclab/mapknitter/blob/e7da08085f74d8283f61502448ab238e86c14cd4/.yarnrc#L1-L2

**Comment by jywarren** [comment]
OK, I opened a PR to complete this transition at https://github.com/publiclab/mapknitter/pull/1000, but it'll need testing, esp. on unstable. @sashadev-sky you may want to pull this into your unstable tests too?

**Comment by alaxalves** [comment]
I removed it because we started using default `node_modules/` folder to install the assets. We were having mismatch of dependencies and assets installation. Some assets that depended on others were failing to load, because of its relative path finding. I suggest we keep .yarnrc but using node_modules/ and not public/lib/.

**Comment by alaxalves** [comment]
> I removed it because we started using default `node_modules/` folder to install the assets. We were having mismatch of dependencies and assets installation. Some assets that depended on others were failing to load, because of its relative path finding. I suggest we keep .yarnrc but using node_modules/ and not public/lib/.

This is caused due to a Yarn issue. It's not a MapKnitter issue. Even though we define our installation path in `public/lib` folder, Yarn has problems finding those. That's why I have set the installation to use Yarn's default folder `node_modules/`. 

Check the links and comment I have provided [here](https://github.com/publiclab/mapknitter/pull/885#issuecomment-516237923)

**Comment by jywarren** [comment]
Thanks, Alax - the potential issue we've seen before is that some JS assets need a publicly accessible URL to their assets, especially those referenced from stylesheets - so, icon images used in styles, as well as font assets. This has come up before for example with the "layer select icon" used in Leaflet's layer control. 

However, have we set up the asset pipeline to route requests for static assets to the `node_modules` folder? If we have, then we don't have to worry about it because we can point libs like Leaflet at the resulting URL. 

For example, you can see here we've manually overridden the path for Leaflet's `imagePath`, pointing at a static location:

https://github.com/publiclab/plots2/blob/65096e88b43baa9749df821976ccfe00ee362e66/app/assets/javascripts/setup.js#L2

`L.Icon.Default.imagePath = '/assets/leaflet/dist/images/';`

If this is possible, then we don't have to move back to `/public/lib` and we'll be fine. Otherwise, we'll have to figure out something else... maybe a symlink or something? But I'm sure we can think through it!

Thanks for responding!

**Comment by jywarren** [comment]
Like, i think the asset pipeline is set up to route requests to `/assets/FOO` to wherever we point it. So if that is working, we should be good. 

http://mapknitter-stable.laboratoriopublico.org/assets/leaflet-distortableimage/package.json

OK, so this works. With a +1 from @alaxalves we should be good here then?

**Comment by jywarren** [comment]
And then we'd be able to undo the `.yarnrc` change.

**Comment by alaxalves** [comment]
> Like, i think the asset pipeline is set up to route requests to `/assets/FOO` to wherever we point it. So if that is working, we should be good.
> 
> http://mapknitter-stable.laboratoriopublico.org/assets/leaflet-distortableimage/package.json
> 
> OK, so this works. With a +1 from @alaxalves we should be good here then?

Yes, I was careful to link every asset reference to the updated path, thus keeping MK's compatibility when loading assets. Every `public/lib/` reference I changed to Yarn's default `node_modules/`. If we experience any asset loading related issue, we could open another issue.

**Comment by alaxalves** [comment]
> > Like, i think the asset pipeline is set up to route requests to `/assets/FOO` to wherever we point it. So if that is working, we should be good.
> > http://mapknitter-stable.laboratoriopublico.org/assets/leaflet-distortableimage/package.json
> > OK, so this works. With a +1 from @alaxalves we should be good here then?
> 
> Yes, I was careful to link every asset reference to the updated path, thus keeping MK's compatibility when loading assets. Every `public/lib/` reference I changed to Yarn's default `node_modules/`. If we experience any asset loading related issue, we could open another issue.

The `assets/` folder is because Rails looks for assets in its default folder `public/`, and we have set yarn to reference its installed assets on this folder too(`public/assets/`), as well as in `node_modules/` folder.

**Comment by alaxalves** [comment]
> Thanks, Alax - the potential issue we've seen before is that some JS assets need a publicly accessible URL to their assets, especially those referenced from stylesheets - so, icon images used in styles, as well as font assets. This has come up before for example with the "layer select icon" used in Leaflet's layer control.
> 
> However, have we set up the asset pipeline to route requests for static assets to the `node_modules` folder? If we have, then we don't have to worry about it because we can point libs like Leaflet at the resulting URL.
> 
> For example, you can see here we've manually overridden the path for Leaflet's `imagePath`, pointing at a static location:
> 
> https://github.com/publiclab/plots2/blob/65096e88b43baa9749df821976ccfe00ee362e66/app/assets/javascripts/setup.js#L2
> 
> `L.Icon.Default.imagePath = '/assets/leaflet/dist/images/';`
> 
> If this is possible, then we don't have to move back to `/public/lib` and we'll be fine. Otherwise, we'll have to figure out something else... maybe a symlink or something? But I'm sure we can think through it!
> 
> Thanks for responding!

I think that in https://github.com/publiclab/plots2/blob/65096e88b43baa9749df821976ccfe00ee362e66/app/assets/javascripts/setup.js#L2 the url should be `assets/FOO` and not `/assets/FOO`, because Sprockets will look into `public/` folder already, thus we shouls reference the assets path. But we should confim this first, I'm not 100% sure. @sashadev-sky can you confirm this?

**Comment by sashadev-sky** [comment]
Not really sure about the sprockets convention. 

But we use `/assets` all over the repo. Especially for `javascript_includee_tags`. (perhaps wrongly because there is a lot of unused code). So would be good to look into

**Comment by alaxalves** [comment]
> Not really sure about the sprockets convention.
> 
> But we use `/assets` all over the repo. Especially for `javascript_includee_tags`. (perhaps wrongly because there is a lot of unused code). So would be good to look into

I agree!

**Comment by jywarren** [comment]
I'm going to revert the .yarnrc change I'd made, but for the change between `assets/FOO` and `/assets/FOO` another issue may need to be opened! Thanks, all!

**Comment by jywarren** [comment]
One more note here! I realized something we'd seen while debugging just before this issue that I just now understood - if the assets are available at `/public/lib/FOO` then they will override those available at `/assets/FOO` (i.e. from node_modules) -- so in production we'll have to manually remove the old ones or they'll override the newer versions.

**Comment by jywarren** [comment]
Also noting that I found we had an `/assets/FOO` _folder_ which had to be removed as well before it would go all the way to `node_modules`.
